SLIC: TrackManager Class Reference
TrackManager Class Reference
Manages access to stored track information used for MCParticle output.
#include <TrackManager.hh>
Public Member Functions
TrackManager ()
virtual ~TrackManager ()
TrackSummary * findTrackSummary (G4int trackID)
TrackSummaryVector * getTrackSummaries ()
TrackSummaryMap * getTrackSummaryMap ()
void registerTrackSummary (TrackSummary *trackSummary)
void reset ()
void saveTrackSummaries (const G4Event *event, LCEvent *lcevent)
Public Member Functions inherited from Singleton< TrackManager >
Singleton ()
~Singleton ()
void release ()
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void stepping (const G4Step *)
Private Member Functions
TrackSummary * findFirstSavedAncestor (TrackSummary *trackSummary)
Private Attributes
TrackSummaryVector * _trackSummaries
TrackSummaryMap * _trackSummaryMap
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Static Public Member Functions inherited from Singleton< TrackManager >
static TrackManager * instance ()
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
Manages access to stored track information used for MCParticle output.
Definition at line 23 of file TrackManager.hh.
Constructor & Destructor Documentation
TrackManager()
TrackManager () inline
Class constructor.
Definition at line 30 of file TrackManager.hh.
                        :
                 Module("TrackManager") {
             _trackSummaries = new TrackSummaryVector;
             _trackSummaryMap = new TrackSummaryMap;
         }
References TrackManager::_trackSummaries, and TrackManager::_trackSummaryMap.
~TrackManager()
virtual ~TrackManager () inline virtual
Class destructor.
Definition at line 39 of file TrackManager.hh.
{
             delete _trackSummaries;
             delete _trackSummaryMap;
         }
References TrackManager::_trackSummaries, and TrackManager::_trackSummaryMap.
Member Function Documentation
findFirstSavedAncestor()
TrackSummary * findFirstSavedAncestor (TrackSummary * trackSummary) private
Find the first saved ancestor of a TrackSummary and associate it to the first saved MCParticle ancestor.
Parameters
[in] trackSummary The child TrackSummary.
Returns
The first saved ancestor TrackSummary.
Definition at line 124 of file TrackManager.cc.
{
     TrackSummary* parent = trackSummary->findParent();
     while (parent != 0) {
         if (parent->getToBeSaved() == true) {
             /* Associate the track ID to the first MCParticle up the tree that will be saved. */
             MCParticleManager::instance()->addMCParticleTrackID(trackSummary->getTrackID(), parent->getMCParticle());
             break;
         }
         parent = parent->findParent();
     }
     return parent;
 }
References TrackSummary::findParent(), TrackSummary::getMCParticle(), TrackSummary::getToBeSaved(), TrackSummary::getTrackID(), and Singleton< MCParticleManager >::instance().
Referenced by TrackManager::saveTrackSummaries().
findTrackSummary()
TrackSummary* findTrackSummary (G4int trackID) inline
Find a TrackSummary by track ID.
Parameters
[in] trackID The track ID.
Returns
The matching TrackSummary or NULL if not found.
Definition at line 96 of file TrackManager.hh.
{
             return (*_trackSummaryMap)[trackID];
         }
References TrackManager::_trackSummaryMap.
Referenced by TrackSummary::findParent().
getTrackSummaries()
TrackSummaryVector* getTrackSummaries () inline
Get the current collection of TrackSummary objects.
Returns
The current collection of TrackSummaries.
Definition at line 50 of file TrackManager.hh.
{
             return _trackSummaries;
         }
References TrackManager::_trackSummaries.
getTrackSummaryMap()
TrackSummaryMap* getTrackSummaryMap () inline
Get the map of TrackSummary objects to track IDs.
Returns
The TrackSummaryMap.
Definition at line 79 of file TrackManager.hh.
{
             return _trackSummaryMap;
         }
References TrackManager::_trackSummaryMap.
registerTrackSummary()
void registerTrackSummary (TrackSummary * trackSummary) inline
Map a TrackSummary to its track ID.
Parameters
[in] trackSummary The TrackSummary.
Definition at line 87 of file TrackManager.hh.
{
             (*_trackSummaryMap)[trackSummary->getTrackID()] = trackSummary;
         }
References TrackSummary::getTrackID().
reset()
void reset () inline virtual
Reset the state of this object by clearing data structures.
Reimplemented from Module.
Definition at line 64 of file TrackManager.hh.
                      {
             /* Clear the vector. */
             for (TrackSummaryVector::iterator it = _trackSummaries->begin(); it != _trackSummaries->end(); it++) {
                 delete *it;
             }
             _trackSummaries->clear();
             /* Clear the map. */
             _trackSummaryMap->clear();
         }
References TrackManager::_trackSummaries, and TrackManager::_trackSummaryMap.
saveTrackSummaries()
void saveTrackSummaries (const G4Event * event, LCEvent * lcevent)
Save the TrackSummary vector into a collection of MCParticles in an output LCEvent.
Parameters
[in] event The current G4Event.
[in,out] lcevent The output LCEvent.
Definition at line 23 of file TrackManager.cc.
{
     /* If Geant4 event generation was used, then an empty MCParticle collection needs to be created. */
     G4bool geant4Generator = false;
     if (MCParticleManager::instance()->getMCParticleCollection() == NULL) {
         //std::cout << "creating empty MCParticle collection" << std::endl;
         MCParticleManager::instance()->createMCParticleCollection();
         geant4Generator = true;
     }
     /* Copy MCParticle pointers into the corresponding TrackSummary objects for primary particles. */
     PrimaryParticleMap* particleMap = MCParticleManager::instance()->getPrimaryParticleMap();
     for (PrimaryParticleMapIterator it = particleMap->begin(); it != particleMap->end(); it++) {
         if (it->second == 0) {
             G4Exception("", "", FatalException, "MCParticle was mapped to null G4PrimaryParticle.");
         }
         if (it->second->GetTrackID() < 0)
             continue;
         for (int j = _trackSummaries->size() - 1; j >= 0; j--) {
             if (_trackSummaries->operator[](j)->getTrackID() == it->second->GetTrackID()) {
                 //std::cout << "setting MCParticle " << it->first << " on TrackSummary from primary" << std::endl;
                 _trackSummaries->operator[](j)->setMCParticle(dynamic_cast<MCParticleImpl*>(it->first));
 #ifdef SLIC_LOG
                 log() << LOG:: debug << "primary " << MCParticleManager::instance()->indexOf(it->second)
                 << " had track ID " << _trackSummaries->operator[](j)->getTrackID() << LOG::done;
 #endif
                 break;
             }
         }
     }
     G4bool writeCompleteEvent = LcioManager::instance()->getWriteCompleteEvent();
     // Set parents to be saved on particles that will be persisted.
     for (G4int k = _trackSummaries->size() - 1; k >= 0; k--) {
         // Save all TrackSummary objects if full event is being written.
         //if (writeCompleteEvent)
         //    (*_trackSummaries)[k]->setToBeSaved();
         // Force parents to be saved if TrackSummary will be saved.
         if (((*_trackSummaries)[k])->getToBeSaved())
             ((*_trackSummaries)[k])->setParentToBeSaved();
     }
     /* Get the MCParticle collection created by event generation. */
     LCCollectionVec* mcpVec = MCParticleManager::instance()->getMCParticleCollection();
     /* Save TrackSummary objects to LCIO collection. */
 #ifdef SLIC_LOG
     /*log() << LOG::okay << "TrackManager processing " << _trackSummaries->size() << " TrackSummary objects." << LOG::done;*/
 #endif
     size_t l;
     TrackSummary* trackSummary;
     for (l = 0; l < _trackSummaries->size(); l++) {
         trackSummary = (*_trackSummaries)[l];
         //| writeCompleteEvent
         if (trackSummary->getToBeSaved()) {
             /* Build the MCParticle in case it hasn't been created yet. */
             if (trackSummary->getMCParticle() == 0) {
                 trackSummary->buildMCParticle();
             }
             /* Associate the track ID to the MCParticle for the hit maker. */
             MCParticleManager::instance()->addMCParticleTrackID(trackSummary->getTrackID(), trackSummary->getMCParticle());
             /*
              * Only particles created in the simulation need to be added, as the generator MCParticles
              * associated with primaries were already.  But if a Geant4 internal generator was used
              * such as the GPS or ParticleGun, then all particles with the save flag on should be added
              * here, as they will all be flagged as sim particles and would not have been added yet.
              */
             if (trackSummary->getMCParticle()->getGeneratorStatus() == 0 || geant4Generator) {
                 if (trackSummary->getMCParticle() != NULL) {
                     mcpVec->push_back(trackSummary->getMCParticle());
                     // DEBUG
                     //if (trackSummary->getParentID() <= 0)
                     //    G4cout << "WARNING: sim particle with track ID " << trackSummary->getTrackID() << " has no parent!" << G4endl;
                 }
             }
         } else {
             // If the track will not be saved then associate the information to its first persisted ancestor.
             // This will allow association between track IDs from sensitive detector's in LCDD to their appropriate
             // MCParticle objects in the output collection.
             findFirstSavedAncestor(trackSummary);
         }
     }
     /* Set flag so it is saved. */
     mcpVec->setFlag(0xe0000000);
     /* Save the MCParticle collection into the event. */
     lcEvent->addCollection((LCCollection*) mcpVec, "MCParticle");
 #ifdef SLIC_LOG
     //log() << LOG::always << "Saved " << mcpVec->getNumberOfElements() << " MCParticles." << LOG::done;
 #endif
 }
References TrackManager::_trackSummaries, TrackSummary::buildMCParticle(), LOG::debug, LOG::done, TrackManager::findFirstSavedAncestor(), TrackSummary::getMCParticle(), TrackSummary::getToBeSaved(), TrackSummary::getTrackID(), Singleton< MCParticleManager >::instance(), Singleton< LcioManager >::instance(), and Module::log().
Member Data Documentation
_trackSummaries
TrackSummaryVector* _trackSummaries private
Definition at line 112 of file TrackManager.hh.
Referenced by TrackManager::getTrackSummaries(), TrackManager::reset(), TrackManager::saveTrackSummaries(), TrackManager::TrackManager(), and TrackManager::~TrackManager().
_trackSummaryMap
TrackSummaryMap* _trackSummaryMap private
Definition at line 113 of file TrackManager.hh.
Referenced by TrackManager::findTrackSummary(), TrackManager::getTrackSummaryMap(), TrackManager::reset(), TrackManager::TrackManager(), and TrackManager::~TrackManager().
The documentation for this class was generated from the following files:
TrackManager.hh
TrackManager.cc