SLIC: G4MagIntegratorStepperFactory Class Reference
G4MagIntegratorStepperFactory Class Reference
Instantiates and sets the G4MagIntegratorStepper based on name.
#include <G4MagIntegratorStepperFactory.hh>
Public Member Functions
G4MagIntegratorStepperFactory ()
virtual ~G4MagIntegratorStepperFactory ()
void setupG4MagIntegratorStepper (std::string name)
Public Member Functions inherited from Singleton< G4MagIntegratorStepperFactory >
Singleton ()
~Singleton ()
void release ()
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Private Member Functions
G4MagIntegratorStepper * createG4MagIntegratorStepper (std::string name)
Private Attributes
G4MagneticField * m_field
G4Mag_EqRhs * m_fieldEquations
G4FieldManager * m_fieldMgr
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Static Public Member Functions inherited from Singleton< G4MagIntegratorStepperFactory >
static G4MagIntegratorStepperFactory * instance ()
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
Instantiates and sets the G4MagIntegratorStepper based on name.
Definition at line 22 of file G4MagIntegratorStepperFactory.hh.
Constructor & Destructor Documentation
G4MagIntegratorStepperFactory()
G4MagIntegratorStepperFactory ()
Class constructor.
Definition at line 26 of file G4MagIntegratorStepperFactory.cc.
References LOG::done, LOG::error, Module::log(), G4MagIntegratorStepperFactory::m_field, G4MagIntegratorStepperFactory::m_fieldEquations, and G4MagIntegratorStepperFactory::m_fieldMgr.
~G4MagIntegratorStepperFactory()
~G4MagIntegratorStepperFactory () virtual
Class destructor.
Definition at line 37 of file G4MagIntegratorStepperFactory.cc.
References G4MagIntegratorStepperFactory::m_fieldEquations.
Member Function Documentation
createG4MagIntegratorStepper()
G4MagIntegratorStepper * createG4MagIntegratorStepper (std::string name) private
Create an integrator stepper.
Returns
The integrator stepper.
Definition at line 56 of file G4MagIntegratorStepperFactory.cc.
References LOG::done, LOG::error, Module::log(), G4MagIntegratorStepperFactory::m_fieldEquations, and LOG::name.
Referenced by G4MagIntegratorStepperFactory::setupG4MagIntegratorStepper().
setupG4MagIntegratorStepper()
void setupG4MagIntegratorStepper (std::string name)
Setup an integrator stepper by name.
Parameters
[in] name The name of the stepper.
Definition at line 41 of file G4MagIntegratorStepperFactory.cc.
References G4MagIntegratorStepperFactory::createG4MagIntegratorStepper(), G4MagIntegratorStepperFactory::m_field, G4MagIntegratorStepperFactory::m_fieldMgr, and LOG::name.
Member Data Documentation
m_field
G4MagneticField* m_field private
Definition at line 55 of file G4MagIntegratorStepperFactory.hh.
Referenced by G4MagIntegratorStepperFactory::G4MagIntegratorStepperFactory(), and G4MagIntegratorStepperFactory::setupG4MagIntegratorStepper().
m_fieldEquations
G4Mag_EqRhs* m_fieldEquations private
Definition at line 53 of file G4MagIntegratorStepperFactory.hh.
Referenced by G4MagIntegratorStepperFactory::createG4MagIntegratorStepper(), G4MagIntegratorStepperFactory::G4MagIntegratorStepperFactory(), and G4MagIntegratorStepperFactory::~G4MagIntegratorStepperFactory().
m_fieldMgr
G4FieldManager* m_fieldMgr private
Definition at line 54 of file G4MagIntegratorStepperFactory.hh.
Referenced by G4MagIntegratorStepperFactory::G4MagIntegratorStepperFactory(), and G4MagIntegratorStepperFactory::setupG4MagIntegratorStepper().
The documentation for this class was generated from the following files:
G4MagIntegratorStepperFactory.hh
G4MagIntegratorStepperFactory.cc