SLIC: SlicApplication Class Reference
SlicApplication Class Reference
Singleton class for a Geant4 application.
#include <SlicApplication.hh>
Public Types
enum ErrorCode {
OKAY = 0, UNKNOWN_ERROR, UNKNOWN_EXCEPTION, STD_EXCEPTION,
OUTPUT_FILE_EXISTS, FAILED_DELETE_LCIO_FILE, EVENT_UNDERFLOW, INVALID_GEOMETRY_SETUP,
GENERATOR_NOT_SETUP, ERROR_CODE_SIZE
}
enum ERunMode { eBatch = 1, eInteractive = 2 }
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Member Functions
SlicApplication ()
virtual ~SlicApplication ()
const std::string & getBinaryBasename () const
const std::string & getBinaryName () const
const char * getErrorCodeString (unsigned int errorCode)
ERunMode getMode () const
int getReturnCode () const
RunManager * getRunManager ()
void initialize ()
void initialize (int argc, char **argv)
bool isAborting () const
void printEndTime ()
void printSplashScreen ()
void printStartTime ()
void printUsage ()
void printVersion ()
void run ()
void setAborting (bool a=true)
void setMode (ERunMode rmode)
void setReturnCode (int rc)
Public Member Functions inherited from Singleton< SlicApplication >
Singleton ()
~Singleton ()
void release ()
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Protected Attributes
SlicApplicationMessenger * m_appMessenger
std::string m_binarybasename
std::string m_binaryname
FieldMessenger * m_fieldMessenger
std::string * m_geant4VersionString
bool m_isInitialized
ERunMode m_mode
int m_returnCode
RunManager * m_runManager
G4UIExecutive * m_ui
Private Member Functions
void initializeLCDD ()
void initializeUserActions ()
void initializeVis ()
void setBinaryBasename ()
Additional Inherited Members
Static Public Member Functions inherited from Singleton< SlicApplication >
static SlicApplication * instance ()
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
Singleton class for a Geant4 application.
Note
Instantiates manager and messenger classes, including user actions, G4RunManager, GeneratorManager, and PhysicsListManager.
Definition at line 40 of file SlicApplication.hh.
Member Enumeration Documentation
ErrorCode
enum ErrorCode
Error codes.
Enumerator
OKAY
UNKNOWN_ERROR
UNKNOWN_EXCEPTION
STD_EXCEPTION
OUTPUT_FILE_EXISTS
FAILED_DELETE_LCIO_FILE
EVENT_UNDERFLOW
INVALID_GEOMETRY_SETUP
GENERATOR_NOT_SETUP
ERROR_CODE_SIZE
Definition at line 54 of file SlicApplication.hh.
{
             OKAY = 0, UNKNOWN_ERROR,
             UNKNOWN_EXCEPTION,
             STD_EXCEPTION,
             OUTPUT_FILE_EXISTS,
             FAILED_DELETE_LCIO_FILE,
             EVENT_UNDERFLOW,
             INVALID_GEOMETRY_SETUP,
             GENERATOR_NOT_SETUP,
             ERROR_CODE_SIZE
         };
ERunMode
enum ERunMode
Indicates the run mode: batch or interactive.
Enumerator
eBatch
eInteractive
Definition at line 47 of file SlicApplication.hh.
                       {
             eBatch = 1, eInteractive = 2
         };
Constructor & Destructor Documentation
SlicApplication()
SlicApplication ()
The constructor.
Definition at line 30 of file SlicApplication.cc.
                                  :
         Module("SlicApplication", false), m_appMessenger(0), m_runManager(0), m_mode(SlicApplication::eBatch), m_returnCode(0), m_isInitialized(false), m_geant4VersionString(0) {
 #ifdef SLIC_LOG
     log() << LOG::okay << LOG::head << "SLIC is starting." << LOG::done;
 #endif
 }
References LOG::done, LOG::head, Module::log(), and LOG::okay.
~SlicApplication()
~SlicApplication () virtual
The destructor.
Definition at line 37 of file SlicApplication.cc.
{
     if (m_appMessenger != 0) {
         delete m_appMessenger;
     }
     // Deletion of all modules is commented out as iterating the
     // map causes a seg fault in more recent gcc versions like 9,
     // for unknown reasons. Should not have any effect since the
     // application is exiting anyways and there are no modules
     // which perform any meaningful cleanup in their destructors. --JM
 /*
 #ifdef linux
 #ifdef SLIC_LOG
     log().debug("Deleting registered modules ...");
 #endif
     ModuleRegistry::instance()->deleteModules();
 #endif
 */
     // Delete the G4RunManager, which also deletes all the Geant4-related modules.
 //#ifdef SLIC_LOG
 //    log().debug("Deleting G4RunManager ...");
 //#endif
 //    delete G4RunManager::GetRunManager();
 #ifdef SLIC_LOG
     log() << LOG::okay << LOG::head << "SLIC is exiting." << LOG::done;
     log() << "return code: " << getReturnCode() << " => " << getErrorCodeString(getReturnCode()) << LOG::done;
 #endif
 }
References LOG::done, SlicApplication::getErrorCodeString(), SlicApplication::getReturnCode(), LOG::head, Module::log(), SlicApplication::m_appMessenger, and LOG::okay.
Member Function Documentation
getBinaryBasename()
const std::string & getBinaryBasename () const
Get the base name of the binary (file name only).
Returns
The base name of the binary.
Definition at line 141 of file SlicApplication.cc.
{
     return m_binarybasename;
 }
References SlicApplication::m_binarybasename.
getBinaryName()
const std::string & getBinaryName () const
Get the name of the binary, as it was invoked from the command line.
Returns
The name of the binary.
Definition at line 137 of file SlicApplication.cc.
{
     return m_binaryname;
 }
References SlicApplication::m_binaryname.
getErrorCodeString()
const char* getErrorCodeString (unsigned int errorCode) inline
Get a string representation of an error code.
Parameters
[in] errorCode The errorCode.
Returns
The string representation of the error code.
Definition at line 182 of file SlicApplication.hh.
{
             if (errorCode > (ERROR_CODE_SIZE - 1)) {
                 log() << LOG::error << "invalid error code requested: " << errorCode << LOG::done;
                 throw new std::exception();
             }
             return ErrorCodeStrings[errorCode];
         }
References LOG::done, LOG::error, SlicApplication::ERROR_CODE_SIZE, slic::ErrorCodeStrings, and Module::log().
Referenced by SlicApplication::~SlicApplication().
getMode()
SlicApplication::ERunMode getMode () const
Get the run mode, interactive or batch.
Returns
The run mode.
Definition at line 160 of file SlicApplication.cc.
{
     return m_mode;
 }
References SlicApplication::m_mode.
Referenced by SlicApplication::run().
getReturnCode()
int getReturnCode () const
Get the return code.
Returns
The return code.
Definition at line 145 of file SlicApplication.cc.
{
     return m_returnCode;
 }
References SlicApplication::m_returnCode.
Referenced by SlicMain::main(), and SlicApplication::~SlicApplication().
getRunManager()
RunManager * getRunManager ()
Return SLIC's RunManager instance.
Returns
The RunManager instance.
Definition at line 170 of file SlicApplication.cc.
{
     return m_runManager;
 }
References SlicApplication::m_runManager.
initialize() [1/2]
void initialize () virtual
Initialize the application.
Reimplemented from Module.
Definition at line 81 of file SlicApplication.cc.
{
     if (!m_isInitialized) {
         // Print the SLIC splash screen.
         printSplashScreen();
         // Initialize the application messenger.
         m_appMessenger = new SlicApplicationMessenger(this);
         // Create a new RunManager.
         m_runManager = new RunManager();
         PhysicsListManager::instance();
         // Initialize the LcioManager.
         LcioManager::instance();
         // Initialize the magnetic field messenger.
         FieldManager::instance();
         // Setup the LCDD subsystem.
         initializeLCDD();
         // Initialize the tracker manager.
         TrackManager::instance();
         // Initialize the MCParticle manager.
         MCParticleManager::instance();
         // Initialize visualization.
         initializeVis();
         // Set state variable.
         m_isInitialized = true;
     } else {
         log().warning("Call to SlicApplication::initialize() was ignored.  SLIC is already initialized!");
     }
 }
References SlicApplication::initializeLCDD(), SlicApplication::initializeVis(), Singleton< TrackManager >::instance(), Singleton< PhysicsListManager >::instance(), Singleton< MCParticleManager >::instance(), Singleton< LcioManager >::instance(), Singleton< FieldManager >::instance(), Module::log(), SlicApplication::m_appMessenger, SlicApplication::m_isInitialized, SlicApplication::m_runManager, SlicApplication::printSplashScreen(), and LogStream::warning().
Referenced by SlicMain::main(), and SlicApplication::run().
initialize() [2/2]
void initialize (int argc, char ** argv)
Setup SLIC from command line arguments using the CommandLineProcessor.
Parameters
[in] argc The argument count.
[in] argv The argument values.
Definition at line 69 of file SlicApplication.cc.
{
     // Set the name and basename of slic's binary from the command line arguments.
     m_binaryname = std::string(argv[0]);
     setBinaryBasename();
     // Process arguments using the CommandLineProcessor.
     CommandLineProcessor* cmd = CommandLineProcessor::instance();
     cmd->process(argc, argv);
     m_ui = new G4UIExecutive(argc, argv);
 }
References Singleton< CommandLineProcessor >::instance(), SlicApplication::m_binaryname, SlicApplication::m_ui, CommandLineProcessor::process(), and SlicApplication::setBinaryBasename().
initializeLCDD()
void initializeLCDD () private
Register the LCDDDetectorConstruction.
Definition at line 128 of file SlicApplication.cc.
{
     // LCDD geometry subsystem.
     m_runManager->SetUserInitialization(new LCDDDetectorConstruction());
 }
References SlicApplication::m_runManager.
Referenced by SlicApplication::initialize().
initializeUserActions()
void initializeUserActions () private
Register the Geant4 user action classes with the G4RunManager.
initializeVis()
void initializeVis () private
Initialize the Geant4 visualization subsystem.
Definition at line 119 of file SlicApplication.cc.
 {
     G4VisExecutive* vis = new G4VisExecutive();
     vis->Initialize();
     // VRML writer within SLIC.
     new VRML2WriterMessenger();
 }
Referenced by SlicApplication::initialize().
isAborting()
bool isAborting () const
Get the abort state.
printEndTime()
void printEndTime ()
Print the end time.
printSplashScreen()
void printSplashScreen ()
Print SLIC's splash screen.
Definition at line 203 of file SlicApplication.cc.
{
     log() << LOG::done;
     log() << LOG::always << "*************************************************************" << LOG::done;
     log() << LOG::always << " Application : " << PackageInfo::getFullName() << " (" << PackageInfo::getShortName() << ")" << LOG::done;
     log() << LOG::always << " Version : " << PackageInfo::getVersion() << LOG::done;
     log() << LOG::always << "*************************************************************" << LOG::done;
 }
References LOG::always, LOG::done, and Module::log().
Referenced by SlicApplication::initialize().
printStartTime()
void printStartTime ()
Print the start time.
printUsage()
void printUsage ()
Print the usage by calling the CommandLineProcessor.
Definition at line 211 of file SlicApplication.cc.
{
     CommandLineProcessor::instance()->printUsage();
 }
References Singleton< CommandLineProcessor >::instance().
Referenced by SlicApplicationMessenger::SetNewValue().
printVersion()
void printVersion ()
Print the version string.
Definition at line 199 of file SlicApplication.cc.
{
     CommandLineProcessor::instance()->printVersion();
 }
References Singleton< CommandLineProcessor >::instance().
Referenced by SlicApplicationMessenger::SetNewValue().
run()
void run ()
Run the application.
Definition at line 174 of file SlicApplication.cc.
{
     // Initialize if not already.
     if (!m_isInitialized) {
         initialize();
     }
     // Retrieve the list of Geant4 commands created by CommandLineProcessor.
     CommandQueue* q = CommandLineProcessor::instance()->getCommandQueue();
     // Print, execute, and clear the CommandQueue.
 #ifdef SLIC_LOG
     log().verbose("Printing the Geant4 command queue ...");
     q->printOut();
 #endif
     q->execute();
     q->clear();
     // Start the UI session if in interactive mode.
     if (getMode() == eInteractive) {
         log().verbose("Starting interactive session ...");
         m_ui->SessionStart();
         delete m_ui;
     }
 }
References CommandQueue::clear(), SlicApplication::eInteractive, CommandQueue::execute(), SlicApplication::getMode(), SlicApplication::initialize(), Singleton< CommandLineProcessor >::instance(), Module::log(), SlicApplication::m_isInitialized, SlicApplication::m_ui, CommandQueue::printOut(), and LogStream::verbose().
Referenced by SlicMain::main().
setAborting()
void setAborting (bool a = true)
Set abort state.
Parameters
[in] a The application abort state.
Definition at line 164 of file SlicApplication.cc.
{
     if (abort) {
         G4RunManager::GetRunManager()->AbortRun(abort);
     }
 }
setBinaryBasename()
void setBinaryBasename () private
Set the binary base name from the full name.
Definition at line 153 of file SlicApplication.cc.
{
     std::string::size_type sidx = m_binaryname.find_last_of('/');
     if (sidx != std::string::npos) {
         m_binarybasename = std::string(m_binaryname, sidx + 1);
     }
 }
References SlicApplication::m_binarybasename, and SlicApplication::m_binaryname.
Referenced by SlicApplication::initialize().
setMode()
void setMode (SlicApplication::ERunMode rmode)
Set the run mode.
Parameters
[in] rmode The run mode, either batch or interactive.
Definition at line 133 of file SlicApplication.cc.
{
     m_mode = rmode;
 }
References SlicApplication::m_mode.
Referenced by SlicApplicationMessenger::SetNewValue().
setReturnCode()
void setReturnCode (int rc)
Set the return code.
Parameters
[in] rc The return code.
Definition at line 149 of file SlicApplication.cc.
{
     m_returnCode = rc;
 }
References SlicApplication::m_returnCode.
Member Data Documentation
m_appMessenger
SlicApplicationMessenger* m_appMessenger protected
Definition at line 218 of file SlicApplication.hh.
Referenced by SlicApplication::initialize(), and SlicApplication::~SlicApplication().
m_binarybasename
std::string m_binarybasename protected
Definition at line 236 of file SlicApplication.hh.
Referenced by SlicApplication::getBinaryBasename(), and SlicApplication::setBinaryBasename().
m_binaryname
std::string m_binaryname protected
Definition at line 235 of file SlicApplication.hh.
Referenced by SlicApplication::getBinaryName(), SlicApplication::initialize(), and SlicApplication::setBinaryBasename().
m_fieldMessenger
FieldMessenger* m_fieldMessenger protected
Definition at line 221 of file SlicApplication.hh.
m_geant4VersionString
std::string* m_geant4VersionString protected
Definition at line 239 of file SlicApplication.hh.
m_isInitialized
bool m_isInitialized protected
Definition at line 232 of file SlicApplication.hh.
Referenced by SlicApplication::initialize(), and SlicApplication::run().
m_mode
ERunMode m_mode protected
Definition at line 226 of file SlicApplication.hh.
Referenced by SlicApplication::getMode(), and SlicApplication::setMode().
m_returnCode
int m_returnCode protected
Definition at line 229 of file SlicApplication.hh.
Referenced by SlicApplication::getReturnCode(), and SlicApplication::setReturnCode().
m_runManager
RunManager* m_runManager protected
Definition at line 223 of file SlicApplication.hh.
Referenced by SlicApplication::getRunManager(), SlicApplication::initialize(), and SlicApplication::initializeLCDD().
m_ui
G4UIExecutive* m_ui protected
Definition at line 215 of file SlicApplication.hh.
Referenced by SlicApplication::initialize(), and SlicApplication::run().
The documentation for this class was generated from the following files:
SlicApplication.hh
SlicApplication.cc