SLIC: EventMessenger Class Reference
EventMessenger Class Reference
Messenger for event-related commands.
#include <EventMessenger.hh>
Public Member Functions
EventMessenger ()
virtual ~EventMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
Private Member Functions
void defineCommands ()
Private Attributes
G4UIcmdWithABool * m_eventTimerCmd
Detailed Description
Messenger for event-related commands.
Definition at line 15 of file EventMessenger.hh.
Constructor & Destructor Documentation
EventMessenger()
EventMessenger ()
Class constructor.
Definition at line 10 of file EventMessenger.cc.
References EventMessenger::defineCommands().
~EventMessenger()
~EventMessenger () virtual
Class destructor.
Definition at line 14 of file EventMessenger.cc.
Member Function Documentation
defineCommands()
void defineCommands () private
Define the commands that this messenger with handle.
Definition at line 31 of file EventMessenger.cc.
References EventMessenger::m_eventTimerCmd.
Referenced by EventMessenger::EventMessenger().
SetNewValue()
void SetNewValue (G4UIcommand * command, G4String newValues)
Process the macro command.
Parameters
[in] command The macro command.
[in] newValues The argument values.
Definition at line 17 of file EventMessenger.cc.
References EventAction::enableEventTimer(), EventAction::getEventAction(), and EventMessenger::m_eventTimerCmd.
Member Data Documentation
m_eventTimerCmd
G4UIcmdWithABool* m_eventTimerCmd private
Definition at line 45 of file EventMessenger.hh.
Referenced by EventMessenger::defineCommands(), and EventMessenger::SetNewValue().
The documentation for this class was generated from the following files:
EventMessenger.hh
EventMessenger.cc