SLIC: HitsCollectionUtil Class Reference
HitsCollectionUtil Class Reference
Static utility methods for hits collections.
#include <HitsCollectionUtil.hh>
Static Public Member Functions
static std::vector< int > getHCIDs ()
static std::vector< std::string > getHCNames ()
static std::vector< SensitiveDetector * > getSensitiveDetectors ()
Private Member Functions
HitsCollectionUtil ()
Detailed Description
Static utility methods for hits collections.
Definition at line 16 of file HitsCollectionUtil.hh.
Constructor & Destructor Documentation
HitsCollectionUtil()
HitsCollectionUtil () private
Class constructor.
Member Function Documentation
getHCIDs()
std::vector< int > getHCIDs () static
Get the current list of hits collection IDs.
Returns
The list of hits collection IDS.
Definition at line 37 of file HitsCollectionUtil.cc.
{
     std::vector<int> hcids;
     const std::vector<SensitiveDetector*>& sds = getSensitiveDetectors();
     for (std::vector<SensitiveDetector*>::const_iterator it = sds.begin(); it != sds.end(); it++) {
         SensitiveDetector* sd = (*it);
         for (int i = 0; i < sd->getNumberOfHitsCollections(); i++) {
             hcids.push_back(sd->getHCID(i));
         }
     }
     return hcids;
 }
References HitsCollectionUtil::getSensitiveDetectors().
Referenced by LcioHitsCollectionBuilder::createHitCollections(), and HitsCollectionUtil::getHCNames().
getHCNames()
std::vector< std::string > getHCNames () static
Get the current list of hits collection names.
Returns
The list of hits collection names.
Definition at line 49 of file HitsCollectionUtil.cc.
{
     std::vector<int> hcids = getHCIDs();
     const G4Event* currEvent = G4EventManager::GetEventManager()->GetConstCurrentEvent();
     G4HCofThisEvent* hce = currEvent->GetHCofThisEvent();
     std::vector<std::string> hcnames;
     if (currEvent) {
         G4VHitsCollection* hc = 0;
         for (std::vector<int>::const_iterator iter = hcids.begin(); iter != hcids.end(); iter++) {
             hc = hce->GetHC((*iter));
             hcnames.push_back(hc->GetName());
         }
     }
     return hcnames;
 }
References HitsCollectionUtil::getHCIDs().
getSensitiveDetectors()
std::vector< SensitiveDetector * > getSensitiveDetectors () static
Get the current list of sensitive detectors.
Returns
The list of sensitive detectors.
Definition at line 18 of file HitsCollectionUtil.cc.
{
     G4SDManager* SDmgr = G4SDManager::GetSDMpointer();
     G4HCtable* HCtbl = SDmgr->GetHCtable();
     G4int num_entries = HCtbl->entries();
     std::vector<SensitiveDetector*> sds;
     for (G4int i = 0; i < num_entries; i++) {
         // get the name of this SD
         G4String sdname = HCtbl->GetSDname(i);
         // retrieve corresponding Sensitive Detector from Geant4 store and cast to LCDD type
         SensitiveDetector* sd = static_cast<SensitiveDetector*>(G4SDManager::GetSDMpointer()->FindSensitiveDetector(sdname));
         // Add, checking for dups.
         if (sd && std::find(sds.begin(), sds.end(), sd) == sds.end())
             sds.push_back(sd);
     }
     return sds;
 }
Referenced by HitsCollectionUtil::getHCIDs().
The documentation for this class was generated from the following files:
HitsCollectionUtil.hh
HitsCollectionUtil.cc