SLIC: VRML2Writer Class Reference
VRML2Writer Class Reference
A simple, standalone VRML2 writer that dumps the detector geometry in a hierarchical format.
#include <VRML2Writer.hh>
Public Member Functions
VRML2Writer (const std::string &filename)
~VRML2Writer ()
void write ()
Private Member Functions
void indent ()
void processBox (G4Box *box)
void processPhysicalVolume (G4VPhysicalVolume *volume)
void processPolyhedron (G4Polyhedron *poly)
void processSolid (G4VSolid *solid)
void processTopVolume (G4VPhysicalVolume *volume)
void processVisualization (G4VPhysicalVolume *volume)
void unindent ()
void writeLine (const std::string &line)
Private Attributes
int _indentLevel
std::ofstream _out
Detailed Description
A simple, standalone VRML2 writer that dumps the detector geometry in a hierarchical format.
Definition at line 21 of file VRML2Writer.hh.
Constructor & Destructor Documentation
VRML2Writer()
VRML2Writer (const std::string & filename)
Class constructor.
Definition at line 24 of file VRML2Writer.cc.
                                                   :
         _indentLevel(0) {
     _out.open(filename.c_str());
 }
References VRML2Writer::_out.
~VRML2Writer()
~VRML2Writer ()
Class destructor.
Definition at line 29 of file VRML2Writer.cc.
{
     if (_out.is_open())
         _out.close();
 }
References VRML2Writer::_out.
Member Function Documentation
indent()
void indent () private
Indent once in the output.
Definition at line 203 of file VRML2Writer.cc.
{
     ++_indentLevel;
 }
References VRML2Writer::_indentLevel.
Referenced by VRML2Writer::processBox(), VRML2Writer::processPhysicalVolume(), VRML2Writer::processPolyhedron(), VRML2Writer::processTopVolume(), and VRML2Writer::processVisualization().
processBox()
void processBox (G4Box * box) private
Process a box shape.
Parameters
[in] box The G4Box.
Definition at line 139 of file VRML2Writer.cc.
{
     writeLine("geometry Box {");
     indent();
     std::stringstream ss;
     ss << "size " << box->GetXHalfLength() * 2 / m << " " << box->GetYHalfLength() * 2 / m << " " << box->GetZHalfLength() * 2 / m;
     writeLine(ss.str());
     unindent();
     writeLine("}");
 }
References VRML2Writer::indent(), VRML2Writer::unindent(), and VRML2Writer::writeLine().
Referenced by VRML2Writer::processSolid().
processPhysicalVolume()
void processPhysicalVolume (G4VPhysicalVolume * volume) private
Process a physical volume.
Parameters
[in] volume The physical volume.
Definition at line 51 of file VRML2Writer.cc.
{
     writeLine("DEF " + pv->GetName() + " Transform {");
     indent();
     writeLine("children [");
     indent();
     // shape node for each physical volume
     const G4VisAttributes* vis = pv->GetLogicalVolume()->GetVisAttributes();
     bool show = true;
     if (vis && !vis->IsVisible())
         show = false;
     if (show) {
         writeLine("DEF " + pv->GetName() + " Shape {");
         indent();
         processVisualization(pv);
         processSolid(pv->GetLogicalVolume()->GetSolid());
         unindent();
         writeLine("}");
     }
     G4LogicalVolume* lv = pv->GetLogicalVolume();
     // Recurse through daughter volumes
     bool showDaughters = true;
     if (vis && vis->IsDaughtersInvisible())
         showDaughters = false;
     if (showDaughters) {
         for (int i = 0, ndau = lv->GetNoDaughters(); i < ndau; i++) {
             processPhysicalVolume(lv->GetDaughter(i));
         }
     }
     unindent();
     writeLine("]"); // children
     // translation
     const G4ThreeVector& pos = pv->GetTranslation();
     std::stringstream ss;
     ss << "translation " << pos.x() / m << " " << pos.y() / m << " " << pos.z() / m;
     writeLine(ss.str());
     // rotation
     const G4RotationMatrix* rot = pv->GetRotation();
     CLHEP::Hep3Vector axis(0, 0, 0);
     double angle = 0;
     if (rot != 0)
         rot->getAngleAxis(angle, axis);
     std::stringstream ss2;
     ss2 << "rotation " << axis.x() << " " << axis.y() << " " << axis.z() << " " << -angle;
     rot = 0;
     writeLine(ss2.str());
     unindent();
     writeLine("}"); // Transform
 }
References VRML2Writer::indent(), VRML2Writer::processSolid(), VRML2Writer::processVisualization(), VRML2Writer::unindent(), and VRML2Writer::writeLine().
Referenced by VRML2Writer::processTopVolume().
processPolyhedron()
void processPolyhedron (G4Polyhedron * poly) private
Process a polyhedron.
Parameters
[in] poly The G4Polyhedron.
Definition at line 151 of file VRML2Writer.cc.
{
     writeLine("geometry IndexedFaceSet {");
     indent();
     writeLine("coord Coordinate {");
     indent();
     writeLine("point [");
     indent();
     int i, j;
     for (i = 1, j = polyhedron->GetNoVertices(); j; j--, i++) {
         G4Point3D point = polyhedron->GetVertex(i);
         std::stringstream ss;
         ss << point.x() / m << " " << point.y() / m << " " << point.z() / m;
         writeLine(ss.str());
     }
     unindent();
     writeLine("]"); // point
     unindent();
     writeLine("}"); // coord
     writeLine("coordIndex [");
     indent();
     // facet loop
     int f;
     for (f = polyhedron->GetNoFacets(); f; f--) {
         // edge loop
         bool notLastEdge;
         int index = -1, edgeFlag = 1;
         std::stringstream ss;
         do {
             notLastEdge = polyhedron->GetNextVertexIndex(index, edgeFlag);
             ss << index - 1 << ", ";
         } while (notLastEdge);
         ss << "-1, ";
         writeLine(ss.str());
     }
     unindent();
     writeLine("]");
     writeLine("solid FALSE");
     unindent();
     writeLine("}"); // IndexFaceSet
 }
References VRML2Writer::indent(), VRML2Writer::unindent(), and VRML2Writer::writeLine().
Referenced by VRML2Writer::processSolid().
processSolid()
void processSolid (G4VSolid * solid) private
Process a solid.
Parameters
[in] solid The G4VSolid.
Definition at line 131 of file VRML2Writer.cc.
{
     if (solid->GetEntityType() == "G4Box") {
         processBox((G4Box*) solid);
     } else {
         processPolyhedron(solid->GetPolyhedron());
     }
 }
References VRML2Writer::processBox(), and VRML2Writer::processPolyhedron().
Referenced by VRML2Writer::processPhysicalVolume().
processTopVolume()
void processTopVolume (G4VPhysicalVolume * volume) private
Recursively process volumes from the top.
Parameters
[in] The top volume.
Definition at line 39 of file VRML2Writer.cc.
{
     writeLine("Group {");
     indent();
     writeLine("children [");
     indent();
     processPhysicalVolume(wv);
     unindent();
     writeLine("]");
     unindent();
     writeLine("}"); // Group
 }
References VRML2Writer::indent(), VRML2Writer::processPhysicalVolume(), VRML2Writer::unindent(), and VRML2Writer::writeLine().
Referenced by VRML2Writer::write().
processVisualization()
void processVisualization (G4VPhysicalVolume * volume) private
Process the visualization settings of the volume.
Parameters
[in] volume The physical volume.
Definition at line 107 of file VRML2Writer.cc.
{
     const G4VisAttributes* vis = pv->GetLogicalVolume()->GetVisAttributes();
     double r, g, b;
     r = g = b = 1.0;
     if (vis != 0) {
         const G4Colour& col = vis->GetColour();
         r = col.GetRed();
         g = col.GetGreen();
         b = col.GetBlue();
     }
     writeLine("appearance Appearance {");
     indent();
     writeLine("material Material {");
     indent();
     std::stringstream ss;
     ss << r << " " << g << " " << b;
     writeLine("diffuseColor " + ss.str());
     writeLine("transparency 0.0"); // use viewer like Deep View to get a wireframe or transparent view
     unindent();
     writeLine("}");
     unindent();
     writeLine("}");
 }
References VRML2Writer::indent(), VRML2Writer::unindent(), and VRML2Writer::writeLine().
Referenced by VRML2Writer::processPhysicalVolume().
unindent()
void unindent () private
Remove a level of indentation.
Definition at line 207 of file VRML2Writer.cc.
{
     --_indentLevel;
 }
References VRML2Writer::_indentLevel.
Referenced by VRML2Writer::processBox(), VRML2Writer::processPhysicalVolume(), VRML2Writer::processPolyhedron(), VRML2Writer::processTopVolume(), and VRML2Writer::processVisualization().
write()
void write ()
Write out VRML to the current file.
Definition at line 34 of file VRML2Writer.cc.
{
     writeLine("#VRML V2.0 utf8");
     processTopVolume(G4TransportationManager::GetTransportationManager()->GetNavigatorForTracking()->GetWorldVolume());
 }
References VRML2Writer::processTopVolume(), and VRML2Writer::writeLine().
Referenced by VRML2WriterMessenger::SetNewValue().
writeLine()
void writeLine (const std::string & line) private
Write a line into the output.
Parameters
[in] line The line of output.
Definition at line 196 of file VRML2Writer.cc.
{
     for (int i = 0; i < _indentLevel; i++) {
         _out << "    ";
     }
     _out << text << std::endl;
 }
References VRML2Writer::_indentLevel, VRML2Writer::_out, and LOG::endl.
Referenced by VRML2Writer::processBox(), VRML2Writer::processPhysicalVolume(), VRML2Writer::processPolyhedron(), VRML2Writer::processTopVolume(), VRML2Writer::processVisualization(), and VRML2Writer::write().
Member Data Documentation
_indentLevel
int _indentLevel private
Definition at line 97 of file VRML2Writer.hh.
Referenced by VRML2Writer::indent(), VRML2Writer::unindent(), and VRML2Writer::writeLine().
_out
std::ofstream _out private
Definition at line 96 of file VRML2Writer.hh.
Referenced by VRML2Writer::VRML2Writer(), VRML2Writer::writeLine(), and VRML2Writer::~VRML2Writer().
The documentation for this class was generated from the following files:
VRML2Writer.hh
VRML2Writer.cc