SLIC: SlicApplicationMessenger Class Reference
SlicApplicationMessenger Class Reference
G4UImessenger for the SLIC application.
#include <SlicApplicationMessenger.hh>
Public Member Functions
SlicApplicationMessenger (SlicApplication *app)
virtual ~SlicApplicationMessenger ()
virtual void SetNewValue (G4UIcommand *cmd, G4String newVals)
Private Member Functions
void defineCommands ()
Private Attributes
SlicApplication * m_app
G4UIcommand * m_interactive
G4UIcommand * m_quietMode
G4UIdirectory * m_slicDir
G4UIcommand * m_slicUsage
G4UIcommand * m_slicVersion
Detailed Description
G4UImessenger for the SLIC application.
Definition at line 17 of file SlicApplicationMessenger.hh.
Constructor & Destructor Documentation
SlicApplicationMessenger()
SlicApplicationMessenger (SlicApplication * app)
Class constructor.
Parameters
[in] app The associated SlicApplication.
Definition at line 9 of file SlicApplicationMessenger.cc.
{
     m_app = app;
     defineCommands();
 }
References SlicApplicationMessenger::defineCommands(), and SlicApplicationMessenger::m_app.
~SlicApplicationMessenger()
~SlicApplicationMessenger () virtual
Class destructor.
Definition at line 14 of file SlicApplicationMessenger.cc.
{
 }
Member Function Documentation
defineCommands()
void defineCommands () private
Define commands handled by this macro.
Definition at line 35 of file SlicApplicationMessenger.cc.
{
     // interactive mode
     m_interactive = new G4UIcommand("/control/interactive", this);
     m_interactive->SetGuidance("Set interactive mode to G4 UI session. [SLIC]");
     // SLIC dir
     m_slicDir = new G4UIdirectory("/slic/");
     m_slicDir->SetGuidance("SLIC simulator commands. [SLIC]");
     // print SLIC usage
     m_slicUsage = new G4UIcommand("/slic/usage", this);
     m_slicUsage->SetGuidance("Print SLIC usage instructions.");
     // print SLIC version
     m_slicVersion = new G4UIcommand("/slic/version", this);
     m_slicVersion->SetGuidance("Print SLIC version information.");
     // quiet mode
     m_quietMode = new G4UIcommand("/slic/quiet", this);
     m_quietMode->SetGuidance("Run in quiet mode, suppressing all stdout console output.");
 }
References SlicApplicationMessenger::m_interactive, SlicApplicationMessenger::m_quietMode, SlicApplicationMessenger::m_slicDir, SlicApplicationMessenger::m_slicUsage, and SlicApplicationMessenger::m_slicVersion.
Referenced by SlicApplicationMessenger::SlicApplicationMessenger().
SetNewValue()
void SetNewValue (G4UIcommand * cmd, G4String newVals) virtual
Execute macro command.
Parameters
[in] cmd The macro command.
[in] newVals The argument values.
Definition at line 17 of file SlicApplicationMessenger.cc.
{
     if (cmd == m_interactive) {
         m_app->setMode(SlicApplication::eInteractive);
     } else if (cmd == m_slicVersion) {
         m_app->printVersion();
     } else if (cmd == m_slicUsage) {
         m_app->printUsage();
     } else if (cmd == m_quietMode) {
         std::cout << "Quiet mode is enabled!" << std::endl;
         std::cout.setstate(std::ios_base::failbit);
         //ofstream file("/dev/null");
         //std::cout.rdbuf(file.rdbuf());
         // No more messages will be printed to cout for the remainder of the job!
     } else {
         m_app->log() << LOG::error << "Unknown command to SlicApplicationMessenger." << LOG::done;
     }
 }
References LOG::done, SlicApplication::eInteractive, LOG::endl, LOG::error, Module::log(), SlicApplicationMessenger::m_app, SlicApplicationMessenger::m_interactive, SlicApplicationMessenger::m_quietMode, SlicApplicationMessenger::m_slicUsage, SlicApplicationMessenger::m_slicVersion, SlicApplication::printUsage(), SlicApplication::printVersion(), and SlicApplication::setMode().
Member Data Documentation
m_app
SlicApplication* m_app private
Definition at line 49 of file SlicApplicationMessenger.hh.
Referenced by SlicApplicationMessenger::SetNewValue(), and SlicApplicationMessenger::SlicApplicationMessenger().
m_interactive
G4UIcommand* m_interactive private
Definition at line 53 of file SlicApplicationMessenger.hh.
Referenced by SlicApplicationMessenger::defineCommands(), and SlicApplicationMessenger::SetNewValue().
m_quietMode
G4UIcommand* m_quietMode private
Definition at line 56 of file SlicApplicationMessenger.hh.
Referenced by SlicApplicationMessenger::defineCommands(), and SlicApplicationMessenger::SetNewValue().
m_slicDir
G4UIdirectory* m_slicDir private
Definition at line 51 of file SlicApplicationMessenger.hh.
Referenced by SlicApplicationMessenger::defineCommands().
m_slicUsage
G4UIcommand* m_slicUsage private
Definition at line 54 of file SlicApplicationMessenger.hh.
Referenced by SlicApplicationMessenger::defineCommands(), and SlicApplicationMessenger::SetNewValue().
m_slicVersion
G4UIcommand* m_slicVersion private
Definition at line 55 of file SlicApplicationMessenger.hh.
Referenced by SlicApplicationMessenger::defineCommands(), and SlicApplicationMessenger::SetNewValue().
The documentation for this class was generated from the following files:
SlicApplicationMessenger.hh
SlicApplicationMessenger.cc