SLIC: TimeUtil Class Reference
TimeUtil Class Reference
Miscellaneous time-related utilities.
#include <TimeUtil.hh>
Public Types
typedef long long long64
Static Public Member Functions
static tm * get_tm_local ()
static std::string getAscTime ()
static std::string getDate ()
static long64 getTimeNS ()
Detailed Description
Miscellaneous time-related utilities.
Definition at line 16 of file TimeUtil.hh.
Member Typedef Documentation
long64
typedef long long long64
Definition at line 20 of file TimeUtil.hh.
Member Function Documentation
get_tm_local()
static tm* get_tm_local () inline static
Definition at line 44 of file TimeUtil.hh.
{
             time_t rawtime;
             struct tm* timeinfo;
             time(&rawtime);
             timeinfo = localtime(&rawtime);
             return timeinfo;
         }
References LOG::time.
Referenced by TimeUtil::getAscTime(), and TimeUtil::getDate().
getAscTime()
static std::string getAscTime () inline static
Definition at line 22 of file TimeUtil.hh.
{
             tm* timeinfo = get_tm_local();
             std::string s = asctime(timeinfo);
             s.erase(s.end() - 1, s.end());
             return s;
         }
References TimeUtil::get_tm_local().
Referenced by LogStream::operator<<().
getDate()
static std::string getDate () inline static
Definition at line 37 of file TimeUtil.hh.
{
             tm* timeinfo = get_tm_local();
             char buffer[11];
             strftime(buffer, 11, "%Y-%m-%d", timeinfo);
             return std::string(buffer);
         }
References TimeUtil::get_tm_local().
Referenced by LcioFileNamer::getFieldValue().
getTimeNS()
static long64 getTimeNS () inline static
Definition at line 31 of file TimeUtil.hh.
{
             long64 t_sec = (long64) time(NULL);
             long64 t_ns = t_sec * ((long64) 1e9);
             return t_ns;
         }
References LOG::time.
Referenced by LcioManager::setEventTimeStamp().
The documentation for this class was generated from the following file:
TimeUtil.hh