SLIC: TrackUtil Class Reference
TrackUtil Class Reference
Miscellaneous helper methods for G4Track and related classes.
#include <TrackUtil.hh>
Static Public Member Functions
static UserRegionInformation * getRegionInformation (const G4Track *track)
static UserTrackInformation * getUserTrackInformation (const G4Track *track)
static UserTrackInformation * setupUserTrackInformation (const G4Track *track, G4bool save)
Detailed Description
Miscellaneous helper methods for G4Track and related classes.
Definition at line 20 of file TrackUtil.hh.
Member Function Documentation
getRegionInformation()
static UserRegionInformation* getRegionInformation (const G4Track * track) inline static
Get the UserRegionInformation of this G4Track based on its start position.
Parameters
track The G4Track.
Returns
The UserRegionInformation for this G4Track.
Definition at line 29 of file TrackUtil.hh.
{
             G4VPhysicalVolume* volume = G4TransportationManager::GetTransportationManager()->GetNavigatorForTracking()->LocateGlobalPointAndSetup(track->GetPosition());
             G4Region* region = volume->GetLogicalVolume()->GetRegion();
             UserRegionInformation* regionInfo = dynamic_cast<UserRegionInformation*>(region->GetUserInformation());
             return regionInfo;
         }
Referenced by TrackingAction::PreUserTrackingAction(), and TrackSummary::update().
getUserTrackInformation()
static UserTrackInformation* getUserTrackInformation (const G4Track * track) inline static
Get the UserTrackInformation for the track.
Returns
The UserTrackInformation for the track, which may be NULL.
Definition at line 66 of file TrackUtil.hh.
{
             return dynamic_cast<UserTrackInformation*>(track->GetUserInformation());
         }
Referenced by TrackingAction::PostUserTrackingAction(), and TrackingAction::PreUserTrackingAction().
setupUserTrackInformation()
static UserTrackInformation* setupUserTrackInformation (const G4Track * track, G4bool save) inline static
Setup the UserTrackInformation for the G4Track, which also requires first creating a TrackSummary containing all the track information. This will register the TrackSummary in the global list for the event.
Returns
The UserTrackInformation that was created for the track.
Definition at line 42 of file TrackUtil.hh.
{
             /* Create new TrackSummary. */
             TrackSummary* trackSummary = new TrackSummary(track, save);
             /* Add it to the master list. */
             TrackManager::instance()->getTrackSummaries()->push_back(trackSummary);
             /* Associate it to its track ID. */
             (*TrackManager::instance()->getTrackSummaryMap())[track->GetTrackID()] = trackSummary;
             /* Create new UserTrackInformation. */
             UserTrackInformation* trackInfo = new UserTrackInformation(trackSummary);
             /* Set the UserTrackInformation on the track. */
             ((G4Track*) track)->SetUserInformation(trackInfo);
             return trackInfo;
         }
References Singleton< TrackManager >::instance().
Referenced by TrackingAction::PostUserTrackingAction(), TrackingAction::PreUserTrackingAction(), and SteppingAction::UserSteppingAction().
The documentation for this class was generated from the following file:
TrackUtil.hh