SLIC: TrackingAction Class Reference
TrackingAction Class Reference
Implementation of G4UserTrackingAction.
#include <TrackingAction.hh>
Public Member Functions
TrackingAction ()
~TrackingAction ()
void PostUserTrackingAction (const G4Track *)
void PreUserTrackingAction (const G4Track *)
Public Member Functions inherited from PluginManagerAccessor
PluginManager * getPluginManager ()
void setPluginManager (PluginManager *pluginManager)
Additional Inherited Members
Protected Attributes inherited from PluginManagerAccessor
PluginManager * m_pluginManager
Detailed Description
Implementation of G4UserTrackingAction.
Definition at line 18 of file TrackingAction.hh.
Constructor & Destructor Documentation
TrackingAction()
TrackingAction () inline
Class constructor.
Definition at line 25 of file TrackingAction.hh.
{
         }
~TrackingAction()
~TrackingAction () inline
Class destructor.
Definition at line 31 of file TrackingAction.hh.
{
         }
Member Function Documentation
PostUserTrackingAction()
void PostUserTrackingAction (const G4Track * track)
Post tracking action.
Parameters
[in] aTrack The G4Track.
Definition at line 71 of file TrackingAction.cc.
{
     // Get the track information and summary.
     UserTrackInformation* trackInfo = TrackUtil::getUserTrackInformation(track);
     TrackSummary* trackSummary = NULL;
     if (trackInfo != NULL)
         trackSummary = trackInfo->getTrackSummary();
     // Track has secondaries?
     if (fpTrackingManager->GimmeSecondaries()->size() > 0 && trackInfo == NULL) {
         // Tracks with secondaries always get track information but they are not saved by default.
         trackSummary = TrackUtil::setupUserTrackInformation(track, false)->getTrackSummary();
     }
     // Track summary exists?
     if (trackSummary != NULL) {
         // Update the track summary.
         trackSummary->update(track);
     }
     m_pluginManager->postTracking(track);
 }
References UserTrackInformation::getTrackSummary(), TrackUtil::getUserTrackInformation(), PluginManagerAccessor::m_pluginManager, PluginManager::postTracking(), TrackUtil::setupUserTrackInformation(), and TrackSummary::update().
PreUserTrackingAction()
void PreUserTrackingAction (const G4Track * track)
Pre tracking action.
Parameters
[in] aTrack The G4Track.
Definition at line 15 of file TrackingAction.cc.
{
     G4int trackID = track->GetTrackID();
     G4int parentID = track->GetParentID();
     G4bool isTruePrimary = (track->GetParentID() == 0);
     UserRegionInformation* regionInfo = TrackUtil::getRegionInformation(track);
     G4bool insideTrackerRegion = regionInfo->getStoreSecondaries();
     UserTrackInformation* trackInfo = TrackUtil::getUserTrackInformation(track);
     bool hasTrackInfo = (trackInfo != NULL);
     bool aboveEnergyThreshold = (track->GetKineticEnergy() > regionInfo->getThreshold());
     // This happens when backscattering track are un-suspended.
     if (hasTrackInfo) {
         // Track is backscattering?
         if (trackInfo->getTrackSummary()->getBackScattering()) {
             // Update current track ID for calorimeter SDs and return.
             CurrentTrackState::setCurrentTrackID(trackID);
             return;
         }
         return;
     }
     // Primary OR in tracker region and above energy threshold?
     if (isTruePrimary || (insideTrackerRegion && aboveEnergyThreshold)) {
         // Update track ID for calorimeter SDs.
         CurrentTrackState::setCurrentTrackID(trackID);
         // Turn on trajectory storage.
         fpTrackingManager->SetStoreTrajectory(true);
         // Has track information?
         if (!hasTrackInfo) {
             // Create the track information and save it.
             TrackUtil::setupUserTrackInformation(track, true);
         }
     } else {
         // Inside tracker region and below energy threshold?
         if (insideTrackerRegion && !aboveEnergyThreshold) {
             // Has track information?
             if (!hasTrackInfo) {
                 // Create track information but do not save it.
                 TrackUtil::setupUserTrackInformation(track, false);
             }
         } else {
             // Track is outside tracking region so turn off trajectory storage.
             // These are generally tracks from calorimeter showers.
             fpTrackingManager->SetStoreTrajectory(false);
         }
     }
     m_pluginManager->preTracking(track);
 }
References TrackSummary::getBackScattering(), TrackUtil::getRegionInformation(), UserTrackInformation::getTrackSummary(), TrackUtil::getUserTrackInformation(), PluginManagerAccessor::m_pluginManager, PluginManager::preTracking(), and TrackUtil::setupUserTrackInformation().
The documentation for this class was generated from the following files:
TrackingAction.hh
TrackingAction.cc