SLIC: SteppingAction Class Reference
SteppingAction Class Reference
Implementation of G4UserSteppingAction.
#include <SteppingAction.hh>
Public Member Functions
SteppingAction ()
virtual ~SteppingAction ()
bool isBackScattering (const G4Step *step)
void UserSteppingAction (const G4Step *step)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from PluginManagerAccessor
PluginManager * getPluginManager ()
void setPluginManager (PluginManager *pluginManager)
Private Member Functions
void checkKillTrack (const G4Step *step)
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Protected Attributes inherited from PluginManagerAccessor
PluginManager * m_pluginManager
Detailed Description
Implementation of G4UserSteppingAction.
Definition at line 22 of file SteppingAction.hh.
Constructor & Destructor Documentation
SteppingAction()
SteppingAction ()
Class constructor.
Definition at line 17 of file SteppingAction.cc.
                                :
         Module("SteppingAction", false, true) {
 }
~SteppingAction()
~SteppingAction () virtual
Class destructor.
Definition at line 21 of file SteppingAction.cc.
{
 }
Member Function Documentation
checkKillTrack()
void checkKillTrack (const G4Step * step) private
Kill a G4Track if it is inside a track-killing region.
Parameters
[in] step The G4Step.
Definition at line 55 of file SteppingAction.cc.
{
     /* Check if the region of the pre-point has tracking killing enabled. */
     UserRegionInformation* regionInfo = UserRegionInformation::getRegionInformation(aStep->GetPreStepPoint());
     if (regionInfo->getKillTracks()) {
         /* Kill the track if region track kill flag is set to true. */
         log() << LOG::always << "Killing track: " << aStep->GetTrack()->GetTrackID() << LOG::done;
         aStep->GetTrack()->SetTrackStatus(fStopAndKill);
     }
 }
References LOG::always, LOG::done, and Module::log().
Referenced by SteppingAction::UserSteppingAction().
isBackScattering()
bool isBackScattering (const G4Step * step)
Return true if this track appears to be backscattering from a non-tracking region into the tracking region.
Returns
True if track is backscattering; false if not.
Definition at line 65 of file SteppingAction.cc.
{
     /* Get pre-point info. */
     const G4StepPoint* prePoint = step->GetPreStepPoint();
     const G4StepPoint* postPoint = step->GetPostStepPoint();
     const UserRegionInformation* prePointRegionInfo = (UserRegionInformation*) prePoint->GetTouchableHandle()->GetVolume()->GetLogicalVolume()->GetRegion()->GetUserInformation();
     G4bool prePointInsideTrackerRegion = prePointRegionInfo->getStoreSecondaries();
     /* Get post-point info. */
     G4bool postPointInsideTrackerRegion = false;
     if (postPoint->GetTouchableHandle()->GetVolume() != NULL) {
         const UserRegionInformation* postPointRegionInfo = (UserRegionInformation*) postPoint->GetTouchableHandle()->GetVolume()->GetLogicalVolume()->GetRegion()->GetUserInformation();
         postPointInsideTrackerRegion = postPointRegionInfo->getStoreSecondaries();
     }
     /* Track is backscattering if it steps from a non-tracking region back into a tracking region. */
     return ((!prePointInsideTrackerRegion) && postPointInsideTrackerRegion);
 }
Referenced by SteppingAction::UserSteppingAction().
UserSteppingAction()
void UserSteppingAction (const G4Step * step)
Implementation of user stepping action.
Parameters
[in] step The G4Step.
Definition at line 24 of file SteppingAction.cc.
{
     /* Check for back scattering. */
     if (isBackScattering(step) && step->GetStepLength() != 0.) {
         // Get track information.
         UserTrackInformation* trackInfo = (UserTrackInformation*) fpSteppingManager->GetTrack()->GetUserInformation();
         // Need to start making track information if doesn't exist because these tracks or daughters could leave tracker hits.
         if (trackInfo == NULL)
             // Add new track information but don't save.  The tracker hit processor can turn saving on.
             trackInfo = TrackUtil::setupUserTrackInformation(fpSteppingManager->GetTrack(), false);
         TrackSummary* trackSummary = trackInfo->getTrackSummary();
         //G4cout << "setting backscattering flag" << G4endl;
         trackSummary->update(fpSteppingManager->GetTrack());
         trackSummary->setBackScattering();
         // Suspend backscattering tracks to postpone them to the end of shower development.
         fpSteppingManager->GetTrack()->SetTrackStatus(fSuspend);
         //G4cout << "suspended backscattering track " << fpSteppingManager->GetTrack()->GetTrackID() << G4endl;
     }
     /* Check if the track should be killed. */
     checkKillTrack(step);
     m_pluginManager->stepping(step);
 }
References SteppingAction::checkKillTrack(), UserTrackInformation::getTrackSummary(), SteppingAction::isBackScattering(), PluginManagerAccessor::m_pluginManager, TrackSummary::setBackScattering(), TrackUtil::setupUserTrackInformation(), PluginManager::stepping(), and TrackSummary::update().
The documentation for this class was generated from the following files:
SteppingAction.hh
SteppingAction.cc