SLIC: PluginManager Class Reference
PluginManager Class Reference
Manages user sim plugins.
#include <PluginManager.hh>
Public Types
typedef std::vector< UserActionPlugin * > PluginVec
Public Member Functions
PluginManager ()
virtual ~PluginManager ()
void beginEvent (const G4Event *anEvent)
void beginRun (const G4Run *aRun)
void create (const std::string &pluginName, const std::string &libName)
void destroy (const std::string &pluginName)
void endEvent (const G4Event *anEvent)
void endRun (const G4Run *aRun)
UserActionPlugin * findPlugin (const std::string &pluginName)
void generatePrimary (G4Event *anEvent)
void postTracking (const G4Track *aTrack)
void preTracking (const G4Track *aTrack)
std::ostream & print (std::ostream &os)
G4ClassificationOfNewTrack stackingClassifyNewTrack (const G4Track *aTrack)
Return a track classification from the user plugins that have stacking actions.
void stackingNewStage ()
void stackingPrepareNewEvent ()
void stepping (const G4Step *aStep)
Private Member Functions
void deregisterPlugin (UserActionPlugin *plugin)
void destroy (UserActionPlugin *plugin)
void destroyPlugins ()
void registerPlugin (UserActionPlugin *plugin)
Private Attributes
PluginLoader pluginLoader_
PluginVec plugins_
Detailed Description
Manages user sim plugins.
Note
This class loads UserSimPlugin objects from dynamic libraries using a PluginLoader. It is also responsible for activating the user action hooks for all registered plugins. Only one instance of a given plugin can be loaded at a time.
See also
UserActionPlugin
PluginLoader
Definition at line 35 of file PluginManager.hh.
Member Typedef Documentation
PluginVec
typedef std::vector<UserActionPlugin*> PluginVec
Vector of plugins.
Definition at line 42 of file PluginManager.hh.
Constructor & Destructor Documentation
PluginManager()
PluginManager () inline
Class constructor.
Definition at line 47 of file PluginManager.hh.
{
         }
~PluginManager()
~PluginManager () virtual
Class destructor. This will destroy all the currently registered plugins.
Definition at line 5 of file PluginManager.cc.
{
     destroyPlugins();
 }
References PluginManager::destroyPlugins().
Member Function Documentation
beginEvent()
void beginEvent (const G4Event * anEvent)
Activate the begin event hook of registered plugins.
Parameters
anEvent The Geant4 event.
Definition at line 49 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasEventAction()) {
             (*it)->beginEvent(event);
         }
     }
 }
References PluginManager::plugins_.
Referenced by EventAction::BeginOfEventAction().
beginRun()
void beginRun (const G4Run * aRun)
Activate the begin run hook for registered plugins.
Parameters
aRun The Geant4 run that is beginning.
Definition at line 9 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasRunAction()) {
             (*it)->beginRun(run);
         }
     }
 }
References PluginManager::plugins_.
Referenced by RunAction::BeginOfRunAction().
create()
void create (const std::string & pluginName, const std::string & libName)
Create a new plugin by name from the given library.
Parameters
pluginName The name of the plugin.
libName The name of the shared library.
Definition at line 124 of file PluginManager.cc.
{
     if (findPlugin(pluginName) == nullptr) {
         UserActionPlugin* plugin = pluginLoader_.create(pluginName, libName);
         registerPlugin(plugin);
     } else {
         std::cerr << "[ PluginManager ] - Plugin " << pluginName << " already exists." << std::endl;
         throw new std::runtime_error("Plugin already loaded.");
     }
 }
References PluginLoader::create(), LOG::endl, PluginManager::findPlugin(), PluginManager::pluginLoader_, and PluginManager::registerPlugin().
Referenced by PluginMessenger::SetNewValue().
deregisterPlugin()
void deregisterPlugin (UserActionPlugin * plugin) private
De-register a plugin.
Parameters
plugin Pointer to plugin that should be de-registered.
Definition at line 159 of file PluginManager.cc.
{
     std::vector<UserActionPlugin*>::iterator pos = std::find(plugins_.begin(), plugins_.end(), plugin);
     if (pos != plugins_.end()) {
         plugins_.erase(pos);
     }
 }
References PluginManager::plugins_.
Referenced by PluginManager::destroy().
destroy() [1/2]
void destroy (const std::string & pluginName)
Destroy a plugin by name.
Parameters
pluginName The name of the plugin.
Definition at line 134 of file PluginManager.cc.
{
     UserActionPlugin* plugin = findPlugin(pluginName);
     if (plugin != nullptr) {
         destroy(plugin);
     }
 }
References PluginManager::findPlugin().
Referenced by PluginManager::destroyPlugins(), and PluginMessenger::SetNewValue().
destroy() [2/2]
void destroy (UserActionPlugin * plugin) private
Destroy a plugin.
Parameters
plugin Pointer to plugin that should be destroyed.
Definition at line 141 of file PluginManager.cc.
{
     if (plugin != nullptr) {
         deregisterPlugin(plugin);
         pluginLoader_.destroy(plugin);
     }
 }
References PluginManager::deregisterPlugin(), PluginLoader::destroy(), and PluginManager::pluginLoader_.
destroyPlugins()
void destroyPlugins () private
Destroy all registered plugins.
Definition at line 166 of file PluginManager.cc.
{
     for (unsigned iPlugin = 0; iPlugin < plugins_.size(); iPlugin++) {
         destroy(plugins_[iPlugin]);
     }
     plugins_.clear();
 }
References PluginManager::destroy(), and PluginManager::plugins_.
Referenced by PluginManager::~PluginManager().
endEvent()
void endEvent (const G4Event * anEvent)
Activate the end event hook of registered plugins.
Parameters
anEvent The Geant4 event.
Definition at line 57 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasEventAction()) {
             (*it)->endEvent(event);
         }
     }
 }
References PluginManager::plugins_.
Referenced by EventAction::EndOfEventAction().
endRun()
void endRun (const G4Run * aRun)
Activate the end run hook of registered plugins.
Parameters
aRun The Geant4 run that is ending.
Definition at line 17 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasRunAction()) {
             (*it)->endRun(run);
         }
     }
 }
References PluginManager::plugins_.
Referenced by RunAction::EndOfRunAction().
findPlugin()
UserActionPlugin * findPlugin (const std::string & pluginName)
Find a plugin by name.
Parameters
pluginName The name of the plugin.
Returns
The plugin with the name or nullptr if does not exist.
Definition at line 113 of file PluginManager.cc.
{
     UserActionPlugin* foundPlugin = nullptr;
     for (PluginVec::iterator iPlugin = plugins_.begin(); iPlugin != plugins_.end(); iPlugin++) {
         if ((*iPlugin)->getName() == pluginName) {
             foundPlugin = *iPlugin;
             break;
         }
     }
     return foundPlugin;
 }
References PluginManager::plugins_.
Referenced by PluginManager::create(), and PluginManager::destroy().
generatePrimary()
void generatePrimary (G4Event * anEvent)
Activate the generate primary hook of registered plugins.
Parameters
anEvent The Geant4 event.
Definition at line 65 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasPrimaryGeneratorAction()) {
             (*it)->generatePrimary(event);
         }
     }
 }
References PluginManager::plugins_.
Referenced by PrimaryGeneratorAction::GeneratePrimaries().
postTracking()
void postTracking (const G4Track * aTrack)
Activate the post-tracking hook of registered plugins.
Parameters
aTrack The Geant4 track.
Definition at line 41 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasTrackingAction()) {
             (*it)->postTracking(track);
         }
     }
 }
References PluginManager::plugins_.
Referenced by TrackingAction::PostUserTrackingAction().
preTracking()
void preTracking (const G4Track * aTrack)
Activate the pre-tracking hook of registered plugins.
Parameters
aTrack The Geant4 track.
Definition at line 33 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasTrackingAction()) {
             (*it)->preTracking(track);
         }
     }
 }
References PluginManager::plugins_.
Referenced by TrackingAction::PreUserTrackingAction().
print()
std::ostream & print (std::ostream & os)
Print out information about registered plugins.
Parameters
os The output stream.
Returns
The same output stream.
Definition at line 148 of file PluginManager.cc.
{
     for (PluginVec::iterator iPlugin = plugins_.begin(); iPlugin != plugins_.end(); iPlugin++) {
         os << (*iPlugin)->getName() << std::endl;
     }
     return os;
 }
References LOG::endl, and PluginManager::plugins_.
Referenced by PluginMessenger::SetNewValue().
registerPlugin()
void registerPlugin (UserActionPlugin * plugin) private
Register a plugin.
Parameters
plugin Pointer to plugin that should be registered.
Definition at line 155 of file PluginManager.cc.
{
     plugins_.push_back(plugin);
 }
References PluginManager::plugins_.
Referenced by PluginManager::create().
stackingClassifyNewTrack()
G4ClassificationOfNewTrack stackingClassifyNewTrack (const G4Track * aTrack)
Return a track classification from the user plugins that have stacking actions.
Activate the track classification hook of registered plugins.
Parameters
aTrack The Geant4 track.
Note
The current classification will only be updated if a plugin actually provides a different classification than the current one.
Definition at line 73 of file PluginManager.cc.
{
     // Default value of a track is fUrgent.
     G4ClassificationOfNewTrack currentTrackClass = G4ClassificationOfNewTrack::fUrgent;
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasStackingAction()) {
             // Get proposed new track classification from this plugin.
             G4ClassificationOfNewTrack newTrackClass = (*it)->stackingClassifyNewTrack(track, currentTrackClass);
             // Only set the current classification if the plugin changed it.
             if (newTrackClass != currentTrackClass) {
                 // Set the track classification from this plugin.
                 currentTrackClass = newTrackClass;
             }
         }
     }
     // Return the current track classification.
     return currentTrackClass;
 }
References PluginManager::plugins_.
Referenced by StackingAction::ClassifyNewTrack().
stackingNewStage()
void stackingNewStage ()
Activate the stacking new stage hook of registered plugins.
Definition at line 97 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasEventAction()) {
             (*it)->stackingNewStage();
         }
     }
 }
References PluginManager::plugins_.
Referenced by StackingAction::NewStage().
stackingPrepareNewEvent()
void stackingPrepareNewEvent ()
Activate the prepare new event stacking hook of registered plugins.
Definition at line 105 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasStackingAction()) {
             (*it)->stackingPrepareNewEvent();
         }
     }
 }
References PluginManager::plugins_.
Referenced by StackingAction::PrepareNewEvent().
stepping()
void stepping (const G4Step * aStep)
Activate the stepping hook of registered plugins.
Parameters
aStep The Geant4 step.
Definition at line 25 of file PluginManager.cc.
{
     for (PluginVec::iterator it = plugins_.begin(); it != plugins_.end(); it++) {
         if ((*it)->hasSteppingAction()) {
             (*it)->stepping(step);
         }
     }
 }
References PluginManager::plugins_.
Referenced by SteppingAction::UserSteppingAction().
Member Data Documentation
pluginLoader_
PluginLoader pluginLoader_ private
The plugin loader for loading plugins from shared libraries.
Definition at line 184 of file PluginManager.hh.
Referenced by PluginManager::create(), and PluginManager::destroy().
plugins_
PluginVec plugins_ private
The list of registered plugins.
Definition at line 189 of file PluginManager.hh.
Referenced by PluginManager::beginEvent(), PluginManager::beginRun(), PluginManager::deregisterPlugin(), PluginManager::destroyPlugins(), PluginManager::endEvent(), PluginManager::endRun(), PluginManager::findPlugin(), PluginManager::generatePrimary(), PluginManager::postTracking(), PluginManager::preTracking(), PluginManager::print(), PluginManager::registerPlugin(), PluginManager::stackingClassifyNewTrack(), PluginManager::stackingNewStage(), PluginManager::stackingPrepareNewEvent(), and PluginManager::stepping().
The documentation for this class was generated from the following files:
PluginManager.hh
PluginManager.cc