SLIC: PrimaryGeneratorAction Class Reference
PrimaryGeneratorAction Class Reference
Implementation of G4VUserPrimaryGeneratorAction.
#include <PrimaryGeneratorAction.hh>
Public Member Functions
PrimaryGeneratorAction ()
virtual ~PrimaryGeneratorAction ()
virtual void GeneratePrimaries (G4Event *anEvent)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from PluginManagerAccessor
PluginManager * getPluginManager ()
void setPluginManager (PluginManager *pluginManager)
Private Member Functions
void printBeginEventMessage (G4Event *anEvent)
Private Attributes
EventSourceManager * _manager
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0 , eNotInitialized = 1 , eBadState = 2 , eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Protected Attributes inherited from PluginManagerAccessor
PluginManager * m_pluginManager
Detailed Description
Implementation of G4VUserPrimaryGeneratorAction.
Definition at line 21 of file PrimaryGeneratorAction.hh.
Constructor & Destructor Documentation
PrimaryGeneratorAction()
PrimaryGeneratorAction ()
Class constructor.
Definition at line 19 of file PrimaryGeneratorAction.cc.
References PrimaryGeneratorAction::_manager, and Singleton< EventSourceManager >::instance().
~PrimaryGeneratorAction()
~PrimaryGeneratorAction () virtual
Class destructor.
Definition at line 24 of file PrimaryGeneratorAction.cc.
Member Function Documentation
GeneratePrimaries()
void GeneratePrimaries (G4Event * anEvent) virtual
Generate G4PrimaryParticle objects into the G4Event.
Parameters
[in] anEvent The target G4Event.
Definition at line 27 of file PrimaryGeneratorAction.cc.
References PrimaryGeneratorAction::_manager, EventSourceManager::beginEvent(), LOG::done, EventSourceManager::generateNextEvent(), PluginManager::generatePrimary(), RunManager::instance(), Singleton< TrackManager >::instance(), Singleton< MCParticleManager >::instance(), Singleton< SlicApplication >::instance(), EventSourceManager::isEOF(), Module::log(), PluginManagerAccessor::m_pluginManager, LOG::name, LOG::sep, and LOG::warning.
printBeginEventMessage()
void printBeginEventMessage (G4Event * anEvent) private
Begin the beginning of event message.
Member Data Documentation
_manager
EventSourceManager* _manager private
Definition at line 52 of file PrimaryGeneratorAction.hh.
Referenced by PrimaryGeneratorAction::PrimaryGeneratorAction(), and PrimaryGeneratorAction::GeneratePrimaries().
The documentation for this class was generated from the following files:
PrimaryGeneratorAction.hh
PrimaryGeneratorAction.cc