SLIC: EventAction Class Reference
EventAction Class Reference
Implementation of G4UserEventAction.
#include <EventAction.hh>
Public Member Functions
EventAction ()
virtual ~EventAction ()
void BeginOfEventAction (const G4Event *anEvent)
void enableEventTimer (bool et=true)
virtual void EndOfEventAction (const G4Event *anEvent)
void startEventTimer ()
void stopEventTimer ()
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from PluginManagerAccessor
PluginManager * getPluginManager ()
void setPluginManager (PluginManager *pluginManager)
Static Public Member Functions
static EventAction * getEventAction ()
Private Attributes
bool m_enableEventTimer
G4Timer m_eventTimer
G4UImessenger * m_messenger
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Protected Attributes inherited from PluginManagerAccessor
PluginManager * m_pluginManager
Detailed Description
Implementation of G4UserEventAction.
Note
Calls actions of TrajectoryManager and LcioManager.
Definition at line 25 of file EventAction.hh.
Constructor & Destructor Documentation
EventAction()
EventAction ()
Class constructor.
Definition at line 22 of file EventAction.cc.
                          :
         G4UserEventAction(), Module("EventAction", false), m_enableEventTimer(false) {
     m_messenger = new EventMessenger();
 }
References EventAction::m_messenger.
~EventAction()
~EventAction () virtual
Class destructor.
Definition at line 27 of file EventAction.cc.
{
 }
Member Function Documentation
BeginOfEventAction()
void BeginOfEventAction (const G4Event * anEvent)
Callback for the beginning of a Geant4 event.
Parameters
[in] anEvent The Geant4 event.
Definition at line 30 of file EventAction.cc.
{
     // Reset current track state.
     CurrentTrackState::setCurrentTrackID(-1);
     m_pluginManager->beginEvent(anEvent);
 }
References PluginManager::beginEvent(), and PluginManagerAccessor::m_pluginManager.
enableEventTimer()
void enableEventTimer (bool et = true)
Enable or disable the event processing timer.
Parameters
[in] et The event timer setting; true to turn on.
Definition at line 93 of file EventAction.cc.
 { m_enableEventTimer = et; }
References EventAction::m_enableEventTimer.
Referenced by EventMessenger::SetNewValue().
EndOfEventAction()
void EndOfEventAction (const G4Event * anEvent) virtual
Callback for the end of a Geant4 event.
Parameters
[in] anEvent The Geant4 event.
Definition at line 37 of file EventAction.cc.
{
     // If either the run or event have been aborted, don't write an LCEvent.
     if (!RunManager::instance()->isRunAborted() &&
             !G4RunManager::GetRunManager()->GetCurrentEvent()->IsAborted()) {
         /* Create an empty LCEvent. */
         LcioManager::instance()->createLCEvent();
         /* Save track information to MCParticle collection in LCIO output event. */
         TrackManager::instance()->saveTrackSummaries(anEvent, LcioManager::instance()->getCurrentLCEvent());
         /* End of event processing for the current event generator. */
         EventSourceManager::instance()->endEvent(anEvent);
         /* Execute LcioManager's end of event action. */
         LcioManager::instance()->endEvent(anEvent);
     }
     m_pluginManager->endEvent(anEvent);
     /* Stop the event timer. */
     stopEventTimer();
     /* Print the end event message. */
     //printEndEventMessage(anEvent);
 }
References PluginManager::endEvent(), Singleton< EventSourceManager >::instance(), Singleton< TrackManager >::instance(), Singleton< LcioManager >::instance(), RunManager::instance(), PluginManagerAccessor::m_pluginManager, and EventAction::stopEventTimer().
getEventAction()
EventAction * getEventAction () static
Get the singleton instance of this class.
Returns
The EventAction object.
Definition at line 70 of file EventAction.cc.
{
     const EventAction* ea = static_cast<const EventAction*>(G4RunManager::GetRunManager()->GetUserEventAction());
     return const_cast<EventAction*>(ea);
 }
Referenced by EventSourceManager::beginEvent(), and EventMessenger::SetNewValue().
startEventTimer()
void startEventTimer ()
Start the event timer.
Definition at line 84 of file EventAction.cc.
{
     if (m_enableEventTimer) {
         m_eventTimer.Start();
 #ifdef SLIC_LOG
         log() << LOG::verbose << "Started Event Timer." << LOG::done;
 #endif
     }
 }
References LOG::done, Module::log(), EventAction::m_enableEventTimer, EventAction::m_eventTimer, and LOG::verbose.
Referenced by EventSourceManager::beginEvent().
stopEventTimer()
void stopEventTimer ()
Stop the event timer.
Definition at line 75 of file EventAction.cc.
{
     if (m_enableEventTimer) {
         m_eventTimer.Stop();
 #ifdef SLIC_LOG
         log() << LOG::okay << "Event Timer: " << m_eventTimer << LOG::done;
 #endif
     }
 }
References LOG::done, Module::log(), EventAction::m_enableEventTimer, EventAction::m_eventTimer, and LOG::okay.
Referenced by EventAction::EndOfEventAction().
Member Data Documentation
m_enableEventTimer
bool m_enableEventTimer private
Print the end of event message.
Parameters
[in] anEvent The Geant4 event.
Definition at line 85 of file EventAction.hh.
Referenced by EventAction::enableEventTimer(), EventAction::startEventTimer(), and EventAction::stopEventTimer().
m_eventTimer
G4Timer m_eventTimer mutable private
Definition at line 86 of file EventAction.hh.
Referenced by EventAction::startEventTimer(), and EventAction::stopEventTimer().
m_messenger
G4UImessenger* m_messenger private
Definition at line 88 of file EventAction.hh.
Referenced by EventAction::EventAction().
The documentation for this class was generated from the following files:
EventAction.hh
EventAction.cc