SLIC: FileUtil Class Reference
FileUtil Class Reference
Utilities for file manipulation.
#include <FileUtil.hh>
Static Public Member Functions
static std::string basename (std::string filename)
static std::string extension (std::string filename)
static bool fileExists (const char *filename)
static bool fileExists (const std::string &filename)
static std::string removeExtension (std::string filename)
static int removeFile (const char *filename)
static int removeFile (const std::string &filename)
Detailed Description
Utilities for file manipulation.
Definition at line 13 of file FileUtil.hh.
Member Function Documentation
basename()
std::string basename (std::string filename) static
Get the base name of a file path, which has the directory stripped from it.
Parameters
[in] filename Full path to a file.
Returns
The base name of the file.
Definition at line 40 of file FileUtil.cc.
{
     static std::string delim = "/";
     std::string filename = fn;
     // find Unix/Cygwin delim
     int basename_pos = filename.rfind(delim);
     // may be dealing with a Windows-style path
 #if defined(__WIN32__) || defined(__CYGWIN__) || defined(__CYGWIN32__)
     if ( basename_pos == -1 ) {
         basename_pos = filename.rfind("\\");
     }
 #endif
     // found a dir delimiter so erase up to it
     if (basename_pos != -1) {
         filename.erase(filename.begin(), filename.begin() + basename_pos + 1);
     }
     return filename;
 }
Referenced by LcioFileNamer::makeFileBasedName().
extension()
std::string extension (std::string filename) static
Get the extension of a file.
Parameters
[in] filename Full path to a file.
Returns
The extension of the file.
Definition at line 63 of file FileUtil.cc.
{
     std::string::size_type idx = fn.find_last_of(".");
     std::string ext;
     if (idx != std::string::npos) {
         ext = fn.substr(idx + 1, fn.size() - idx);
     } else {
         ext = "";
     }
     return ext;
 }
Referenced by EventSourceManager::setFilename().
fileExists() [1/2]
bool fileExists (const char * filename) static
Check if a file exists.
Parameters
[in] fileName Full path to a file.
Returns
True if file exists; false if it does not.
Definition at line 22 of file FileUtil.cc.
{
     bool exists = true;
     ifstream fin;
     fin.open(filename, ios::in);
     // either doesn't exist or can't read
     if (fin.fail()) {
         exists = false;
     }
     fin.close();
     return exists;
 }
Referenced by FileUtil::fileExists(), LcioManager::openLcioFile(), and EventSourceWithInputFile::setFilename().
fileExists() [2/2]
bool fileExists (const std::string & filename) static
Check if a file exists.
Parameters
[in] fileName Full path string to a file.
Returns
True if file exists; false if it does not.
Definition at line 36 of file FileUtil.cc.
{
     return FileUtil::fileExists(filename.c_str());
 }
References FileUtil::fileExists().
removeExtension()
std::string removeExtension (std::string filename) static
Strip the extension from a file name.
Parameters
[in] filename Full path to a file.
Returns
The file name with extension stripped off.
Definition at line 76 of file FileUtil.cc.
{
     std::string::size_type idx = fn.find_last_of(".");
     std::string fname;
     if (idx != std::string::npos) {
         fname = fn.substr(0, idx);
     } else {
         fname = fn;
     }
     return fname;
 }
Referenced by LcioFileNamer::makeFileBasedName().
removeFile() [1/2]
int removeFile (const char * filename) static
Remove a file.
Parameters
[in] filename Full path to a file.
Returns
Command status with non-zero indicating an error.
Definition at line 13 of file FileUtil.cc.
{
     int ret = remove(filename);
     return ret;
 }
Referenced by LcioManager::openLcioFile(), and FileUtil::removeFile().
removeFile() [2/2]
int removeFile (const std::string & filename) static
Remove a file.
Parameters
[in] filename Full path to a file.
Returns
Command status with non-zero indicating an error.
Definition at line 18 of file FileUtil.cc.
{
     return FileUtil::removeFile(filename.c_str());
 }
References FileUtil::removeFile().
The documentation for this class was generated from the following files:
FileUtil.hh
FileUtil.cc