SLIC: HepPDTManager Class Reference
HepPDTManager Class Reference
A class for managing the HepPDT particle table.
#include <HepPDTManager.hh>
Public Member Functions
HepPDTManager ()
virtual ~HepPDTManager ()
HepPDT::ParticleDataTable * getParticleDataTable ()
void setParticleDataFile (std::string pdfile)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from Singleton< HepPDTManager >
Singleton ()
~Singleton ()
void release ()
Private Member Functions
void loadParticleData ()
void printParticleData ()
Private Attributes
HepPDT::ParticleDataTable * m_datacol
bool m_fileSet
std::string m_pdfile
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Static Public Member Functions inherited from Singleton< HepPDTManager >
static HepPDTManager * instance ()
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
A class for managing the HepPDT particle table.
Definition at line 24 of file HepPDTManager.hh.
Constructor & Destructor Documentation
HepPDTManager()
HepPDTManager ()
Class constructor.
Definition at line 5 of file HepPDTManager.cc.
References LOG::debug, Module::log(), and LogStream::setOutputLevel().
~HepPDTManager()
~HepPDTManager () virtual
Class destructor.
Definition at line 10 of file HepPDTManager.cc.
References HepPDTManager::m_datacol.
Member Function Documentation
getParticleDataTable()
HepPDT::ParticleDataTable * getParticleDataTable ()
Get the particle data table, which is created on demand.
Returns
The particle data table.
Definition at line 14 of file HepPDTManager.cc.
References HepPDTManager::loadParticleData(), and HepPDTManager::m_datacol.
loadParticleData()
void loadParticleData () private
Load all data into the particle data table object.
Definition at line 26 of file HepPDTManager.cc.
References LOG::done, LOG::error, Module::log(), HepPDTManager::m_datacol, HepPDTManager::m_fileSet, and HepPDTManager::m_pdfile.
Referenced by HepPDTManager::getParticleDataTable().
printParticleData()
void printParticleData () private
Print out the particle table data.
Definition at line 62 of file HepPDTManager.cc.
References LOG::always, LOG::done, LOG::endl, Module::log(), and HepPDTManager::m_datacol.
setParticleDataFile()
void setParticleDataFile (std::string pdfile)
Set the path to the particle data table.
Parameters
[in] pdfile The path to the particle data table.
Definition at line 21 of file HepPDTManager.cc.
References HepPDTManager::m_fileSet, and HepPDTManager::m_pdfile.
Member Data Documentation
m_datacol
HepPDT::ParticleDataTable* m_datacol private
Definition at line 64 of file HepPDTManager.hh.
Referenced by HepPDTManager::getParticleDataTable(), HepPDTManager::loadParticleData(), HepPDTManager::printParticleData(), and HepPDTManager::~HepPDTManager().
m_fileSet
bool m_fileSet private
Definition at line 66 of file HepPDTManager.hh.
Referenced by HepPDTManager::loadParticleData(), and HepPDTManager::setParticleDataFile().
m_pdfile
std::string m_pdfile private
Definition at line 65 of file HepPDTManager.hh.
Referenced by HepPDTManager::loadParticleData(), and HepPDTManager::setParticleDataFile().
The documentation for this class was generated from the following files:
HepPDTManager.hh
HepPDTManager.cc