SLIC: GeneratorMessenger Class Reference
GeneratorMessenger Class Reference
Geant4 commands related to event generation.
#include <GeneratorMessenger.hh>
Public Member Functions
GeneratorMessenger ()
virtual ~GeneratorMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
Private Member Functions
void defineCommands ()
Private Attributes
G4UIcommand * m_enablePrintEventCmd
G4UIcommand * m_filenameCmd
G4UIdirectory * m_generatorDir
G4UIcommand * m_printNumEventsGeneratedCmd
G4UIcommand * m_randomSeedCmd
G4UIcommand * m_resetCmd
G4UIcommand * m_selectCmd
G4UIcmdWithADoubleAndUnit * m_setLorentzTransformationAngleCmd
G4UIcmdWithADouble * m_setZSmearingParameterCmd
G4UIcmdWithAnInteger * m_skipEventsCmd
Detailed Description
Geant4 commands related to event generation.
Definition at line 19 of file GeneratorMessenger.hh.
Constructor & Destructor Documentation
GeneratorMessenger()
GeneratorMessenger ()
Class constructor.
Definition at line 28 of file GeneratorMessenger.cc.
{
     defineCommands();
 }
~GeneratorMessenger()
~GeneratorMessenger () virtual
Class destructor.
Definition at line 32 of file GeneratorMessenger.cc.
{
 }
Member Function Documentation
defineCommands()
void defineCommands () private
Define the commands of the messenger.
Definition at line 97 of file GeneratorMessenger.cc.
{
     G4UIparameter *p;
     // generator dir
     m_generatorDir = new G4UIdirectory("/generator/");
     m_generatorDir->SetGuidance("Event generation commands.");
     // select
     m_selectCmd = new G4UIcommand("/generator/select", this);
     m_selectCmd->SetGuidance("Set Generator to use: lcio, stdhep, gps or gun.");
     p = new G4UIparameter("generator", 's', false);
     m_selectCmd->SetParameter(p);
     // reset
     m_resetCmd = new G4UIcommand("/generator/reset", this);
     m_resetCmd->SetGuidance("Reset the generator using the current info.");
     // skipEvents
     m_skipEventsCmd = new G4UIcmdWithAnInteger("/generator/skipEvents", this);
     m_skipEventsCmd->SetGuidance("Skip n events of current generator.");
     m_skipEventsCmd->SetParameterName("NumEvents", false);
     // filename
     m_filenameCmd = new G4UIcommand("/generator/filename", this);
     m_filenameCmd->SetGuidance("Set generator input filename.");
     p = new G4UIparameter("filename", 's', false);
     m_filenameCmd->SetParameter(p);
     // dumpCurrentEvent
     m_enablePrintEventCmd = new G4UIcommand("/generator/printEvent", this);
     m_enablePrintEventCmd->SetGuidance("Dump information about the current generator event.");
     // printNumEventsGenerated
     m_printNumEventsGeneratedCmd = new G4UIcommand("/generator/printNumEventsGenerated", this);
     m_printNumEventsGeneratedCmd->SetGuidance("Print out number of events generated with current generator.");
     // random seed cmd
     m_randomSeedCmd = new G4UIcommand("/random/seed", this);
     m_randomSeedCmd->SetGuidance("Set random seed; no argument seeds with current time.");
     p = new G4UIparameter("seedValue", 'i', true);
     m_randomSeedCmd->SetParameter(p);
     // Lorentz transformation
     m_setLorentzTransformationAngleCmd = new G4UIcmdWithADoubleAndUnit("/generator/setLorentzTransformationAngle", this);
     m_setLorentzTransformationAngleCmd->SetGuidance("Set the Lorentz transformation angle to boost generated events.");
     // Z smearing parameter.
     m_setZSmearingParameterCmd = new G4UIcmdWithADouble("/generator/setZSmearingParameter", this);
     m_setZSmearingParameterCmd->SetGuidance("Set the parameter for smearing vertex Z positions.");
 }
SetNewValue()
void SetNewValue (G4UIcommand * command, G4String newValues) virtual
Process a macro command.
Parameters
[in] command The macro command.
[in] newValues The command arguments.
Definition at line 35 of file GeneratorMessenger.cc.
{
     std::istringstream is((const char*) newVals);
     std::string s;
     is >> s;
     EventSourceManager* mgr = EventSourceManager::instance();
     // select
     if (cmd == m_selectCmd) {
         mgr->setupEventSource(s);
     }
     // reset
     else if (cmd == m_resetCmd) {
         mgr->resetCurrentEventSource();
     }
     // skipEvents
     else if (cmd == m_skipEventsCmd) {
         mgr->setSkipEvents(StringUtil::toInt(s));
     }
     // filename
     else if (cmd == m_filenameCmd) {
         mgr->setFilename(s);
     }
     // dumpCurrentEvent
     else if (cmd == m_enablePrintEventCmd) {
         G4bool enablePrintEvent = StringUtil::toBool(s);
         mgr->enablePrintEvent(enablePrintEvent);
     }
     // printNumEventsGenerated
     else if (cmd == m_printNumEventsGeneratedCmd) {
         mgr->printNumEventsGenerated();
     }
     // set random seed
     else if (cmd == m_randomSeedCmd) {
         G4int seed = 0;
         // seed from user arg
         if (s != std::string("")) {
             seed = StringUtil::toInt(s);
         }
         // seed from time
         // @todo Get MS instead of just seconds, which is not very good quality for a seed.
         else {
             seed = ((unsigned) time(NULL));
         }
         // seed it
         HepRandom::setTheSeed(seed);
         mgr->log() << LOG::okay << "set random seed: " << seed << LOG::done;
     }
     // Lorentz transformation angle
     else if (cmd == m_setLorentzTransformationAngleCmd) {
         EventSourceManager::instance()->setLorentzTransformationAngle(G4UIcmdWithADoubleAndUnit::GetNewDoubleValue(newVals));
     } else if (cmd == m_setZSmearingParameterCmd) {
         EventSourceManager::instance()->setZSmearing(G4UIcmdWithADouble::GetNewDoubleValue(newVals));
     } else {
         G4Exception("", "", JustWarning, "Unknown command.");
     }
 }
References LOG::done, EventSourceManager::enablePrintEvent(), Module::log(), LOG::okay, EventSourceManager::printNumEventsGenerated(), EventSourceManager::resetCurrentEventSource(), EventSourceManager::setFilename(), EventSourceManager::setSkipEvents(), EventSourceManager::setupEventSource(), and LOG::time.
Member Data Documentation
m_enablePrintEventCmd
G4UIcommand* m_enablePrintEventCmd private
Definition at line 57 of file GeneratorMessenger.hh.
m_filenameCmd
G4UIcommand* m_filenameCmd private
Definition at line 56 of file GeneratorMessenger.hh.
m_generatorDir
G4UIdirectory* m_generatorDir private
Definition at line 51 of file GeneratorMessenger.hh.
m_printNumEventsGeneratedCmd
G4UIcommand* m_printNumEventsGeneratedCmd private
Definition at line 58 of file GeneratorMessenger.hh.
m_randomSeedCmd
G4UIcommand* m_randomSeedCmd private
Definition at line 52 of file GeneratorMessenger.hh.
m_resetCmd
G4UIcommand* m_resetCmd private
Definition at line 54 of file GeneratorMessenger.hh.
m_selectCmd
G4UIcommand* m_selectCmd private
Definition at line 53 of file GeneratorMessenger.hh.
m_setLorentzTransformationAngleCmd
G4UIcmdWithADoubleAndUnit* m_setLorentzTransformationAngleCmd private
Definition at line 59 of file GeneratorMessenger.hh.
m_setZSmearingParameterCmd
G4UIcmdWithADouble* m_setZSmearingParameterCmd private
Definition at line 60 of file GeneratorMessenger.hh.
m_skipEventsCmd
G4UIcmdWithAnInteger* m_skipEventsCmd private
Definition at line 55 of file GeneratorMessenger.hh.
The documentation for this class was generated from the following files:
GeneratorMessenger.hh
GeneratorMessenger.cc