SLIC: StackingAction Class Reference
StackingAction Class Reference
Implemention of Geant4's G4UserStackingAction.
#include <StackingAction.hh>
Public Member Functions
StackingAction ()
virtual ~StackingAction ()
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track *aTrack)
void NewStage ()
void PrepareNewEvent ()
Public Member Functions inherited from PluginManagerAccessor
PluginManager * getPluginManager ()
void setPluginManager (PluginManager *pluginManager)
Additional Inherited Members
Protected Attributes inherited from PluginManagerAccessor
PluginManager * m_pluginManager
Detailed Description
Implemention of Geant4's G4UserStackingAction.
Note
Implementation of G4UserStackingAction for SLIC. This is copied from Mokka and right now it just suspends backscattering tracks until the end of shower development.
Definition at line 22 of file StackingAction.hh.
Constructor & Destructor Documentation
StackingAction()
StackingAction ()
Definition at line 10 of file StackingAction.cc.
{
 }
~StackingAction()
~StackingAction () virtual
Definition at line 13 of file StackingAction.cc.
{
 }
Member Function Documentation
ClassifyNewTrack()
G4ClassificationOfNewTrack ClassifyNewTrack (const G4Track * aTrack)
Definition at line 16 of file StackingAction.cc.
{
     // FIXME: Need to determine how these are supposed to work together!
     G4ClassificationOfNewTrack classification = m_pluginManager->stackingClassifyNewTrack(aTrack);
     if (aTrack->GetTrackStatus() == fSuspend)
         classification = fWaiting;
 }
References PluginManagerAccessor::m_pluginManager, and PluginManager::stackingClassifyNewTrack().
NewStage()
void NewStage ()
Definition at line 23 of file StackingAction.cc.
{
     m_pluginManager->stackingNewStage();
 }
References PluginManagerAccessor::m_pluginManager, and PluginManager::stackingNewStage().
PrepareNewEvent()
void PrepareNewEvent ()
Definition at line 27 of file StackingAction.cc.
{
     m_pluginManager->stackingPrepareNewEvent();
 }
References PluginManagerAccessor::m_pluginManager, and PluginManager::stackingPrepareNewEvent().
The documentation for this class was generated from the following files:
StackingAction.hh
StackingAction.cc