SLIC: EventSourceWithInputFile Class Reference
EventSourceWithInputFile Class Reference abstract
An EventSource with an associated input file, such as StdHep or LCIO event files.
#include <EventSourceWithInputFile.hh>
Public Member Functions
virtual ~EventSourceWithInputFile ()
void beginEvent (const G4Event *event)
void beginRun (const G4Run *run)
virtual void close ()=0
const std::string & getFilename ()
bool isEOF ()
virtual void open ()=0
virtual void printCurrentEvent ()=0
virtual void readNextEvent ()=0
void reset ()
void setFilename (const std::string &filename)
unsigned int skipEvents (unsigned int nevents)
Public Member Functions inherited from EventSource
virtual ~EventSource ()
virtual void endEvent (const G4Event *event)
virtual void endRun (const G4Run *run)
virtual void generate (G4Event *event)=0
Public Member Functions inherited from Module
virtual ~Module ()
virtual void cleanup ()
bool deleteOnExit ()
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void stepping (const G4Step *)
Protected Member Functions
EventSourceWithInputFile (const std::string &name, const std::string &filename="")
Protected Member Functions inherited from EventSource
EventSource (const std::string &name)
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Protected Attributes
bool m_eof
bool m_fileIsNew
bool m_fileIsOpen
bool m_fileIsSet
std::string m_filename
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Detailed Description
An EventSource with an associated input file, such as StdHep or LCIO event files.
Definition at line 15 of file EventSourceWithInputFile.hh.
Constructor & Destructor Documentation
EventSourceWithInputFile()
EventSourceWithInputFile (const std::string & name, const std::string & filename = "") inline protected
Class constructor.
Parameters
[in] name The name of the source.
[in] filename The file name of the source.
Definition at line 24 of file EventSourceWithInputFile.hh.
                                                                                         :
                 EventSource(name), m_filename(filename), m_eof(false), m_fileIsOpen(false), m_fileIsNew(false), m_fileIsSet(false) {
         }
~EventSourceWithInputFile()
virtual ~EventSourceWithInputFile () inline virtual
Class destructor.
Definition at line 33 of file EventSourceWithInputFile.hh.
{
         }
Member Function Documentation
beginEvent()
void beginEvent (const G4Event * event) virtual
Begin of event hook.
Parameters
[in] event The Geant4 event.
Reimplemented from EventSource.
Reimplemented in LcioEventSource, LHEEventSource, and StdHepEventSource.
Definition at line 64 of file EventSourceWithInputFile.cc.
{
     readNextEvent();
 }
References EventSourceWithInputFile::readNextEvent().
Referenced by StdHepEventSource::beginEvent(), LHEEventSource::beginEvent(), and LcioEventSource::beginEvent().
beginRun()
void beginRun (const G4Run * run) virtual
Begin run hook.
Parameters
[in] run The Geant4 run.
Reimplemented from EventSource.
Reimplemented in LcioEventSource, LHEEventSource, and StdHepEventSource.
Definition at line 68 of file EventSourceWithInputFile.cc.
{
     // attempt to setup filename from mgr if got a new filename
     if (EventSourceManager::instance()->isNewFilename()) {
         setFilename(EventSourceManager::instance()->getFilename());
     }
     // check if filename is setup correctly
     if (!m_fileIsSet) {
         G4Exception("", "", FatalException, "Generator filename was not set.");
     }
     // reset if new file
     if (m_fileIsNew) {
         // close and open (possibly with new file)
         reset();
         /* Set state variables. */
         m_fileIsNew = false;
         m_fileIsOpen = true;
     }
     // get num events to skip from mgr
     int nskip = EventSourceManager::instance()->getSkipEvents();
     if (nskip) {
 #ifdef SLIC_LOG
         log() << LOG::okay << "Skipping <" << nskip << "> events ..." << LOG::done;
 #endif
         // skip events according to current mgr val
         int actualskipped = skipEvents(nskip);
 #ifdef SLIC_LOG
         log() << LOG::okay << "Skipped <" << actualskipped << "> events." << LOG::done;
         if (actualskipped < nskip) {
             log() << LOG::warning << "Ran out of records to skip on event file!" << LOG::done;
         }
 #endif
         // reset skip events
         EventSourceManager::instance()->setSkipEvents(0);
     }
 }
References LOG::done, EventSourceWithInputFile::getFilename(), Singleton< EventSourceManager >::instance(), Module::log(), EventSourceWithInputFile::m_fileIsNew, EventSourceWithInputFile::m_fileIsOpen, EventSourceWithInputFile::m_fileIsSet, LOG::okay, EventSourceWithInputFile::reset(), EventSourceWithInputFile::setFilename(), EventSourceWithInputFile::skipEvents(), and LOG::warning.
Referenced by StdHepEventSource::beginRun(), LHEEventSource::beginRun(), and LcioEventSource::beginRun().
close()
virtual void close () pure virtual
Close the file associated with the source.
Implemented in LcioEventSource, LHEEventSource, and StdHepEventSource.
Referenced by EventSourceWithInputFile::reset().
getFilename()
const std::string & getFilename ()
Get the file name of the source.
Returns
The file name.
Definition at line 30 of file EventSourceWithInputFile.cc.
{
     return m_filename;
 }
References EventSourceWithInputFile::m_filename.
Referenced by EventSourceWithInputFile::beginRun(), StdHepEventSource::open(), and LHEEventSource::open().
isEOF()
bool isEOF ()
Check if the end of file has been reached.
Definition at line 60 of file EventSourceWithInputFile.cc.
{
     return m_eof;
 }
References EventSourceWithInputFile::m_eof.
Referenced by EventSourceManager::isEOF(), and EventSourceWithInputFile::skipEvents().
open()
virtual void open () pure virtual
Open the file associated with the source.
Implemented in LcioEventSource, LHEEventSource, and StdHepEventSource.
Referenced by EventSourceWithInputFile::reset().
printCurrentEvent()
virtual void printCurrentEvent () pure virtual
Dump the current event to std::cout.
Implements EventSource.
Implemented in LcioEventSource, LHEEventSource, and StdHepEventSource.
readNextEvent()
virtual void readNextEvent () pure virtual
Read the next event.
Implemented in LcioEventSource, LHEEventSource, and StdHepEventSource.
Referenced by EventSourceWithInputFile::beginEvent(), and EventSourceWithInputFile::skipEvents().
reset()
void reset () virtual
Reset the source back to the beginning of the file.
Reimplemented from EventSource.
Definition at line 34 of file EventSourceWithInputFile.cc.
{
     // close if open
     if (m_fileIsOpen) {
         close();
     }
     // (re)open
     open();
     // should not be EOF now (maybe on next read)
     m_eof = false;
 }
References EventSourceWithInputFile::close(), EventSourceWithInputFile::m_eof, EventSourceWithInputFile::m_fileIsOpen, and EventSourceWithInputFile::open().
Referenced by EventSourceWithInputFile::beginRun().
setFilename()
void setFilename (const std::string & filename)
Set the file name of the source.
Parameters
[in] filename The file name.
Definition at line 8 of file EventSourceWithInputFile.cc.
{
     if (s != std::string("")) {
         if (FileUtil::fileExists(s)) {
             m_filename = s;
             m_fileIsSet = true;
             m_fileIsNew = true;
         }
 #ifdef SLIC_LOG
         else {
             log() << LOG::error << "Ignoring nonexistant input file <" << s << ">." << LOG::done;
         }
 #endif
     }
 #ifdef SLIC_LOG
     else {
         log() << LOG::error << "Ignoring blank filename." << LOG::done;
     }
 #endif
 }
References LOG::done, LOG::error, FileUtil::fileExists(), Module::log(), EventSourceWithInputFile::m_fileIsNew, EventSourceWithInputFile::m_fileIsSet, and EventSourceWithInputFile::m_filename.
Referenced by EventSourceWithInputFile::beginRun().
skipEvents()
unsigned int skipEvents (unsigned int nevents) virtual
Skip a number of events in the source's file.
Parameters
[in] nevents The number of events to skip.
Reimplemented from EventSource.
Definition at line 47 of file EventSourceWithInputFile.cc.
{
     unsigned int i;
     for (i = 0; i < nevents; i++) {
         if (isEOF()) {
             break;
         }
         readNextEvent();
     }
     return i;
 }
References EventSourceWithInputFile::isEOF(), and EventSourceWithInputFile::readNextEvent().
Referenced by EventSourceWithInputFile::beginRun().
Member Data Documentation
m_eof
bool m_eof protected
Definition at line 104 of file EventSourceWithInputFile.hh.
Referenced by EventSourceWithInputFile::isEOF(), StdHepEventSource::readNextEvent(), LcioEventSource::readNextEvent(), and EventSourceWithInputFile::reset().
m_fileIsNew
bool m_fileIsNew protected
Definition at line 106 of file EventSourceWithInputFile.hh.
Referenced by EventSourceWithInputFile::beginRun(), and EventSourceWithInputFile::setFilename().
m_fileIsOpen
bool m_fileIsOpen protected
Definition at line 105 of file EventSourceWithInputFile.hh.
Referenced by EventSourceWithInputFile::beginRun(), StdHepEventSource::close(), LHEEventSource::close(), LcioEventSource::close(), StdHepEventSource::open(), LHEEventSource::open(), LcioEventSource::open(), and EventSourceWithInputFile::reset().
m_fileIsSet
bool m_fileIsSet protected
Definition at line 107 of file EventSourceWithInputFile.hh.
Referenced by EventSourceWithInputFile::beginRun(), and EventSourceWithInputFile::setFilename().
m_filename
std::string m_filename protected
Definition at line 101 of file EventSourceWithInputFile.hh.
Referenced by EventSourceWithInputFile::getFilename(), LcioEventSource::open(), and EventSourceWithInputFile::setFilename().
The documentation for this class was generated from the following files:
EventSourceWithInputFile.hh
EventSourceWithInputFile.cc