SLIC: LcioFileNamer Class Reference
LcioFileNamer Class Reference
Automatically name LCIO output files according to input settings.
#include <LcioFileNamer.hh>
Public Member Functions
LcioFileNamer ()
virtual ~LcioFileNamer ()
std::string makeFileName (std::vector< std::string > fields)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Private Member Functions
std::string getFieldValue (std::string field)
std::string makeDefaultFileName ()
Static Private Member Functions
static std::string getGeant4VersionString ()
static std::string makeEventName ()
static std::string makeEventNumberString ()
static std::string makeFileBasedName ()
static std::string makeGPSName ()
static std::string makeGunName ()
static std::string makeRunNumberString ()
Private Attributes
std::vector< std::string > m_defaultFields
Static Private Attributes
static std::string m_sep = "_"
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
Automatically name LCIO output files according to input settings.
Definition at line 20 of file LcioFileNamer.hh.
Constructor & Destructor Documentation
LcioFileNamer()
LcioFileNamer ()
Class constructor.
Definition at line 29 of file LcioFileNamer.cc.
                              :
         Module("LcioFileNamer") {
     m_defaultFields.push_back("event");
     m_defaultFields.push_back("application");
     m_defaultFields.push_back("physics");
     m_defaultFields.push_back("geometry");
 }
References LcioFileNamer::m_defaultFields.
~LcioFileNamer()
~LcioFileNamer () virtual
Definition at line 37 of file LcioFileNamer.cc.
{
 }
Member Function Documentation
getFieldValue()
std::string getFieldValue (std::string field) private
Get the value of a field.
Parameters
[in] field The field name.
Definition at line 40 of file LcioFileNamer.cc.
{
     std::string value;
     static std::string sep("-");
     if (field == "application") {
         value = PackageInfo::getShortName() + "-v" + PackageInfo::getVersion(sep);
     } else if (field == "geometry") {
         value = LCDDProcessor::instance()->getDetectorName();
     } else if (field == "date") {
         value = TimeUtil::getDate();
     } else if (field == "event" || field == "evt") {
         value = LcioFileNamer::makeEventName();
     } else if (field == "eventNumber") {
         value = LcioFileNamer::makeEventNumberString();
     } else if (field == "run") {
         value = LcioFileNamer::makeRunNumberString();
     } else if (field == "binary") {
         value = SlicApplication::instance()->getBinaryBasename();
     } else if (field == "physics") {
         value = PhysicsListManager::instance()->getCurrentListName();
     } else {
 #ifdef SLIC_LOG
         log() << LOG::error << "Ignoring unknown autoname field <" << field << ">." << LOG::done;
 #endif
         value = "";
     }
     return value;
 }
References LOG::done, LOG::error, TimeUtil::getDate(), Singleton< SlicApplication >::instance(), Singleton< PhysicsListManager >::instance(), Module::log(), LcioFileNamer::makeEventName(), LcioFileNamer::makeEventNumberString(), LcioFileNamer::makeRunNumberString(), and LOG::sep.
Referenced by LcioFileNamer::makeFileName().
getGeant4VersionString()
static std::string getGeant4VersionString () static private
Create a string with the Geant4 version information.
Returns
The Geant4 version string.
makeDefaultFileName()
std::string makeDefaultFileName () private
Create the file name using the default set of fields.
Returns
The file name.
Definition at line 88 of file LcioFileNamer.cc.
{
     return makeFileName(m_defaultFields);
 }
References LcioFileNamer::m_defaultFields, and LcioFileNamer::makeFileName().
Referenced by LcioFileNamer::makeFileName().
makeEventName()
std::string makeEventName () static private
Create the file name based on the current event generator.
Returns
The file name.
Definition at line 92 of file LcioFileNamer.cc.
{
     std::string evt;
     EventSourceManager::ESourceType est = EventSourceManager::instance()->getCurrentSourceType();
     if (EventSourceManager::instance()->isFileSource()) {
         evt = makeFileBasedName();
     } else if (est == EventSourceManager::eGPS) {
         evt = makeGPSName();
     } else if (est == EventSourceManager::eParticleGun) {
         evt = makeGunName();
     } else {
         evt = "events";
     }
     return evt;
 }
References EventSourceManager::eGPS, EventSourceManager::eParticleGun, Singleton< EventSourceManager >::instance(), LcioFileNamer::makeFileBasedName(), LcioFileNamer::makeGPSName(), and LcioFileNamer::makeGunName().
Referenced by LcioFileNamer::getFieldValue().
makeEventNumberString()
std::string makeEventNumberString () static private
Create a string from the number of events that were run using 'beamon'.
Returns
The number of events that were run.
Definition at line 153 of file LcioFileNamer.cc.
{
     return StringUtil::toString(SlicApplication::instance()->getRunManager()->getNumberOfEventsToRun());
 }
References Singleton< SlicApplication >::instance().
Referenced by LcioFileNamer::getFieldValue().
makeFileBasedName()
std::string makeFileBasedName () static private
Create the file name based on a generator with an input file.
Returns
The file name.
Definition at line 109 of file LcioFileNamer.cc.
{
     std::string fname = EventSourceManager::instance()->getFilename();
     // basename and remove file extension
     fname = FileUtil::removeExtension(FileUtil::basename(fname));
     return fname;
 }
References FileUtil::basename(), Singleton< EventSourceManager >::instance(), and FileUtil::removeExtension().
Referenced by LcioFileNamer::makeEventName().
makeFileName()
std::string makeFileName (std::vector< std::string > fields)
Create a file name based on a list of fields to include.
Parameters
[in] fields The list of fields.
Returns
The file name.
Definition at line 70 of file LcioFileNamer.cc.
{
     std::string filename = "";
     if (fieldList.size() != 0) {
         for (std::vector<std::string>::const_iterator it = fieldList.begin(); it != fieldList.end(); it++) {
             std::string value = getFieldValue(*it);
             if (value != "") {
                 filename = filename + value + m_sep;
             }
         }
         if (filename != "") {
             filename.erase(filename.end() - 1, filename.end());
         }
     } else {
         filename = makeDefaultFileName();
     }
     return filename;
 }
References LcioFileNamer::getFieldValue(), LcioFileNamer::m_sep, and LcioFileNamer::makeDefaultFileName().
Referenced by LcioManager::makeAutoname(), and LcioFileNamer::makeDefaultFileName().
makeGPSName()
std::string makeGPSName () static private
Create the file name based on settings of the Geant4 GPS.
Returns
The file name.
Definition at line 118 of file LcioFileNamer.cc.
{
     G4GeneralParticleSource* gps = EventSourceManager::instance()->getGPS();
     // particle name
     std::string pname = gps->GetParticleDefinition()->GetParticleName();
     // energy
     double ene = gps->GetCurrentSource()->GetEneDist()->GenerateOne(gps->GetParticleDefinition());
     std::string eneStr = StringUtil::toString(ene / GeV) + "GeV";
     // full string
     std::string evtname = pname + m_sep + eneStr;
     return evtname;
 }
References Singleton< EventSourceManager >::instance(), and LcioFileNamer::m_sep.
Referenced by LcioFileNamer::makeEventName().
makeGunName()
std::string makeGunName () static private
Create the file name based on settings of the Geant4 particle gun.
Returns
The file name.
Definition at line 134 of file LcioFileNamer.cc.
{
     G4ParticleGun* gun = EventSourceManager::instance()->getParticleGun();
     // particle name
     std::string pname = gun->GetParticleDefinition()->GetParticleName();
     // energy
     std::string pE = StringUtil::toString(gun->GetParticleEnergy() / GeV) + "GeV";
     // full string
     std::string evtname = pname + m_sep + pE;
     return evtname;
 }
References Singleton< EventSourceManager >::instance(), and LcioFileNamer::m_sep.
Referenced by LcioFileNamer::makeEventName().
makeRunNumberString()
std::string makeRunNumberString () static private
Create a string from the current run number information in the RunManager.
Returns
The run number string.
Definition at line 149 of file LcioFileNamer.cc.
{
     return StringUtil::toString(G4RunManager::GetRunManager()->GetCurrentRun()->GetRunID());
 }
Referenced by LcioFileNamer::getFieldValue().
Member Data Documentation
m_defaultFields
std::vector<std::string> m_defaultFields private
Definition at line 99 of file LcioFileNamer.hh.
Referenced by LcioFileNamer::LcioFileNamer(), and LcioFileNamer::makeDefaultFileName().
m_sep
std::string m_sep = "_" static private
Definition at line 98 of file LcioFileNamer.hh.
Referenced by LcioFileNamer::makeFileName(), LcioFileNamer::makeGPSName(), and LcioFileNamer::makeGunName().
The documentation for this class was generated from the following files:
LcioFileNamer.hh
LcioFileNamer.cc