SLIC: LogManager Class Reference
LogManager Class Reference
Manages LogStreams and their associated LogMessenger objects.
#include <LogManager.hh>
Public Member Functions
LogManager ()
virtual ~LogManager ()
LogStream * createLog (std::string name="NONE", LOG::ELevel level=LOG::okay, ostream *os=&std::cout)
LogStream * createLogWithMessenger (std::string name="NONE", LOG::ELevel level=LOG::okay, ostream *os=&std::cout)
void removeLog (LogStream *log)
Public Member Functions inherited from Singleton< LogManager >
Singleton ()
~Singleton ()
void release ()
Private Types
typedef std::vector< LogStream * > LogList
typedef LogList::iterator LogListIterator
typedef std::vector< LogMessenger * > LogMessengerList
typedef LogMessengerList::iterator LogMessengerListIterator
typedef std::map< LogStream *, LogMessenger * > LogMessengerMap
typedef std::map< std::string, LogStream * > LogNameMap
Private Member Functions
LogMessenger * createLogMessenger (LogStream *l)
LogStream * findLog (const std::string &name)
LogListIterator findLog (LogStream *log)
LogMessengerListIterator findLogMessenger (LogMessenger *lm)
LogMessenger * findLogMessenger (LogStream *s)
void removeLogMessenger (LogMessenger *lm)
Private Attributes
G4UIdirectory * m_logDir
LogMessengerMap m_logMessengerMap
LogNameMap m_logNameMap
LogList m_logs
LogMessengerList m_messengers
Friends
class LogStream
Additional Inherited Members
Static Public Member Functions inherited from Singleton< LogManager >
static LogManager * instance ()
Detailed Description
Manages LogStreams and their associated LogMessenger objects.
Note
This class "owns" both LogStream and LogMessenger objects, so neither of these classes should be deleted outside of this class.
LogManager and LogStream are both friends of each other.
Definition at line 31 of file LogManager.hh.
Member Typedef Documentation
LogList
typedef std::vector<LogStream*> LogList private
Definition at line 36 of file LogManager.hh.
LogListIterator
typedef LogList::iterator LogListIterator private
Definition at line 39 of file LogManager.hh.
LogMessengerList
typedef std::vector<LogMessenger*> LogMessengerList private
Definition at line 42 of file LogManager.hh.
LogMessengerListIterator
typedef LogMessengerList::iterator LogMessengerListIterator private
Definition at line 45 of file LogManager.hh.
LogMessengerMap
typedef std::map<LogStream*, LogMessenger*> LogMessengerMap private
Definition at line 51 of file LogManager.hh.
LogNameMap
typedef std::map<std::string, LogStream*> LogNameMap private
Definition at line 48 of file LogManager.hh.
Constructor & Destructor Documentation
LogManager()
LogManager () inline
Class constructor.
Definition at line 58 of file LogManager.hh.
                      {
             m_logDir = new G4UIdirectory("/log/");
             m_logDir->SetGuidance("Commands for changing log output settings. [SLIC]");
         }
References LogManager::m_logDir.
~LogManager()
virtual ~LogManager () inline virtual
Class destructor.
Definition at line 66 of file LogManager.hh.
{
             delete m_logDir;
         }
References LogManager::m_logDir.
Member Function Documentation
createLog()
LogStream* createLog (std::string name = "NONE", LOG::ELevel level = LOG::okay, ostream * os = &std::cout) inline
Create a LogStream.
Parameters
[in] name The name of the LogStream.
[in] level The log level.
[in] os The output stream.
Definition at line 78 of file LogManager.hh.
{
             LogStream *l = new LogStream(name, level, os);
             m_logs.push_back(l);
             m_logNameMap[name] = l;
             return l;
         }
References LOG::level, LogManager::LogStream, LogManager::m_logNameMap, LogManager::m_logs, and LOG::name.
Referenced by LogManager::createLogWithMessenger().
createLogMessenger()
LogMessenger* createLogMessenger (LogStream * l) inline private
Create a LogMessenger attached to the given LogStream.
Parameters
[in] l The LogStream.
Returns
The new LogMessenger assigned to the LogStream.
Definition at line 129 of file LogManager.hh.
{
             // Check for and return an existing LogMessenger.
             LogMessenger *check = findLogMessenger(l);
             if (check != 0) {
                 return check;
             }
             // Make a new LogMessenger.
             LogMessenger *lm = new LogMessenger(l);
             m_messengers.push_back(lm);
             m_logMessengerMap[l] = lm;
             return lm;
         }
References LogManager::findLogMessenger(), LogManager::m_logMessengerMap, and LogManager::m_messengers.
Referenced by LogManager::createLogWithMessenger().
createLogWithMessenger()
LogStream* createLogWithMessenger (std::string name = "NONE", LOG::ELevel level = LOG::okay, ostream * os = &std::cout) inline
Create a LogStream and associated LogMessenger.
Parameters
[in] name The name of the LogStream.
[in] level The log level.
[in] os The output stream.
Definition at line 91 of file LogManager.hh.
{
             LogStream *l = createLog(name, level, os);
             createLogMessenger(l);
             return l;
         }
References LogManager::createLog(), LogManager::createLogMessenger(), LOG::level, and LOG::name.
findLog() [1/2]
LogStream* findLog (const std::string & name) inline private
Find a LogStream pointer by name.
Parameters
[in] name The name of the LogStream.
Definition at line 161 of file LogManager.hh.
{
             return m_logNameMap[name];
         }
References LogManager::m_logNameMap, and LOG::name.
Referenced by LogManager::removeLog().
findLog() [2/2]
LogListIterator findLog (LogStream * log) inline private
Get position of LogStream by its pointer.
Parameters
[in] log The LogStream.
Returns
An iterator pointing to the LogStream.
Definition at line 170 of file LogManager.hh.
{
             if (log == 0)
                 return m_logs.end();
             return find(m_logs.begin(), m_logs.end(), log);
         }
References LogManager::m_logs.
findLogMessenger() [1/2]
LogMessengerListIterator findLogMessenger (LogMessenger * lm) inline private
Find position of LogMessenger by its pointer.
Parameters
[in] lm The LogMessenger.
Returns
An iterator pointing to the LogMessenger.
Definition at line 181 of file LogManager.hh.
{
             if (lm == 0)
                 return m_messengers.end();
             return find(m_messengers.begin(), m_messengers.end(), lm);
         }
References LogManager::m_messengers.
Referenced by LogManager::createLogMessenger(), LogManager::removeLog(), and LogManager::removeLogMessenger().
findLogMessenger() [2/2]
LogMessenger* findLogMessenger (LogStream * s) inline private
Find a LogMessenger by its associated LogStream.
Parameters
[in] s The LogStream.
Returns
The LogMessenger or null if not found.
Definition at line 192 of file LogManager.hh.
{
             return m_logMessengerMap[s];
         }
References LogManager::m_logMessengerMap.
removeLog()
void removeLog (LogStream * log) inline
Remove a LogStream and also its LogMessenger, if it exists.
Parameters
[in] log The LogStream to remove.
Definition at line 101 of file LogManager.hh.
{
             if (log == 0)
                 return;
             LogListIterator it = findLog(log);
             if (it != m_logs.end()) {
                 LogStream *l = (*it);
                 // Delete the LogStream's messenger, if it exists.
                 LogMessenger *lm = findLogMessenger(l);
                 if (lm != 0) {
                     removeLogMessenger(lm);
                 }
                 // Delete the LogStream object.
                 delete (*it);
                 // Remove the LogStream entry.
                 m_logs.erase(it);
             }
         }
References LogManager::findLog(), LogManager::findLogMessenger(), LogManager::m_logs, and LogManager::removeLogMessenger().
removeLogMessenger()
void removeLogMessenger (LogMessenger * lm) inline private
Remove a LogMessenger.
Parameters
lm The LogMessenger to remove.
Definition at line 147 of file LogManager.hh.
{
             if (lm == 0)
                 return;
             LogMessengerListIterator it = findLogMessenger(lm);
             if (it != m_messengers.end()) {
                 delete (*it);
                 m_messengers.erase(it);
             }
         }
References LogManager::findLogMessenger(), and LogManager::m_messengers.
Referenced by LogManager::removeLog().
Friends And Related Function Documentation
LogStream
friend class LogStream friend
Definition at line 196 of file LogManager.hh.
Referenced by LogManager::createLog().
Member Data Documentation
m_logDir
G4UIdirectory* m_logDir private
Definition at line 204 of file LogManager.hh.
Referenced by LogManager::LogManager(), and LogManager::~LogManager().
m_logMessengerMap
LogMessengerMap m_logMessengerMap private
Definition at line 202 of file LogManager.hh.
Referenced by LogManager::createLogMessenger(), and LogManager::findLogMessenger().
m_logNameMap
LogNameMap m_logNameMap private
Definition at line 201 of file LogManager.hh.
Referenced by LogManager::createLog(), and LogManager::findLog().
m_logs
LogList m_logs private
Definition at line 199 of file LogManager.hh.
Referenced by LogManager::createLog(), LogManager::findLog(), and LogManager::removeLog().
m_messengers
LogMessengerList m_messengers private
Definition at line 200 of file LogManager.hh.
Referenced by LogManager::createLogMessenger(), LogManager::findLogMessenger(), and LogManager::removeLogMessenger().
The documentation for this class was generated from the following file:
LogManager.hh