SLIC: MCParticleGenerator Class Reference
MCParticleGenerator Class Reference
Converts from MCParticle collection into a G4Event.
#include <MCParticleGenerator.hh>
Public Member Functions
MCParticleGenerator (G4String eventFile)
virtual ~MCParticleGenerator ()
void generateEvent (G4Event *event)
LCEvent * getCurrentEvent ()
void readNextEvent ()
Private Attributes
LCEvent * _lcevent
MCParticleManager * _particleManager
LCReader * _reader
Detailed Description
Converts from MCParticle collection into a G4Event.
Definition at line 31 of file MCParticleGenerator.hh.
Constructor & Destructor Documentation
MCParticleGenerator()
MCParticleGenerator (G4String eventFile)
Class constructor.
Setup the reader.
Definition at line 23 of file MCParticleGenerator.cc.
References MCParticleGenerator::_particleManager, MCParticleGenerator::_reader, and Singleton< MCParticleManager >::instance().
~MCParticleGenerator()
~MCParticleGenerator () virtual
Class destructor.
Definition at line 36 of file MCParticleGenerator.cc.
References MCParticleGenerator::_reader.
Member Function Documentation
generateEvent()
void generateEvent (G4Event * event)
Generate a G4Event from an MCParticleCollection in an LCEvent.
Parameters
[in,out] event The input G4Event to be created.
Definition at line 48 of file MCParticleGenerator.cc.
References MCParticleGenerator::_lcevent, MCParticleGenerator::_particleManager, and MCParticleManager::generateEvent().
Referenced by LcioEventSource::generate().
getCurrentEvent()
LCEvent * getCurrentEvent ()
Get the current LCEvent.
Returns
The current LCEvent.
Definition at line 44 of file MCParticleGenerator.cc.
References MCParticleGenerator::_lcevent.
Referenced by LcioEventSource::readNextEvent().
readNextEvent()
void readNextEvent ()
Read the next LCEvent.
Definition at line 40 of file MCParticleGenerator.cc.
References MCParticleGenerator::_lcevent, and MCParticleGenerator::_reader.
Referenced by LcioEventSource::readNextEvent().
Member Data Documentation
_lcevent
LCEvent* _lcevent private
Definition at line 64 of file MCParticleGenerator.hh.
Referenced by MCParticleGenerator::generateEvent(), MCParticleGenerator::getCurrentEvent(), and MCParticleGenerator::readNextEvent().
_particleManager
MCParticleManager* _particleManager private
Definition at line 66 of file MCParticleGenerator.hh.
Referenced by MCParticleGenerator::generateEvent(), and MCParticleGenerator::MCParticleGenerator().
_reader
LCReader* _reader private
Definition at line 65 of file MCParticleGenerator.hh.
Referenced by MCParticleGenerator::MCParticleGenerator(), MCParticleGenerator::readNextEvent(), and MCParticleGenerator::~MCParticleGenerator().
The documentation for this class was generated from the following files:
MCParticleGenerator.hh
MCParticleGenerator.cc