SLIC: LHEParticle Class Reference
LHEParticle Class Reference
Single particle record in an LHE event.
#include <LHEParticle.hh>
Public Member Functions
LHEParticle (std::string &data)
int getICOLUP (int) const
int getIDUP () const
int getISTUP () const
LHEParticle * getMother (int) const
int getMOTHUP (int) const
double getPUP (int) const
double getSPINUP () const
double getVTIMUP () const
void print (std::ostream &stream) const
void setMother (int i, LHEParticle *particle)
Private Attributes
int icolup_ [2]
int idup_
int istup_
LHEParticle * mothers_ [2]
int mothup_ [2]
double pup_ [5]
int spinup_
double vtimup_
Friends
std::ostream & operator<< (std::ostream &stream, const LHEParticle &particle)
Detailed Description
Single particle record in an LHE event.
Definition at line 20 of file LHEParticle.hh.
Constructor & Destructor Documentation
LHEParticle()
LHEParticle (std::string & data)
Class constructor.
Parameters
data The particle record as a space-delimited string.
Definition at line 15 of file LHEParticle.cc.
{
         std::istringstream iss(line);
         std::vector<std::string> tokens;
         do {
             std::string elem;
             iss >> elem;
             if (elem.size() != 0) {
                 tokens.push_back(elem);
             }
         } while (iss);
         if (tokens.size() != 13) {
             std::cerr << "ERROR: Bad particle record in LHE file ..." << std::endl;
             std::cerr << "  " << line << std::endl;
             G4Exception("LHEParticle::LHEParticle", "LHEParticleError", FatalException, "Wrong number of tokens in LHE particle record.");
         }
         idup_ = atof(tokens[0].c_str());
         istup_ = atoi(tokens[1].c_str());
         mothup_[0] = atoi(tokens[2].c_str());
         mothup_[1] = atoi(tokens[3].c_str());
         icolup_[0] = atoi(tokens[4].c_str());
         icolup_[1] = atoi(tokens[5].c_str());
         pup_[0] = atof(tokens[6].c_str());
         pup_[1] = atof(tokens[7].c_str());
         pup_[2] = atof(tokens[8].c_str());
         pup_[3] = atof(tokens[9].c_str());
         pup_[4] = atof(tokens[10].c_str());
         vtimup_ = atof(tokens[11].c_str());
         spinup_ = atof(tokens[12].c_str());
         mothers_[0] = NULL;
         mothers_[1] = NULL;
     }
References LOG::endl, LHEParticle::icolup_, LHEParticle::idup_, LHEParticle::istup_, LHEParticle::mothers_, LHEParticle::mothup_, LHEParticle::pup_, LHEParticle::spinup_, and LHEParticle::vtimup_.
Member Function Documentation
getICOLUP()
int getICOLUP (int i) const
Get the particle color (ICOLUP) by index.
Returns
The particle color by index.
Definition at line 63 of file LHEParticle.cc.
{
         return icolup_[i];
     }
References LHEParticle::icolup_.
Referenced by LHEParticle::print().
getIDUP()
int getIDUP () const
Get the PDG code (IDUP).
Returns
The PDG code.
Definition at line 51 of file LHEParticle.cc.
{
         return idup_;
     }
References LHEParticle::idup_.
Referenced by LHEPrimaryGenerator::GeneratePrimaryVertex(), and LHEParticle::print().
getISTUP()
int getISTUP () const
Get the status code (ISTUP).
Returns
The status code.
Definition at line 55 of file LHEParticle.cc.
{
         return istup_;
     }
References LHEParticle::istup_.
Referenced by LHEPrimaryGenerator::GeneratePrimaryVertex(), and LHEParticle::print().
getMother()
LHEParticle * getMother (int i) const
Get a mother particle by index.
Returns
The mother particle at the index.
Definition at line 83 of file LHEParticle.cc.
{
         return mothers_[i];
     }
References LHEParticle::mothers_.
Referenced by LHEPrimaryGenerator::GeneratePrimaryVertex().
getMOTHUP()
int getMOTHUP (int i) const
Get a mother particle index (MOTHUP) by index.
Returns
The mother particle by index.
Definition at line 59 of file LHEParticle.cc.
{
         return mothup_[i];
     }
References LHEParticle::mothup_.
Referenced by LHEParticle::print(), and LHEReader::readNextEvent().
getPUP()
double getPUP (int i) const
Get a momentum component (PUP) by index. Defined in order: E/C, Px, Py, Pz, mass
Returns
The momentum component by index.
Definition at line 67 of file LHEParticle.cc.
{
         return pup_[i];
     }
References LHEParticle::pup_.
Referenced by LHEPrimaryGenerator::GeneratePrimaryVertex(), and LHEParticle::print().
getSPINUP()
double getSPINUP () const
Get the particle's spin (SPINUP).
Returns
The particle's spin.
Definition at line 75 of file LHEParticle.cc.
{
         return spinup_;
     }
References LHEParticle::spinup_.
Referenced by LHEParticle::print().
getVTIMUP()
double getVTIMUP () const
Get the proper lifetime (VTIMUP).
Returns
The particle's proper lifetime.
Definition at line 71 of file LHEParticle.cc.
{
         return vtimup_;
     }
References LHEParticle::vtimup_.
Referenced by LHEPrimaryGenerator::GeneratePrimaryVertex(), and LHEParticle::print().
print()
void print (std::ostream & stream) const
Print particle information to an output stream.
Parameters
stream The output stream.
Definition at line 87 of file LHEParticle.cc.
{
         stream << "LHEParticle { " << "IDUP: " << getIDUP() << ", ISTUP: " << getISTUP() << ", MOTHUP[0]: " << getMOTHUP(0) << ", MOTHUP[1]: " << getMOTHUP(1) << ", ICOLUP[0]: " << getICOLUP(0) << ", ICOLUP[1]: " << getICOLUP(1) << ", PUP[0]: " << getPUP(0) << ", PUP[1]: " << getPUP(1) << ", PUP[2]: " << getPUP(2) << ", PUP[3]: " << getPUP(3) << ", PUP[4]: " << getPUP(4) << ", VTIMUP: " << getVTIMUP() << ", SPINUP: " << getSPINUP() << " }" << std::endl;
     }
References LOG::endl, LHEParticle::getICOLUP(), LHEParticle::getIDUP(), LHEParticle::getISTUP(), LHEParticle::getMOTHUP(), LHEParticle::getPUP(), LHEParticle::getSPINUP(), and LHEParticle::getVTIMUP().
Referenced by slic::operator<<().
setMother()
void setMother (int i, LHEParticle * particle)
Set a mother particle by index.
Parameters
i The mother index.
particle The mother particle.
Definition at line 79 of file LHEParticle.cc.
{
         mothers_[i] = mother;
     }
References LHEParticle::mothers_.
Referenced by LHEReader::readNextEvent().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const LHEParticle & particle) friend
Overloaded stream operator.
Parameters
stream The output stream.
particle The particle to print.
Definition at line 91 of file LHEParticle.cc.
{
         particle.print(stream);
         return stream;
     }
Member Data Documentation
icolup_
int icolup_[2] private
The particle color.
Definition at line 124 of file LHEParticle.hh.
Referenced by LHEParticle::getICOLUP(), and LHEParticle::LHEParticle().
idup_
int idup_ private
The PDG code.
Definition at line 109 of file LHEParticle.hh.
Referenced by LHEParticle::getIDUP(), and LHEParticle::LHEParticle().
istup_
int istup_ private
The status code.
Definition at line 114 of file LHEParticle.hh.
Referenced by LHEParticle::getISTUP(), and LHEParticle::LHEParticle().
mothers_
LHEParticle* mothers_[2] private
The mother particles.
Definition at line 104 of file LHEParticle.hh.
Referenced by LHEParticle::getMother(), LHEParticle::LHEParticle(), and LHEParticle::setMother().
mothup_
int mothup_[2] private
The mother particle indices.
Definition at line 119 of file LHEParticle.hh.
Referenced by LHEParticle::getMOTHUP(), and LHEParticle::LHEParticle().
pup_
double pup_[5] private
The momentum components.
Definition at line 129 of file LHEParticle.hh.
Referenced by LHEParticle::getPUP(), and LHEParticle::LHEParticle().
spinup_
int spinup_ private
The particle's spin.
Definition at line 139 of file LHEParticle.hh.
Referenced by LHEParticle::getSPINUP(), and LHEParticle::LHEParticle().
vtimup_
double vtimup_ private
The proper time.
Definition at line 134 of file LHEParticle.hh.
Referenced by LHEParticle::getVTIMUP(), and LHEParticle::LHEParticle().
The documentation for this class was generated from the following files:
LHEParticle.hh
LHEParticle.cc