SLIC: LHEPrimaryGenerator Class Reference
LHEPrimaryGenerator Class Reference
Generates a Geant4 event from an LHEEvent.
#include <LHEPrimaryGenerator.hh>
Public Member Functions
LHEPrimaryGenerator (LHEReader *reader)
virtual ~LHEPrimaryGenerator ()
void GeneratePrimaryVertex (G4Event *anEvent)
Private Attributes
LHEReader * reader_
Detailed Description
Generates a Geant4 event from an LHEEvent.
Definition at line 22 of file LHEPrimaryGenerator.hh.
Constructor & Destructor Documentation
LHEPrimaryGenerator()
LHEPrimaryGenerator (LHEReader * reader)
Class constructor.
Parameters
reader The LHE reader with the event data.
Definition at line 17 of file LHEPrimaryGenerator.cc.
                                                                  :
             reader_(theReader) {
     }
~LHEPrimaryGenerator()
~LHEPrimaryGenerator () virtual
Class destructor.
Definition at line 21 of file LHEPrimaryGenerator.cc.
{
         delete reader_;
     }
References LHEPrimaryGenerator::reader_.
Member Function Documentation
GeneratePrimaryVertex()
void GeneratePrimaryVertex (G4Event * anEvent)
Generate vertices in the Geant4 event.
Parameters
anEvent The Geant4 event.
Definition at line 25 of file LHEPrimaryGenerator.cc.
{
         LHEEvent* lheEvent = reader_->readNextEvent();
         if (lheEvent != NULL) {
             G4PrimaryVertex* vertex = new G4PrimaryVertex();
             vertex->SetPosition(0, 0, 0);
             vertex->SetWeight(lheEvent->getXWGTUP());
             std::map<LHEParticle*, G4PrimaryParticle*> particleMap;
             int particleIndex = 0;
             const std::vector<LHEParticle*>& particles = lheEvent->getParticles();
             for (std::vector<LHEParticle*>::const_iterator it = particles.begin(); it != particles.end(); it++) {
                 LHEParticle* particle = (*it);
                 if (particle->getISTUP() > 0) {
                     G4PrimaryParticle* primary = new G4PrimaryParticle();
                     if (particle->getIDUP() == -623) { /* Tungsten ion */
                         G4ParticleDefinition* tungstenIonDef = G4IonTable::GetIonTable()->GetIon(74, 184, 0.);
                         if (tungstenIonDef != NULL) {
                             primary->SetParticleDefinition(tungstenIonDef);
                         } else {
                             G4Exception("LHEPrimaryGenerator::GeneratePrimaryVertex", "EventGenerationError", FatalException, "Failed to find particle definition for W ion.");
                         }
                     } else {
                         primary->SetPDGcode(particle->getIDUP());
                     }
                     primary->Set4Momentum(particle->getPUP(0) * GeV, particle->getPUP(1) * GeV, particle->getPUP(2) * GeV, particle->getPUP(3) * GeV);
                     primary->SetProperTime(particle->getVTIMUP() * nanosecond);
                     //UserPrimaryParticleInformation* primaryInfo = new UserPrimaryParticleInformation();
                     //primaryInfo->setHepEvtStatus(particle->getISTUP());
                     //primary->SetUserInformation(primaryInfo);
                     particleMap[particle] = primary;
                     /*
                      * Assign primary as daughter but only if the mother is not a DOC particle.
                      */
                     if (particle->getMother(0) != NULL && particle->getMother(0)->getISTUP() > 0) {
                         G4PrimaryParticle* primaryMom = particleMap[particle->getMother(0)];
                         if (primaryMom != NULL) {
                             primaryMom->SetDaughter(primary);
                         }
                     } else {
                         vertex->SetPrimary(primary);
                     }
                     // Uncomment to print out the G4 primary particle that was created.
                     //primary->Print();
                 } else {
                 }
                 //std::cout << std::endl;
                 ++particleIndex;
             }
             anEvent->AddPrimaryVertex(vertex);
         } else {
             std::cout << "[ LHEPrimaryGenerator ] : Ran out of input events so run will be aborted!" << std::endl;
             G4RunManager::GetRunManager()->AbortRun(true);
             anEvent->SetEventAborted();
         }
         delete lheEvent;
     }
References LOG::endl, LHEParticle::getIDUP(), LHEParticle::getISTUP(), LHEParticle::getMother(), LHEEvent::getParticles(), LHEParticle::getPUP(), LHEParticle::getVTIMUP(), LHEEvent::getXWGTUP(), LHEPrimaryGenerator::reader_, and LHEReader::readNextEvent().
Referenced by LHEEventSource::generate().
Member Data Documentation
reader_
LHEReader* reader_ private
The LHE reader with the event data.
Definition at line 48 of file LHEPrimaryGenerator.hh.
Referenced by LHEPrimaryGenerator::GeneratePrimaryVertex(), and LHEPrimaryGenerator::~LHEPrimaryGenerator().
The documentation for this class was generated from the following files:
LHEPrimaryGenerator.hh
LHEPrimaryGenerator.cc