SLIC: RunAction Class Reference
RunAction Class Reference
Implementation of G4UserRunAction.
#include <RunAction.hh>
Public Member Functions
RunAction ()
~RunAction ()
void BeginOfRunAction (const G4Run *aRun)
void EndOfRunAction (const G4Run *aRun)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from PluginManagerAccessor
PluginManager * getPluginManager ()
void setPluginManager (PluginManager *pluginManager)
Private Member Functions
void startRunTimer ()
void stopRunTimer ()
Private Attributes
G4Timer m_runTimer
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Protected Attributes inherited from PluginManagerAccessor
PluginManager * m_pluginManager
Detailed Description
Implementation of G4UserRunAction.
Definition at line 18 of file RunAction.hh.
Constructor & Destructor Documentation
RunAction()
RunAction ()
Class constructor.
Definition at line 15 of file RunAction.cc.
~RunAction()
~RunAction ()
Class destructor.
Definition at line 19 of file RunAction.cc.
Member Function Documentation
BeginOfRunAction()
void BeginOfRunAction (const G4Run * aRun)
Implementation of begin of run action.
Parameters
[in] aRun The G4Run that is starting.
Definition at line 22 of file RunAction.cc.
References PluginManager::beginRun(), Singleton< LcioManager >::instance(), Singleton< EventSourceManager >::instance(), PluginManagerAccessor::m_pluginManager, and RunAction::startRunTimer().
EndOfRunAction()
void EndOfRunAction (const G4Run * aRun)
Implementation of end of run action.
Parameters
[in] aRun The G4Run that is ending.
Definition at line 44 of file RunAction.cc.
References PluginManager::endRun(), Singleton< LcioManager >::instance(), Singleton< EventSourceManager >::instance(), PluginManagerAccessor::m_pluginManager, and RunAction::stopRunTimer().
startRunTimer()
void startRunTimer () private
Start the run timer.
Definition at line 63 of file RunAction.cc.
References LOG::done, Module::log(), RunAction::m_runTimer, and LOG::okay.
Referenced by RunAction::BeginOfRunAction().
stopRunTimer()
void stopRunTimer () private
Stop the run timer.
Definition at line 71 of file RunAction.cc.
References LOG::done, Module::log(), RunAction::m_runTimer, and LOG::okay.
Referenced by RunAction::EndOfRunAction().
Member Data Documentation
m_runTimer
G4Timer m_runTimer private
Print the beginning of run message.
Parameters
[in] aRun The G4Run that is starting. Print the end of run message.
[in] aRun The G4Run that is ending.
Definition at line 72 of file RunAction.hh.
Referenced by RunAction::startRunTimer(), and RunAction::stopRunTimer().
The documentation for this class was generated from the following files:
RunAction.hh
RunAction.cc