SLIC: RunManager Class Reference
RunManager Class Reference
Extension of G4RunManager.
#include <RunManager.hh>
Public Member Functions
RunManager ()
virtual ~RunManager ()
void abortRun ()
void abortRun (int errorCode)
int getNumberOfEventsToRun ()
void Initialize ()
bool isRunAborted ()
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Static Public Member Functions
static RunManager * instance ()
Protected Member Functions
void BeamOn (G4int nevent, const char *macroFile=0, G4int nselect=-1)
void InitializeGeometry ()
void InitializePhysics ()
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Private Attributes
bool m_abortRun
int m_numberOfEventsToRun
PluginManager * m_pluginManager
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Detailed Description
Extension of G4RunManager.
Note
Initializes the default physics list setup using PhysicsListManager.
Definition at line 18 of file RunManager.hh.
Constructor & Destructor Documentation
RunManager()
RunManager ()
Class constructor.
Definition at line 25 of file RunManager.cc.
                        :
         Module("RunManager", false), m_abortRun(false) {
 }
~RunManager()
~RunManager () virtual
Class destructor.
Definition at line 29 of file RunManager.cc.
{
     delete m_pluginManager;
 }
References RunManager::m_pluginManager.
Member Function Documentation
abortRun() [1/2]
void abortRun () inline
Abort the current run.
Definition at line 45 of file RunManager.hh.
{
             //std::cout << "RunManager.abortRun - run will be aborted!!!" << std::endl;
             log() << LOG::fatal << "Aborting run." << LOG::done;
             m_abortRun = true;
             // Set return code to generic error but don't override if error is already set.
             if (SlicApplication::instance()->getReturnCode() == SlicApplication::OKAY) {
                 SlicApplication::instance()->setReturnCode(SlicApplication::UNKNOWN_ERROR);
             }
             G4RunManager::GetRunManager()->AbortRun(false);
         }
References LOG::done, LOG::fatal, Singleton< SlicApplication >::instance(), Module::log(), RunManager::m_abortRun, SlicApplication::OKAY, and SlicApplication::UNKNOWN_ERROR.
Referenced by RunManager::BeamOn(), EventSourceManager::beginRun(), RunManager::InitializeGeometry(), and LcioManager::openLcioFile().
abortRun() [2/2]
void abortRun (int errorCode) inline
Abort the current run with an error code.
Parameters
[in] errorCode The error code.
Definition at line 60 of file RunManager.hh.
{
             log() << LOG::fatal << LOG::name << LOG::sep << "Aborting run with return code: " << errorCode << LOG::done;
             m_abortRun = true;
             SlicApplication::instance()->setReturnCode(errorCode);
             G4RunManager::GetRunManager()->AbortRun(false);
         }
References LOG::done, LOG::fatal, Singleton< SlicApplication >::instance(), Module::log(), RunManager::m_abortRun, LOG::name, and LOG::sep.
BeamOn()
void BeamOn (G4int nevent, const char * macroFile = 0, G4int nselect = -1) protected
This method overrides the Geant4 implementation. The super class's method is called but wrapped in code for application control flow.
Parameters
[in] nevent The number of events to execute.
[in] macroFile A macro file to be executed after each event (not used by SLIC).
[in] nselect The number of events to wait before macro execution.
Definition at line 113 of file RunManager.cc.
{
     // Reset abort run flag.
     m_abortRun = false;
     // Attempt to initialize Geant4 if not in idle state.
     if (G4StateManager::GetStateManager()->GetCurrentState() != G4State_Idle) {
         this->Initialize();
     }
     // Check if a generator was setup.
     if (EventSourceManager::instance()->getCurrentSource() == 0) {
         log() << LOG::fatal << "No event generator was setup." << LOG::done;
         abortRun(SlicApplication::GENERATOR_NOT_SETUP);
     }
     // Check if run should be aborted due to initialization errors.
     if (!this->isRunAborted()) {
         // Run number of events that were requested.
         m_numberOfEventsToRun = n_event;
         G4RunManager::BeamOn(n_event, macroFile, n_select);
         // Print number of events that were actually generated.
         EventSourceManager* eventManager = EventSourceManager::instance();
         eventManager->printNumEventsGenerated();
         // Check if event underflow occurred where number of events provided was less than requested.
         int nEventsGenerated = eventManager->getNumEventsGenerated();
         if (nEventsGenerated < m_numberOfEventsToRun) {
             log() << LOG::warning << LOG::head << "Generated " << nEventsGenerated << " events but " << n_event << " were requested." << LOG::done;
             // Set event underflow error but do not override an existing return code.
             if (SlicApplication::instance()->getReturnCode() == SlicApplication::OKAY) {
                 SlicApplication::instance()->setReturnCode(SlicApplication::EVENT_UNDERFLOW);
             }
         }
     } else {
         log() << LOG::warning << LOG::head << "Run was aborted before G4 event loop was executed." << LOG::done;
     }
 }
References RunManager::abortRun(), LOG::done, SlicApplication::EVENT_UNDERFLOW, LOG::fatal, SlicApplication::GENERATOR_NOT_SETUP, EventSourceManager::getNumEventsGenerated(), LOG::head, RunManager::Initialize(), Singleton< EventSourceManager >::instance(), Singleton< SlicApplication >::instance(), RunManager::isRunAborted(), Module::log(), RunManager::m_abortRun, RunManager::m_numberOfEventsToRun, SlicApplication::OKAY, EventSourceManager::printNumEventsGenerated(), and LOG::warning.
getNumberOfEventsToRun()
int getNumberOfEventsToRun ()
Get the number of events to run.
Returns
The number of events to run.
Definition at line 154 of file RunManager.cc.
{
     return m_numberOfEventsToRun;
 }
References RunManager::m_numberOfEventsToRun.
Initialize()
void Initialize ()
Initialize this class.
Definition at line 33 of file RunManager.cc.
{
     // Init physics list.
     G4VUserPhysicsList* list = PhysicsListManager::instance()->createPhysicsList();
     G4RunManager::GetRunManager()->SetUserInitialization(list);
     // This makes sure that physics initialization occurs before other user actions.
     G4RunManager::Initialize();
     m_pluginManager = new PluginManager();
     new PluginMessenger(m_pluginManager);
     PrimaryGeneratorAction* genAction = new PrimaryGeneratorAction;
     RunAction* runAction = new RunAction;
     EventAction* eventAction = new EventAction;
     TrackingAction* trackingAction = new TrackingAction;
     SteppingAction* steppingAction = new SteppingAction;
     StackingAction* stackingAction = new StackingAction;
     genAction->setPluginManager(m_pluginManager);
     runAction->setPluginManager(m_pluginManager);
     eventAction->setPluginManager(m_pluginManager);
     trackingAction->setPluginManager(m_pluginManager);
     steppingAction->setPluginManager(m_pluginManager);
     stackingAction->setPluginManager(m_pluginManager);
     SetUserAction(genAction);
     SetUserAction(runAction);
     SetUserAction(eventAction);
     SetUserAction(trackingAction);
     SetUserAction(steppingAction);
     SetUserAction(stackingAction);
     // Initialize the event generation manager.
     EventSourceManager::instance();
     // Setup the default event source.
     EventSourceManager::instance()->setupEventSource();
     // Print list of registered modules.
 #ifdef SLIC_LOG
     ModuleRegistry::instance()->print();
 #endif
 }
References Singleton< PhysicsListManager >::instance(), Singleton< ModuleRegistry >::instance(), Singleton< EventSourceManager >::instance(), RunManager::m_pluginManager, and PluginManagerAccessor::setPluginManager().
Referenced by RunManager::BeamOn().
InitializeGeometry()
void InitializeGeometry () protected
Initialize the current geometry configuration.
Definition at line 101 of file RunManager.cc.
{
     // Was a valid LCDD setup given?
     if (!LCDDParser::instance()->isValidSetup()) {
         // Abort the run as the LCDD URL was probably not set.
         SlicApplication::instance()->setReturnCode(SlicApplication::INVALID_GEOMETRY_SETUP);
         this->abortRun();
     } else {
         // Initialize the geometry.
         G4RunManager::InitializeGeometry();
     }
 }
References RunManager::abortRun(), Singleton< SlicApplication >::instance(), and SlicApplication::INVALID_GEOMETRY_SETUP.
InitializePhysics()
void InitializePhysics () protected
Initialize the current physics configuration.
Definition at line 78 of file RunManager.cc.
{
     // Call the G4RunManager's intitialization method.
     G4RunManager::InitializePhysics();
     // Check if the LCDD subsystem got some limits.
     LCDDProcessor* lcdd = LCDDProcessor::instance();
     PhysicsListManager* pmgr = PhysicsListManager::instance();
     if (lcdd->getLimitSetsBegin() != lcdd->getLimitSetsEnd()) {
         std::cout << "enabling phys limits" << std::endl;
         pmgr->enableLimits(true);
     }
     // Enable physics limits, if necessary.
     if (pmgr->enableLimits()) {
         std::cout << "setting up user limits processes" << std::endl;
         pmgr->setupUserLimitsProcesses();
     }
     // Print out particle table.
     //G4ParticleTable::GetParticleTable()->DumpTable();
 }
References PhysicsListManager::enableLimits(), LOG::endl, Singleton< PhysicsListManager >::instance(), and PhysicsListManager::setupUserLimitsProcesses().
instance()
static RunManager* instance () inline static
Get the instance of RunManager.
Returns
The singleton RunManager.
Definition at line 38 of file RunManager.hh.
{
             return dynamic_cast<RunManager*>(G4RunManager::GetRunManager());
         }
Referenced by LcioManager::beginRun(), EventSourceManager::beginRun(), EventAction::EndOfEventAction(), LcioManager::endRun(), PrimaryGeneratorAction::GeneratePrimaries(), and LcioManager::openLcioFile().
isRunAborted()
bool isRunAborted ()
Return true if run has been aborted.
Returns
True if run has been aborted; false if not.
Definition at line 158 of file RunManager.cc.
{
     return m_abortRun;
 }
References RunManager::m_abortRun.
Referenced by RunManager::BeamOn().
Member Data Documentation
m_abortRun
bool m_abortRun private
Definition at line 108 of file RunManager.hh.
Referenced by RunManager::abortRun(), RunManager::BeamOn(), and RunManager::isRunAborted().
m_numberOfEventsToRun
int m_numberOfEventsToRun private
Definition at line 107 of file RunManager.hh.
Referenced by RunManager::BeamOn(), and RunManager::getNumberOfEventsToRun().
m_pluginManager
PluginManager* m_pluginManager private
Definition at line 109 of file RunManager.hh.
Referenced by RunManager::Initialize(), and RunManager::~RunManager().
The documentation for this class was generated from the following files:
RunManager.hh
RunManager.cc