SLIC: LcioMessenger Class Reference
LcioMessenger Class Reference
G4UIcommand class for LCIO commands.
#include <LcioMessenger.hh>
Public Member Functions
LcioMessenger (LcioManager *mgr)
virtual ~LcioMessenger ()
virtual void SetNewValue (G4UIcommand *command, G4String newValues)
Private Member Functions
void defineCommands ()
Private Attributes
G4UIcmdWithABool * _writeCompleteEventCmd
G4UIcommand * m_autonameCmd
G4UIcommand * m_fileExistsActionCmd
G4UIcommand * m_filenameCmd
G4UIdirectory * m_lcioDir
G4UIcommand * m_mcpFilenameCmd
LcioManager * m_mgr
G4UIcommand * m_pathCmd
G4UIcmdWithABool * m_printEventCmd
G4UIcommand * m_setLongFlagCmd
G4UIcommand * m_setPDGFlagCmd
G4UIcmdWithAnInteger * m_setRunNumberCmd
G4UIcommand * m_verboseCmd
Detailed Description
G4UIcommand class for LCIO commands.
Definition at line 20 of file LcioMessenger.hh.
Constructor & Destructor Documentation
LcioMessenger()
LcioMessenger (LcioManager * mgr)
Class constructor.
Definition at line 21 of file LcioMessenger.cc.
                                              :
         m_mgr(mgr) {
     defineCommands();
 }
References LcioMessenger::defineCommands().
~LcioMessenger()
~LcioMessenger () virtual
Class destructor.
Definition at line 26 of file LcioMessenger.cc.
{
     delete m_lcioDir;
     delete m_pathCmd;
     delete m_filenameCmd;
 }
References LcioMessenger::m_filenameCmd, LcioMessenger::m_lcioDir, and LcioMessenger::m_pathCmd.
Member Function Documentation
defineCommands()
void defineCommands () private
Define the commands handled by this messenger.
Definition at line 101 of file LcioMessenger.cc.
{
     G4UIparameter* p;
     // Lcio dir
     m_lcioDir = new G4UIdirectory("/lcio/");
     m_lcioDir->SetGuidance("LCIO output commands. [SLIC]");
     // path
     m_pathCmd = new G4UIcommand("/lcio/path", this);
     m_pathCmd->SetGuidance("Set Lcio output path.");
     p = new G4UIparameter("path", 's', false);
     m_pathCmd->SetParameter(p);
     // filename
     m_filenameCmd = new G4UIcommand("/lcio/filename", this);
     m_filenameCmd->SetGuidance("Set Lcio output filename.");
     p = new G4UIparameter("filename", 's', false);
     m_filenameCmd->SetParameter(p);
     // CHBIT_LONG
     m_setLongFlagCmd = new G4UIcommand("/lcio/longFlag", this);
     m_setLongFlagCmd->SetGuidance("Set CHBIT_LONG flag for hit positions in output (default = on).");
     p = new G4UIparameter("Value", 'b', true);
     m_setLongFlagCmd->SetParameter(p);
     m_setLongFlagCmd->AvailableForStates(G4State_PreInit);
     // CHBIT_PDG
     m_setPDGFlagCmd = new G4UIcommand("/lcio/PDGFlag", this);
     m_setPDGFlagCmd->SetGuidance("Set CHBIT_PDG flag for super-long output with all Mcp contribs (default is aggregated).");
     p = new G4UIparameter("Value", 'b', true);
     m_setPDGFlagCmd->SetParameter(p);
     m_setLongFlagCmd->AvailableForStates(G4State_PreInit);
     // fileExistsAction
     m_fileExistsActionCmd = new G4UIcommand("/lcio/fileExists", this);
     m_fileExistsActionCmd->SetGuidance("Set action when an Lcio output file exists: fail, overwrite/delete or append.");
     p = new G4UIparameter("mode", 's', false);
     m_fileExistsActionCmd->SetParameter(p);
     // set the starting run number
     m_setRunNumberCmd = new G4UIcmdWithAnInteger("/lcio/runNumber", this);
     m_setRunNumberCmd->SetGuidance("Set starting run number for LCIO event.");
     m_setRunNumberCmd->SetParameterName("RunNumber", false);
     // enable autonaming
     m_autonameCmd = new G4UIcommand("/lcio/autoname", this);
     m_autonameCmd->SetGuidance("Set autonaming parameters.");
     m_autonameCmd->SetGuidance("Valid autoname fields: application geometry event eventNumber run binary physics date geant4");
     p = new G4UIparameter("autoname", 's', true);
     m_autonameCmd->SetParameter(p);
     /* dumping of event data */
     m_printEventCmd = new G4UIcmdWithABool("/lcio/printEvent", this);
     m_printEventCmd->SetGuidance("Dump information about collections in the event");
     m_printEventCmd->SetParameterName("enable", true);
     m_printEventCmd->SetDefaultValue(true);
     _writeCompleteEventCmd = new G4UIcmdWithABool("/lcio/writeCompleteEvent", this);
     _writeCompleteEventCmd->SetGuidance("Write complete event to MCParticle output.");
     _writeCompleteEventCmd->SetParameterName("enable", true);
     _writeCompleteEventCmd->SetDefaultValue(true);
 }
References LcioMessenger::_writeCompleteEventCmd, LcioMessenger::m_autonameCmd, LcioMessenger::m_fileExistsActionCmd, LcioMessenger::m_filenameCmd, LcioMessenger::m_lcioDir, LcioMessenger::m_pathCmd, LcioMessenger::m_printEventCmd, LcioMessenger::m_setLongFlagCmd, LcioMessenger::m_setPDGFlagCmd, and LcioMessenger::m_setRunNumberCmd.
Referenced by LcioMessenger::LcioMessenger().
SetNewValue()
void SetNewValue (G4UIcommand * command, G4String newValues) virtual
Execute a macro command.
Parameters
[in] command The macro command.
[in] newValues The command arguments.
Definition at line 32 of file LcioMessenger.cc.
{
     std::istringstream is((const char*) newVals);
     std::string s;
     is >> s;
     // set output path
     if (cmd == m_pathCmd) {
         m_mgr->setPath(s);
     }
     // set filename
     else if (cmd == m_filenameCmd) {
         m_mgr->setFilename(s);
     }
     // fileExistsAction
     else if (cmd == m_fileExistsActionCmd) {
         m_mgr->setFileExistsAction(LcioManager::getFileExistsActionFromString(s));
     }
     // setRunNumber
     else if (cmd == m_setRunNumberCmd) {
         m_mgr->setRunNumber(StringUtil::toInt(s));
     }
     // autoname
     else if (cmd == m_autonameCmd) {
         std::vector<std::string> fields;
         StringUtil::split(newVals, " ", fields);
         m_mgr->setAutonameFields(fields);
     }
     /* dump event */
     else if (cmd == m_printEventCmd) {
         m_mgr->enableDumpEvent(m_printEventCmd->GetNewBoolValue(newVals.c_str()));
     }
     // flags
     else if (cmd == m_setLongFlagCmd || cmd == m_setPDGFlagCmd) {
         // no args then true
         bool flag_set = true;
         // get arg val if exists
         if (s != std::string("")) {
             flag_set = StringUtil::toBool(s);
         }
         LcioHitsCollectionBuilder* hcb = m_mgr->getHitsCollectionBuilder();
         if (hcb) {
             // CHBIT_LONG for positions in hits
             if (cmd == m_setLongFlagCmd) {
                 hcb->setLongFlag(flag_set);
             }
             // CHBIT_PDG for every PDG contribution in hits
             else if (cmd == m_setPDGFlagCmd) {
                 hcb->setPDGFlag(flag_set);
             }
         } else {
             G4Exception("", "", FatalException, "LcioHitsCollectionBuilder is null.");
         }
     } else if (cmd == _writeCompleteEventCmd) {
         G4bool writeCompleteEvent = StringUtil::toBool(s);
         LcioManager::instance()->setWriteCompleteEvent(writeCompleteEvent);
     }
     // bad command; shouldn't happen
     else {
         G4Exception("LcioMessenger::setNewValue()", "", JustWarning, "Unknown command.");
     }
     return;
 }
References LcioMessenger::_writeCompleteEventCmd, LcioManager::enableDumpEvent(), LcioManager::getFileExistsActionFromString(), LcioManager::getHitsCollectionBuilder(), Singleton< LcioManager >::instance(), LcioMessenger::m_autonameCmd, LcioMessenger::m_fileExistsActionCmd, LcioMessenger::m_filenameCmd, LcioMessenger::m_mgr, LcioMessenger::m_pathCmd, LcioMessenger::m_printEventCmd, LcioMessenger::m_setLongFlagCmd, LcioMessenger::m_setPDGFlagCmd, LcioMessenger::m_setRunNumberCmd, LcioManager::setAutonameFields(), LcioManager::setFileExistsAction(), LcioManager::setFilename(), LcioHitsCollectionBuilder::setLongFlag(), LcioManager::setPath(), LcioHitsCollectionBuilder::setPDGFlag(), and LcioManager::setRunNumber().
Member Data Documentation
_writeCompleteEventCmd
G4UIcmdWithABool* _writeCompleteEventCmd private
Definition at line 64 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), and LcioMessenger::SetNewValue().
m_autonameCmd
G4UIcommand* m_autonameCmd private
Definition at line 62 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), and LcioMessenger::SetNewValue().
m_fileExistsActionCmd
G4UIcommand* m_fileExistsActionCmd private
Definition at line 59 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), and LcioMessenger::SetNewValue().
m_filenameCmd
G4UIcommand* m_filenameCmd private
Definition at line 55 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), LcioMessenger::SetNewValue(), and LcioMessenger::~LcioMessenger().
m_lcioDir
G4UIdirectory* m_lcioDir private
Definition at line 53 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), and LcioMessenger::~LcioMessenger().
m_mcpFilenameCmd
G4UIcommand* m_mcpFilenameCmd private
Definition at line 60 of file LcioMessenger.hh.
m_mgr
LcioManager* m_mgr private
Definition at line 51 of file LcioMessenger.hh.
Referenced by LcioMessenger::SetNewValue().
m_pathCmd
G4UIcommand* m_pathCmd private
Definition at line 54 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), LcioMessenger::SetNewValue(), and LcioMessenger::~LcioMessenger().
m_printEventCmd
G4UIcmdWithABool* m_printEventCmd private
Definition at line 63 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), and LcioMessenger::SetNewValue().
m_setLongFlagCmd
G4UIcommand* m_setLongFlagCmd private
Definition at line 57 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), and LcioMessenger::SetNewValue().
m_setPDGFlagCmd
G4UIcommand* m_setPDGFlagCmd private
Definition at line 58 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), and LcioMessenger::SetNewValue().
m_setRunNumberCmd
G4UIcmdWithAnInteger* m_setRunNumberCmd private
Definition at line 61 of file LcioMessenger.hh.
Referenced by LcioMessenger::defineCommands(), and LcioMessenger::SetNewValue().
m_verboseCmd
G4UIcommand* m_verboseCmd private
Definition at line 56 of file LcioMessenger.hh.
The documentation for this class was generated from the following files:
LcioMessenger.hh
LcioMessenger.cc