SLIC: UserActionPluginMessenger Class Reference
UserActionPluginMessenger Class Reference
Messenger for sending macro commands to a UserActionPlugin.
#include <UserActionPluginMessenger.hh>
Public Member Functions
UserActionPluginMessenger (UserActionPlugin *userPlugin)
virtual ~UserActionPluginMessenger ()
const std::string & getPath ()
UserActionPlugin * getPlugin ()
void SetNewValue (G4UIcommand *command, G4String newValue)
Private Attributes
G4UIdirectory * pluginDir_
UserActionPlugin * userPlugin_
G4UIcommand * verboseCmd_
Detailed Description
Messenger for sending macro commands to a UserActionPlugin.
Note
By default, this class creates a directory for the plugin and provides a command for setting of the verbose level. Users can override this class to provide additional commands for their specific plugins.
Definition at line 29 of file UserActionPluginMessenger.hh.
Constructor & Destructor Documentation
UserActionPluginMessenger()
UserActionPluginMessenger (UserActionPlugin * userPlugin)
Class constructor.
Parameters
userPlugin The associated UserActionPlugin.
Definition at line 5 of file UserActionPluginMessenger.cc.
                                                                                  :
         userPlugin_(userPlugin) {
     pluginDir_ = new G4UIdirectory(std::string("/slic/plugins/" + userPlugin->getName() + "/").c_str());
     pluginDir_->SetGuidance(std::string("Commands for the sim plugin " + userPlugin->getName()).c_str());
     verboseCmd_ = new G4UIcommand(std::string(getPath() + "verbose").c_str(), this);
     G4UIparameter* verbose = new G4UIparameter("verboseLevel", 'i', false);
     verboseCmd_->SetParameter(verbose);
     verboseCmd_->SetGuidance("Set the verbosity level of the sim plugin (1-4).");
     verboseCmd_->AvailableForStates(G4ApplicationState::G4State_PreInit, G4ApplicationState::G4State_Idle);
 }
References UserActionPlugin::getName(), UserActionPluginMessenger::getPath(), UserActionPluginMessenger::pluginDir_, LOG::verbose, and UserActionPluginMessenger::verboseCmd_.
~UserActionPluginMessenger()
virtual ~UserActionPluginMessenger () inline virtual
Class destructor.
Definition at line 42 of file UserActionPluginMessenger.hh.
{
             delete verboseCmd_;
             delete pluginDir_;
         }
References UserActionPluginMessenger::pluginDir_, and UserActionPluginMessenger::verboseCmd_.
Member Function Documentation
getPath()
const std::string& getPath () inline
Get the command path (plugin's macro directory).
Returns
The command path.
Definition at line 58 of file UserActionPluginMessenger.hh.
{
             return pluginDir_->GetCommandPath();
         }
References UserActionPluginMessenger::pluginDir_.
Referenced by UserActionPluginMessenger::UserActionPluginMessenger().
getPlugin()
UserActionPlugin* getPlugin () inline
Get the associated UserActionPlugin.
Returns
The associated UserActionPlugin.
Definition at line 66 of file UserActionPluginMessenger.hh.
{
             return userPlugin_;
         }
References UserActionPluginMessenger::userPlugin_.
SetNewValue()
void SetNewValue (G4UIcommand * command, G4String newValue)
Process the macro command.
Parameters
[in] command The macro command.
[in] newValue The argument values.
Definition at line 18 of file UserActionPluginMessenger.cc.
{
     if (command == verboseCmd_) {
         userPlugin_->setVerboseLevel(std::atoi(newValue));
         std::cout << userPlugin_->getName() << " verbose set to " << userPlugin_->getVerboseLevel() << std::endl;
     }
 }
References LOG::endl, UserActionPlugin::getName(), UserActionPlugin::getVerboseLevel(), UserActionPlugin::setVerboseLevel(), UserActionPluginMessenger::userPlugin_, and UserActionPluginMessenger::verboseCmd_.
Member Data Documentation
pluginDir_
G4UIdirectory* pluginDir_ private
The plugin's command directory.
Definition at line 80 of file UserActionPluginMessenger.hh.
Referenced by UserActionPluginMessenger::getPath(), UserActionPluginMessenger::UserActionPluginMessenger(), and UserActionPluginMessenger::~UserActionPluginMessenger().
userPlugin_
UserActionPlugin* userPlugin_ private
The associated UserActionPligin.
Definition at line 75 of file UserActionPluginMessenger.hh.
Referenced by UserActionPluginMessenger::getPlugin(), and UserActionPluginMessenger::SetNewValue().
verboseCmd_
G4UIcommand* verboseCmd_ private
The command for setting verbose level.
Definition at line 85 of file UserActionPluginMessenger.hh.
Referenced by UserActionPluginMessenger::SetNewValue(), UserActionPluginMessenger::UserActionPluginMessenger(), and UserActionPluginMessenger::~UserActionPluginMessenger().
The documentation for this class was generated from the following files:
UserActionPluginMessenger.hh
UserActionPluginMessenger.cc