SLIC: UserTrackInformation Class Reference
UserTrackInformation Class Reference
The implementation of the G4VUserTrackInformation class for storing track information within the event.
#include <UserTrackInformation.hh>
Public Member Functions
UserTrackInformation (TrackSummary *aTrackSummary)
virtual ~UserTrackInformation ()
TrackSummary * getTrackSummary () const
void operator delete (void *trackInfo)
void * operator new (size_t)
void Print () const
void setHasTrackerHit ()
Private Attributes
TrackSummary * _trackSummary
Detailed Description
The implementation of the G4VUserTrackInformation class for storing track information within the event.
Definition at line 21 of file UserTrackInformation.hh.
Constructor & Destructor Documentation
UserTrackInformation()
UserTrackInformation (TrackSummary * aTrackSummary) inline
Class constructor.
Parameters
[in] aTrackSummary The TrackSummary attached to this information.
Definition at line 30 of file UserTrackInformation.hh.
References UserTrackInformation::_trackSummary.
~UserTrackInformation()
virtual ~UserTrackInformation () inline virtual
Class destructor.
Definition at line 37 of file UserTrackInformation.hh.
Member Function Documentation
getTrackSummary()
TrackSummary* getTrackSummary () const inline
Get the TrackSummary.
Returns
The TrackSummary.
Definition at line 54 of file UserTrackInformation.hh.
References UserTrackInformation::_trackSummary.
Referenced by TrackingAction::PostUserTrackingAction(), TrackingAction::PreUserTrackingAction(), and SteppingAction::UserSteppingAction().
operator delete()
void operator delete (void * trackInfo) inline
Delete operator.
Definition at line 83 of file UserTrackInformation.hh.
References slic::UserTrackInformationAllocator.
operator new()
void * operator new (size_t) inline
New operator.
Definition at line 77 of file UserTrackInformation.hh.
References slic::UserTrackInformationAllocator.
Print()
void Print () const inline
Print out the track information.
Todo:
Implement this method.
Definition at line 67 of file UserTrackInformation.hh.
setHasTrackerHit()
void setHasTrackerHit () inline
Definition at line 58 of file UserTrackInformation.hh.
References UserTrackInformation::_trackSummary, and TrackSummary::setHasTrackerHit().
Member Data Documentation
_trackSummary
TrackSummary* _trackSummary private
Definition at line 72 of file UserTrackInformation.hh.
Referenced by UserTrackInformation::getTrackSummary(), UserTrackInformation::setHasTrackerHit(), and UserTrackInformation::UserTrackInformation().
The documentation for this class was generated from the following file:
UserTrackInformation.hh