SLIC: EventSourceManager Class Reference
EventSourceManager Class Reference
This singleton is responsible for managing physics event sources.
#include <EventSourceManager.hh>
Public Types
enum ESourceType {
eUnknown = 0, eStdHep, eLCIO, eGPS,
eParticleGun, eLHE
}
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Member Functions
EventSourceManager ()
virtual ~EventSourceManager ()
void beginEvent (const G4Event *event)
void beginRun (const G4Run *run)
EventSource * createEventSource (ESourceType st)
void deleteCurrentEventSource ()
void dumpCurrentEvent ()
void enablePrintEvent (G4bool enable)
void endEvent (const G4Event *event)
void endRun (const G4Run *run)
void generate (G4Event *event)
void generateNextEvent (G4Event *evt)
EventSource * getCurrentSource ()
const std::string & getCurrentSourceName ()
ESourceType getCurrentSourceType ()
const std::string & getFilename ()
EventSourceWithInputFile * getFileSource ()
G4GeneralParticleSource * getGPS ()
double getLorentzTransformationAngle ()
int getNumEventsGenerated ()
G4ParticleGun * getParticleGun ()
unsigned int getSkipEvents ()
const std::string & getSourceNameFromType (ESourceType egt) const
ESourceType getSourceTypeFromFileExtension (const std::string &ext)
ESourceType getSourceTypeFromName (const std::string &name) const
G4double getZSmearing ()
void incrNumEventsGenerated ()
bool isEOF ()
bool isFileSource ()
bool isNewFilename ()
bool isNewSource ()
bool isNewSource (ESourceType est)
void printNumEventsGenerated ()
void resetCurrentEventSource ()
void setEventSource (EventSource *eventSource)
void setFilename (const std::string &fileName)
void setLorentzTransformationAngle (const G4double angle)
void setSkipEvents (unsigned int n)
void setSourceType (const std::string &s)
void setSourceType (ESourceType est)
void setupEventSource ()
void setupEventSource (const std::string &sourceType)
void setupEventSource (ESourceType sourceType)
void setZSmearing (const G4double zSmear)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void cleanup ()
bool deleteOnExit ()
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from Singleton< EventSourceManager >
Singleton ()
~Singleton ()
void release ()
Private Attributes
EventSource * m_currentEventSource
G4bool m_enablePrintEvent
bool m_fileIsSet
std::string m_filename
G4double m_lorentzTransformationAngle
GeneratorMessenger * m_messenger
bool m_newFilename
bool m_newSource
int m_ngen
unsigned int m_nskip
EventSource * m_particleGunSource
ESourceType m_sourceType
G4double m_zSmearingParam
Static Private Attributes
static std::string GPS = std::string("gps")
static std::string LCIO = std::string("lcio")
static std::string LHE = std::string("lhe")
static std::string PARTICLE_GUN = std::string("gun")
static std::string STDHEP = std::string("stdhep")
static std::string UNKNOWN = std::string("unknown")
Additional Inherited Members
Static Public Member Functions inherited from Singleton< EventSourceManager >
static EventSourceManager * instance ()
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
This singleton is responsible for managing physics event sources.
Definition at line 25 of file EventSourceManager.hh.
Member Enumeration Documentation
ESourceType
enum ESourceType
Enum for different source types.
Enumerator
eUnknown
eStdHep
eLCIO
eGPS
eParticleGun
eLHE
Definition at line 32 of file EventSourceManager.hh.
{
             eUnknown = 0, eStdHep, eLCIO, eGPS, eParticleGun, eLHE
         };
Constructor & Destructor Documentation
~EventSourceManager()
~EventSourceManager () virtual
Class destructor.
Definition at line 40 of file EventSourceManager.cc.
{
 }
EventSourceManager()
EventSourceManager ()
Class constructor.
Definition at line 26 of file EventSourceManager.cc.
                                        :
         Module("EventSourceManager"), m_currentEventSource(0), m_filename(""), m_fileIsSet(false),
         m_newFilename(false), m_ngen(0), m_nskip(0), m_newSource(true), m_sourceType(eUnknown),
         m_lorentzTransformationAngle(0.), m_zSmearingParam(0.), m_enablePrintEvent(false) {
     // messenger with generator command macro bindings
     m_messenger = new GeneratorMessenger();
     // Always create a ParticleGun generator.
     m_particleGunSource = new ParticleGunEventSource();
     log().setOutputLevel(LOG::always);
 }
References LOG::always, Module::log(), EventSourceManager::m_messenger, EventSourceManager::m_particleGunSource, and LogStream::setOutputLevel().
Member Function Documentation
beginEvent()
void beginEvent (const G4Event * event) virtual
Begin event hook.
Parameters
[in] event The Geant4 event.
Reimplemented from Module.
Definition at line 243 of file EventSourceManager.cc.
{
     // Start the event timer, as generation occurs before EventAction::BeginOfEventAction().
     EventAction::getEventAction()->startEventTimer();
     // Begin event action of current source.
     m_currentEventSource->beginEvent(anEvent);
 }
References EventSource::beginEvent(), EventAction::getEventAction(), EventSourceManager::m_currentEventSource, and EventAction::startEventTimer().
Referenced by PrimaryGeneratorAction::GeneratePrimaries().
beginRun()
void beginRun (const G4Run * run) virtual
Begin run hook.
Parameters
[in] run The Geant4 run.
Reimplemented from Module.
Definition at line 259 of file EventSourceManager.cc.
{
 #ifdef SLIC_LOG
     log() << LOG::debug << LOG::name << "beginRun" << LOG::done;
 #endif
     // Setup a new event source if neccessary.
     setupEventSource();
     // Call the beginRun() function of the current event source.
     if (m_currentEventSource != 0) {
         m_currentEventSource->beginRun(aRun);
         // Filename is now old so source won't reset.
         m_newFilename = false;
         // Reset event counter.
         m_ngen = 0;
     } else {
         log() << LOG::fatal << "No event generator was setup." << LOG::done;
         RunManager::instance()->abortRun(SlicApplication::GENERATOR_NOT_SETUP);
     }
 }
References RunManager::abortRun(), EventSource::beginRun(), LOG::debug, LOG::done, LOG::fatal, SlicApplication::GENERATOR_NOT_SETUP, RunManager::instance(), Module::log(), EventSourceManager::m_currentEventSource, EventSourceManager::m_newFilename, EventSourceManager::m_ngen, LOG::name, and EventSourceManager::setupEventSource().
createEventSource()
EventSource * createEventSource (ESourceType st)
Create an event source from a type.
Returns
The event source from the type.
Definition at line 184 of file EventSourceManager.cc.
{
     EventSource* src = 0;
     if (st == eLCIO) {
         src = new LcioEventSource(getFilename());
     } else if (st == eStdHep) {
         src = new StdHepEventSource(getFilename());
     } else if (st == eGPS) {
         src = new GPSEventSource();
     } else if (st == eParticleGun) {
         return m_particleGunSource;
     } else if (st == eLHE) {
         return new slic::LHEEventSource(getFilename());
     } else if (st == eUnknown) {
         log() << LOG::error << "The event source type <" << getSourceNameFromType(st) << " is flagged as unknown!" << LOG::done;
     } else {
         log() << LOG::error << "Invalid ESourceType." << LOG::done;
     }
     return src;
 }
References LOG::done, EventSourceManager::eGPS, EventSourceManager::eLCIO, EventSourceManager::eLHE, EventSourceManager::eParticleGun, LOG::error, EventSourceManager::eStdHep, EventSourceManager::eUnknown, EventSourceManager::getFilename(), EventSourceManager::getSourceNameFromType(), Module::log(), and EventSourceManager::m_particleGunSource.
Referenced by EventSourceManager::setupEventSource().
deleteCurrentEventSource()
void deleteCurrentEventSource ()
Delete the current event source.
Definition at line 177 of file EventSourceManager.cc.
{
     if (m_currentEventSource) {
         delete m_currentEventSource;
         m_currentEventSource = 0;
     }
 }
References EventSourceManager::m_currentEventSource.
Referenced by EventSourceManager::setEventSource(), and EventSourceManager::setupEventSource().
dumpCurrentEvent()
void dumpCurrentEvent ()
Dump the current event.
Definition at line 147 of file EventSourceManager.cc.
{
     m_currentEventSource->printCurrentEvent();
 }
References EventSourceManager::m_currentEventSource, and EventSource::printCurrentEvent().
enablePrintEvent()
void enablePrintEvent (G4bool enable) inline
Definition at line 293 of file EventSourceManager.hh.
{
             m_enablePrintEvent = enable;
         }
References EventSourceManager::m_enablePrintEvent.
Referenced by GeneratorMessenger::SetNewValue().
endEvent()
void endEvent (const G4Event * event) virtual
End event hook.
Parameters
[in] event The Geant4 event.
Reimplemented from Module.
Definition at line 251 of file EventSourceManager.cc.
{
     m_currentEventSource->endEvent(anEvent);
     if (m_enablePrintEvent) {
         m_currentEventSource->printCurrentEvent();
     }
 }
References EventSource::endEvent(), EventSourceManager::m_currentEventSource, EventSourceManager::m_enablePrintEvent, and EventSource::printCurrentEvent().
endRun()
void endRun (const G4Run * run) virtual
End run hook.
Parameters
[in] run The Geant4 run.
Reimplemented from Module.
Definition at line 290 of file EventSourceManager.cc.
{
     m_currentEventSource->endRun(aRun);
 }
References EventSource::endRun(), and EventSourceManager::m_currentEventSource.
generate()
void generate (G4Event * event)
Generate a Geant4 event.
Parameters
[in] The target Geant4 event.
Definition at line 163 of file EventSourceManager.cc.
{
     if (!isEOF()) {
         m_currentEventSource->generate(evt);
     } else {
         log() << LOG::error << "No more input events from file <" << m_filename << ">." << LOG::done;
     }
     incrNumEventsGenerated();
 }
References LOG::done, LOG::error, EventSource::generate(), EventSourceManager::incrNumEventsGenerated(), EventSourceManager::isEOF(), Module::log(), EventSourceManager::m_currentEventSource, and EventSourceManager::m_filename.
Referenced by EventSourceManager::generateNextEvent().
generateNextEvent()
void generateNextEvent (G4Event * evt)
Definition at line 351 of file EventSourceManager.cc.
{
     generate(evt);
 }
References EventSourceManager::generate().
Referenced by PrimaryGeneratorAction::GeneratePrimaries().
getCurrentSource()
EventSource * getCurrentSource ()
Get the current event source.
Returns
The current event source.
Definition at line 239 of file EventSourceManager.cc.
{
     return m_currentEventSource;
 }
References EventSourceManager::m_currentEventSource.
getCurrentSourceName()
const std::string & getCurrentSourceName ()
Get the name of the current source.
Returns
The name of the current source.
Definition at line 143 of file EventSourceManager.cc.
{
     return getSourceNameFromType(m_sourceType);
 }
References EventSourceManager::getSourceNameFromType(), and EventSourceManager::m_sourceType.
Referenced by EventSourceManager::setupEventSource().
getCurrentSourceType()
EventSourceManager::ESourceType getCurrentSourceType ()
Get the current source type.
Returns
The current source type.
Definition at line 139 of file EventSourceManager.cc.
{
     return m_sourceType;
 }
References EventSourceManager::m_sourceType.
getFilename()
const std::string & getFilename ()
Get the current file name.
Returns
The file name.
Definition at line 43 of file EventSourceManager.cc.
{
     return m_filename;
 }
References EventSourceManager::m_filename.
Referenced by EventSourceManager::createEventSource().
getFileSource()
EventSourceWithInputFile * getFileSource ()
Get the source with input file.
Returns
The source with an input file.
Definition at line 321 of file EventSourceManager.cc.
{
     EventSourceWithInputFile* esif = 0;
     if (isFileSource()) {
         esif = dynamic_cast<EventSourceWithInputFile*>(m_currentEventSource);
     }
     return esif;
 }
References EventSourceManager::isFileSource(), and EventSourceManager::m_currentEventSource.
getGPS()
G4GeneralParticleSource * getGPS ()
Get the GPS particle source.
Returns
The GPS particle source.
Definition at line 329 of file EventSourceManager.cc.
{
     GPSEventSource* src = dynamic_cast<GPSEventSource*>(m_currentEventSource);
     G4GeneralParticleSource* gps = 0;
     if (src) {
         gps = src->getGPS();
     }
     return gps;
 }
References GPSEventSource::getGPS(), and EventSourceManager::m_currentEventSource.
getLorentzTransformationAngle()
double getLorentzTransformationAngle () inline
Get the Lorentz transformation angle.
Returns
The Lorentz transformation angle.
Definition at line 266 of file EventSourceManager.hh.
{
             return m_lorentzTransformationAngle;
         }
References EventSourceManager::m_lorentzTransformationAngle.
getNumEventsGenerated()
int getNumEventsGenerated ()
Get the number of events generated.
Returns
The number of events generated.
Definition at line 155 of file EventSourceManager.cc.
{
     return m_ngen;
 }
References EventSourceManager::m_ngen.
Referenced by RunManager::BeamOn().
getParticleGun()
G4ParticleGun * getParticleGun ()
Get the particle gun source.
Returns
The particle gun source.
Definition at line 340 of file EventSourceManager.cc.
{
     ParticleGunEventSource* src = dynamic_cast<ParticleGunEventSource*>(m_currentEventSource);
     G4ParticleGun* gun = 0;
     if (src) {
         gun = src->getParticleGun();
     }
     return gun;
 }
References ParticleGunEventSource::getParticleGun(), and EventSourceManager::m_currentEventSource.
getSkipEvents()
unsigned int getSkipEvents ()
Get the number of events to skip.
Returns
The number of events to skip.
Definition at line 90 of file EventSourceManager.cc.
{
     return m_nskip;
 }
References EventSourceManager::m_nskip.
getSourceNameFromType()
const std::string & getSourceNameFromType (ESourceType egt) const
Get the source name string from a type.
Returns
egt The source name from the type.
Definition at line 103 of file EventSourceManager.cc.
{
     if (egt == eStdHep) {
         return STDHEP;
     } else if (egt == eLCIO) {
         return LCIO;
     } else if (egt == eGPS) {
         return GPS;
     } else if (egt == eParticleGun) {
         return PARTICLE_GUN;
     } else if (egt == eLHE) {
         return LHE;
     }
     return UNKNOWN;
 }
References EventSourceManager::eGPS, EventSourceManager::eLCIO, EventSourceManager::eLHE, EventSourceManager::eParticleGun, EventSourceManager::eStdHep, EventSourceManager::GPS, EventSourceManager::LCIO, EventSourceManager::LHE, EventSourceManager::PARTICLE_GUN, EventSourceManager::STDHEP, and EventSourceManager::UNKNOWN.
Referenced by EventSourceManager::createEventSource(), and EventSourceManager::getCurrentSourceName().
getSourceTypeFromFileExtension()
EventSourceManager::ESourceType getSourceTypeFromFileExtension (const std::string & ext)
Determine the source type from a file extension.
Parameters
[in] s The file extension.
Returns
The event source type.
Definition at line 62 of file EventSourceManager.cc.
{
     ESourceType est = eUnknown;
     /* LCIO file extension */
     if (fext == "slcio") {
         est = eLCIO;
     }
     /* StdHep files, which may have .xdr file ext */
     else if (fext == "stdhep" || fext == "xdr") {
         est = eStdHep;
     /* LHE files */
     } else if (fext == "lhe") {
         est = eLHE;
     } else {
         log() << LOG::error << "WARNING: File <" << m_filename << "> does not have a known file extension." << LOG::done;
     }
     return est;
 }
References LOG::done, EventSourceManager::eLCIO, EventSourceManager::eLHE, LOG::error, EventSourceManager::eStdHep, EventSourceManager::eUnknown, Module::log(), and EventSourceManager::m_filename.
Referenced by EventSourceManager::setFilename().
getSourceTypeFromName()
EventSourceManager::ESourceType getSourceTypeFromName (const std::string & name) const
Get the source type from a name.
Parameters
[in] name The name of the source.
Returns
The source type.
Definition at line 119 of file EventSourceManager.cc.
{
     std::string sl = StringUtil::toLower(s);
     ESourceType egt = eUnknown;
     if (sl == STDHEP) {
         egt = eStdHep;
     } else if (sl == GPS) {
         egt = eGPS;
     } else if (sl == PARTICLE_GUN) {
         egt = eParticleGun;
     } else if (sl == LCIO) {
         egt = eLCIO;
     } else if (sl == LHE) {
         egt = eLHE;
     }
     return egt;
 }
References EventSourceManager::eGPS, EventSourceManager::eLCIO, EventSourceManager::eLHE, EventSourceManager::eParticleGun, EventSourceManager::eStdHep, EventSourceManager::eUnknown, EventSourceManager::GPS, EventSourceManager::LCIO, EventSourceManager::LHE, EventSourceManager::PARTICLE_GUN, and EventSourceManager::STDHEP.
Referenced by EventSourceManager::setSourceType(), and EventSourceManager::setupEventSource().
getZSmearing()
G4double getZSmearing () inline
Get the Z smearing parameter.
Returns
The Z smearing parameter.
Definition at line 289 of file EventSourceManager.hh.
{
             return m_zSmearingParam;
         }
References EventSourceManager::m_zSmearingParam.
incrNumEventsGenerated()
void incrNumEventsGenerated ()
Increment the number of events generated.
Definition at line 159 of file EventSourceManager.cc.
{
     m_ngen += 1;
 }
References EventSourceManager::m_ngen.
Referenced by EventSourceManager::generate().
isEOF()
bool isEOF ()
Check if end of file has been reached for file-based sources.
Returns
True if end of file has been reached; false if not.
Definition at line 298 of file EventSourceManager.cc.
{
     bool eof = false;
     if (isFileSource()) {
         EventSourceWithInputFile* src = dynamic_cast<EventSourceWithInputFile*>(m_currentEventSource);
         if (src) {
             eof = src->isEOF();
         }
     }
     return eof;
 }
References EventSourceWithInputFile::isEOF(), EventSourceManager::isFileSource(), and EventSourceManager::m_currentEventSource.
Referenced by EventSourceManager::generate(), and PrimaryGeneratorAction::GeneratePrimaries().
isFileSource()
bool isFileSource ()
Check if source is file-based.
Returns
True if source is file-based; false if not.
Definition at line 294 of file EventSourceManager.cc.
{
     return (m_sourceType == eStdHep || m_sourceType == eLCIO);
 }
References EventSourceManager::eLCIO, EventSourceManager::eStdHep, and EventSourceManager::m_sourceType.
Referenced by EventSourceManager::getFileSource(), and EventSourceManager::isEOF().
isNewFilename()
bool isNewFilename ()
Check if the filename is different from the previous.
Returns
True if file name is new; false if not.
Definition at line 317 of file EventSourceManager.cc.
{
     return m_newFilename;
 }
References EventSourceManager::m_newFilename.
isNewSource() [1/2]
bool isNewSource ()
Check if this is a new source which needs to be setup.
Returns
True if source is new for the run; false if not.
Definition at line 309 of file EventSourceManager.cc.
{
     return m_newSource;
 }
References EventSourceManager::m_newSource.
Referenced by EventSourceManager::setupEventSource().
isNewSource() [2/2]
bool isNewSource (ESourceType est)
Check if this is a new source by type.
Returns
True if source type is new for the run; false if not.
Definition at line 313 of file EventSourceManager.cc.
{
     return (est != eUnknown && est != m_sourceType);
 }
References EventSourceManager::eUnknown, and EventSourceManager::m_sourceType.
printNumEventsGenerated()
void printNumEventsGenerated ()
Print the number of events generated.
Definition at line 151 of file EventSourceManager.cc.
{
     log() << LOG::okay << LOG::head << "Generated " << m_ngen << " events." << LOG::done;
 }
References LOG::done, LOG::head, Module::log(), EventSourceManager::m_ngen, and LOG::okay.
Referenced by RunManager::BeamOn(), and GeneratorMessenger::SetNewValue().
resetCurrentEventSource()
void resetCurrentEventSource ()
Reset the current event source.
Definition at line 81 of file EventSourceManager.cc.
{
     m_currentEventSource->reset();
     m_ngen = 0;
 }
References EventSourceManager::m_currentEventSource, EventSourceManager::m_ngen, and EventSource::reset().
Referenced by GeneratorMessenger::SetNewValue().
setEventSource()
void setEventSource (EventSource * eventSource)
Set the current event source.
Parameters
[in] eventSource The event source.
Definition at line 172 of file EventSourceManager.cc.
{
     deleteCurrentEventSource();
     m_currentEventSource = es;
 }
References EventSourceManager::deleteCurrentEventSource(), and EventSourceManager::m_currentEventSource.
setFilename()
void setFilename (const std::string & fileName)
Set the current file name.
Parameters
[in] fileName The file name.
Definition at line 47 of file EventSourceManager.cc.
{
     m_filename = f;
     m_fileIsSet = true;
     m_newFilename = true;
     /*  Get a file extension from the input file. */
     std::string fext = FileUtil::extension(m_filename);
     /* For known file extensions, get a source type. */
     ESourceType est = getSourceTypeFromFileExtension(fext);
     /* Setup a (possibly) new source. */
     setupEventSource(est);
 }
References FileUtil::extension(), EventSourceManager::getSourceTypeFromFileExtension(), EventSourceManager::m_fileIsSet, EventSourceManager::m_filename, EventSourceManager::m_newFilename, and EventSourceManager::setupEventSource().
Referenced by GeneratorMessenger::SetNewValue().
setLorentzTransformationAngle()
void setLorentzTransformationAngle (const G4double angle)
Set the Lorentz transformation angle.
Parameters
[in] angle The Lorentz transformation angle.
Definition at line 355 of file EventSourceManager.cc.
{
     m_lorentzTransformationAngle = lorentzTransformationAngle;
 #ifdef SLIC_LOG
     log() << LOG::always << "Set Lorentz transformation angle to " << G4BestUnit(m_lorentzTransformationAngle, "Angle") << LOG::done;
 #endif
 }
References LOG::always, LOG::done, Module::log(), and EventSourceManager::m_lorentzTransformationAngle.
setSkipEvents()
void setSkipEvents (unsigned int n)
Set the number of events to skip.
Parameters
[in] n The number of events to skip.
Definition at line 86 of file EventSourceManager.cc.
{
     m_nskip = s;
 }
References EventSourceManager::m_nskip.
Referenced by GeneratorMessenger::SetNewValue().
setSourceType() [1/2]
void setSourceType (const std::string & s)
Set the source type to use.
Parameters
[in] est The event source type string.
Definition at line 94 of file EventSourceManager.cc.
{
     setSourceType(getSourceTypeFromName(s));
 }
References EventSourceManager::getSourceTypeFromName(), and EventSourceManager::setSourceType().
setSourceType() [2/2]
void setSourceType (ESourceType est)
Set the source type to use.
Parameters
[in] est The event source type.
Definition at line 98 of file EventSourceManager.cc.
{
     m_sourceType = egt;
     m_newSource = true;
 }
References EventSourceManager::m_newSource, and EventSourceManager::m_sourceType.
Referenced by EventSourceManager::setSourceType().
setupEventSource() [1/3]
void setupEventSource ()
Setup the current event source.
Definition at line 283 of file EventSourceManager.cc.
{
     if (m_newSource) {
         m_currentEventSource = createEventSource(m_sourceType);
         m_newSource = false;
     }
 }
References EventSourceManager::createEventSource(), EventSourceManager::m_currentEventSource, EventSourceManager::m_newSource, and EventSourceManager::m_sourceType.
Referenced by EventSourceManager::beginRun(), EventSourceManager::setFilename(), GeneratorMessenger::SetNewValue(), and EventSourceManager::setupEventSource().
setupEventSource() [2/3]
void setupEventSource (const std::string & sourceType)
Setup an event source from a type string.
Parameters
[in] sourceType The event source type string.
Definition at line 230 of file EventSourceManager.cc.
{
     ESourceType st = getSourceTypeFromName(s);
     if (st != eUnknown) {
         setupEventSource(st);
     } else {
         log().error("The name <" + s + "> is not a valid event source.  New source was NOT created.");
     }
 }
References LogStream::error(), EventSourceManager::eUnknown, EventSourceManager::getSourceTypeFromName(), Module::log(), and EventSourceManager::setupEventSource().
setupEventSource() [3/3]
void setupEventSource (ESourceType sourceType)
Setup an event source from a type.
Parameters
[in] sourceType The event source type.
Definition at line 205 of file EventSourceManager.cc.
{
     // Is it a known source type?
     if (st != eUnknown) {
         // It is a new type of source?
         if (isNewSource(st)) {
             // Set new source type.
             m_sourceType = st;
             // Delete current source.
             deleteCurrentEventSource();
             // Create new source.
             m_currentEventSource = createEventSource(m_sourceType);
 #ifdef SLIC_LOG
             log().okay("Created event generator <" + getCurrentSourceName() + ">");
 #endif
         } else {
             log().warning("Type of new event source is same as old; keeping old source.");
         }
     } else {
         G4Exception("", "", JustWarning, "Event Source type is unknown.");
     }
 }
References EventSourceManager::createEventSource(), EventSourceManager::deleteCurrentEventSource(), EventSourceManager::eUnknown, EventSourceManager::getCurrentSourceName(), EventSourceManager::isNewSource(), Module::log(), EventSourceManager::m_currentEventSource, EventSourceManager::m_sourceType, LogStream::okay(), and LogStream::warning().
setZSmearing()
void setZSmearing (const G4double zSmear) inline
Set the Z smearing parameter.
Parameters
[in] zSmear The Z smearing parameter.
Definition at line 280 of file EventSourceManager.hh.
{
             m_zSmearingParam = zSmear;
             G4cout << "Set m_zSmearingParam = " << m_zSmearingParam << G4endl;
         }
References EventSourceManager::m_zSmearingParam.
Member Data Documentation
GPS
std::string GPS = std::string("gps") static private
Definition at line 329 of file EventSourceManager.hh.
Referenced by EventSourceManager::getSourceNameFromType(), and EventSourceManager::getSourceTypeFromName().
LCIO
std::string LCIO = std::string("lcio") static private
Definition at line 328 of file EventSourceManager.hh.
Referenced by EventSourceManager::getSourceNameFromType(), and EventSourceManager::getSourceTypeFromName().
LHE
std::string LHE = std::string("lhe") static private
Definition at line 331 of file EventSourceManager.hh.
Referenced by EventSourceManager::getSourceNameFromType(), and EventSourceManager::getSourceTypeFromName().
m_currentEventSource
EventSource* m_currentEventSource private
Definition at line 307 of file EventSourceManager.hh.
Referenced by EventSourceManager::beginEvent(), EventSourceManager::beginRun(), EventSourceManager::deleteCurrentEventSource(), EventSourceManager::dumpCurrentEvent(), EventSourceManager::endEvent(), EventSourceManager::endRun(), EventSourceManager::generate(), EventSourceManager::getCurrentSource(), EventSourceManager::getFileSource(), EventSourceManager::getGPS(), EventSourceManager::getParticleGun(), EventSourceManager::isEOF(), EventSourceManager::resetCurrentEventSource(), EventSourceManager::setEventSource(), and EventSourceManager::setupEventSource().
m_enablePrintEvent
G4bool m_enablePrintEvent private
Definition at line 343 of file EventSourceManager.hh.
Referenced by EventSourceManager::enablePrintEvent(), and EventSourceManager::endEvent().
m_fileIsSet
bool m_fileIsSet private
Definition at line 314 of file EventSourceManager.hh.
Referenced by EventSourceManager::setFilename().
m_filename
std::string m_filename private
Definition at line 313 of file EventSourceManager.hh.
Referenced by EventSourceManager::generate(), EventSourceManager::getFilename(), EventSourceManager::getSourceTypeFromFileExtension(), and EventSourceManager::setFilename().
m_lorentzTransformationAngle
G4double m_lorentzTransformationAngle private
Definition at line 338 of file EventSourceManager.hh.
Referenced by EventSourceManager::getLorentzTransformationAngle(), and EventSourceManager::setLorentzTransformationAngle().
m_messenger
GeneratorMessenger* m_messenger private
Definition at line 304 of file EventSourceManager.hh.
Referenced by EventSourceManager::EventSourceManager().
m_newFilename
bool m_newFilename private
Definition at line 315 of file EventSourceManager.hh.
Referenced by EventSourceManager::beginRun(), EventSourceManager::isNewFilename(), and EventSourceManager::setFilename().
m_newSource
bool m_newSource private
Definition at line 324 of file EventSourceManager.hh.
Referenced by EventSourceManager::isNewSource(), EventSourceManager::setSourceType(), and EventSourceManager::setupEventSource().
m_ngen
int m_ngen private
Definition at line 318 of file EventSourceManager.hh.
Referenced by EventSourceManager::beginRun(), EventSourceManager::getNumEventsGenerated(), EventSourceManager::incrNumEventsGenerated(), EventSourceManager::printNumEventsGenerated(), and EventSourceManager::resetCurrentEventSource().
m_nskip
unsigned int m_nskip private
Definition at line 321 of file EventSourceManager.hh.
Referenced by EventSourceManager::getSkipEvents(), and EventSourceManager::setSkipEvents().
m_particleGunSource
EventSource* m_particleGunSource private
Definition at line 310 of file EventSourceManager.hh.
Referenced by EventSourceManager::createEventSource(), and EventSourceManager::EventSourceManager().
m_sourceType
ESourceType m_sourceType private
Definition at line 335 of file EventSourceManager.hh.
Referenced by EventSourceManager::getCurrentSourceName(), EventSourceManager::getCurrentSourceType(), EventSourceManager::isFileSource(), EventSourceManager::isNewSource(), EventSourceManager::setSourceType(), and EventSourceManager::setupEventSource().
m_zSmearingParam
G4double m_zSmearingParam private
Definition at line 341 of file EventSourceManager.hh.
Referenced by EventSourceManager::getZSmearing(), and EventSourceManager::setZSmearing().
PARTICLE_GUN
std::string PARTICLE_GUN = std::string("gun") static private
Definition at line 330 of file EventSourceManager.hh.
Referenced by EventSourceManager::getSourceNameFromType(), and EventSourceManager::getSourceTypeFromName().
STDHEP
std::string STDHEP = std::string("stdhep") static private
Definition at line 327 of file EventSourceManager.hh.
Referenced by EventSourceManager::getSourceNameFromType(), and EventSourceManager::getSourceTypeFromName().
UNKNOWN
std::string UNKNOWN = std::string("unknown") static private
Definition at line 332 of file EventSourceManager.hh.
Referenced by EventSourceManager::getSourceNameFromType().
The documentation for this class was generated from the following files:
EventSourceManager.hh
EventSourceManager.cc