SLIC: LHEReader Class Reference
LHEReader Class Reference
Reads LHE event data into an LHEEvent object.
#include <LHEReader.hh>
Public Member Functions
LHEReader (const std::string &fileName)
virtual ~LHEReader ()
LHEEvent * readNextEvent ()
Private Attributes
std::ifstream ifs_
Detailed Description
Reads LHE event data into an LHEEvent object.
Definition at line 22 of file LHEReader.hh.
Constructor & Destructor Documentation
LHEReader()
LHEReader (const std::string & fileName)
Class constructor.
Parameters
fileName The input file name.
Definition at line 9 of file LHEReader.cc.
{
         std::cout << "Opening LHE file " << filename << std::endl;
         ifs_.open(filename.c_str(), std::ifstream::in);
     }
References LOG::endl, and LHEReader::ifs_.
~LHEReader()
~LHEReader () virtual
Class destructor.
Definition at line 14 of file LHEReader.cc.
{
         ifs_.close();
     }
References LHEReader::ifs_.
Member Function Documentation
readNextEvent()
LHEEvent * readNextEvent ()
Read the next event.
Returns
The next LHE event.
Definition at line 18 of file LHEReader.cc.
{
         std::string line;
         bool foundEventElement = false;
         while (getline(ifs_, line)) {
             if (line == "<event>") {
                 foundEventElement = true;
                 break;
             }
         }
         if (!foundEventElement) {
             std::cerr << "WARNING: No next <event> element was found by the LHE reader." << std::endl;
             return NULL;
         }
         getline(ifs_, line);
         LHEEvent* nextEvent = new LHEEvent(line);
         while (getline(ifs_, line)) {
             if (line == "</event>") {
                 break;
             }
             LHEParticle* particle = new LHEParticle(line);
             nextEvent->addParticle(particle);
         }
         const std::vector<LHEParticle*>& particles = nextEvent->getParticles();
         int particleIndex = 0;
         for (std::vector<LHEParticle*>::const_iterator it = particles.begin(); it != particles.end(); it++) {
             LHEParticle* particle = (*it);
             if (particle->getMOTHUP(0) != 0) {
                 int mother1 = particle->getMOTHUP(0);
                 int mother2 = particle->getMOTHUP(1);
                 if (mother1 > 0) {
                     particle->setMother(0, particles[mother1 - 1]);
                 }
                 if (mother2 > 0) {
                     particle->setMother(1, particles[mother2 - 1]);
                 }
             }
             ++particleIndex;
         }
         return nextEvent;
     }
References LHEEvent::addParticle(), LOG::endl, LHEParticle::getMOTHUP(), LHEEvent::getParticles(), LHEReader::ifs_, and LHEParticle::setMother().
Referenced by LHEPrimaryGenerator::GeneratePrimaryVertex().
Member Data Documentation
ifs_
std::ifstream ifs_ private
The input file stream.
Definition at line 48 of file LHEReader.hh.
Referenced by LHEReader::LHEReader(), LHEReader::readNextEvent(), and LHEReader::~LHEReader().
The documentation for this class was generated from the following files:
LHEReader.hh
LHEReader.cc