SLIC: LcioHitsCollectionBuilder Class Reference
LcioHitsCollectionBuilder Class Reference
Builds Lcio hits collections from G4/SLIC event data.
#include <LcioHitsCollectionBuilder.hh>
Public Member Functions
LcioHitsCollectionBuilder ()
virtual ~LcioHitsCollectionBuilder ()
EVENT::LCEvent * createHitCollectionsFromEvent (const G4Event *event, EVENT::LCEvent *lcioEvent)
bool getStoreMomentum ()
void setLongFlag (bool longFlag=true)
void setPDGFlag (bool pdgFlag=true)
void setStoreMomentum (bool storeMomentum=true)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Private Member Functions
void addParticleContributions (CalorimeterHit *calorimeterHit, IMPL::SimCalorimeterHitImpl *simCalorimeterHit)
void combineMcpHitContribs (const HitContributionList &allContributions, HitContributionList &combinedContributions)
IMPL::LCCollectionVec * createCalorimeterCollectionVec (G4VHitsCollection *hitCollection)
IMPL::LCCollectionVec * createCollectionVec (G4VHitsCollection *hitCollection, SensitiveDetector::EType sensitiveDetectorType)
IMPL::SimCalorimeterHitImpl * createHit (CalorimeterHit *calorimeterHit)
IMPL::SimTrackerHitImpl * createHit (TrackerHit *trackerHit)
void createHitCollections ()
IMPL::LCCollectionVec * createTrackerCollectionVec (G4VHitsCollection *hitCollection)
HitContribution * findHitContribution (int trackID, HitContributionList &contributions)
void saveHits (CalorimeterHitsCollection *calorimeterHits, IMPL::LCCollectionVec *collection)
void saveHits (TrackerHitsCollection *trackerHits, IMPL::LCCollectionVec *collection)
void setEndcapFlag (SensitiveDetector *sensitiveDetector)
void setFlagDefaults ()
Static Private Member Functions
static bool containsCollection (EVENT::LCEvent *event, const std::string &name)
Private Attributes
IMPL::LCFlagImpl m_calCollFlag
const G4Event * m_currentG4Event
EVENT::LCEvent * m_currentLCEvent
bool m_storeMomentum
IMPL::LCFlagImpl m_trkCollFlag
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
Builds Lcio hits collections from G4/SLIC event data.
Note
Makes use of LcioMcpManager for Mcp hit contributions.
Definition at line 32 of file LcioHitsCollectionBuilder.hh.
Constructor & Destructor Documentation
LcioHitsCollectionBuilder()
LcioHitsCollectionBuilder ()
Class constructor.
Definition at line 36 of file LcioHitsCollectionBuilder.cc.
                                                      :
         Module("LcioHitsCollectionBuilder"), m_storeMomentum(0) {
     // setup default coll flag for cal hits
     setFlagDefaults();
     // Set store momentum bit for TrackerHits
     m_trkCollFlag.setBit(LCIO::THBIT_MOMENTUM);
 }
References LcioHitsCollectionBuilder::m_trkCollFlag, and LcioHitsCollectionBuilder::setFlagDefaults().
~LcioHitsCollectionBuilder()
~LcioHitsCollectionBuilder () virtual
Class destructor.
Definition at line 46 of file LcioHitsCollectionBuilder.cc.
{
 }
Member Function Documentation
addParticleContributions()
void addParticleContributions (CalorimeterHit * calorimeterHit, IMPL::SimCalorimeterHitImpl * simCalorimeterHit) private
Copy MCParticle hit contributions from a CalorimeterHit to a SimCalorimeterHit.
Parameters
[in] calorimeterHit The CalorimeterHit with the contributions.
[out] simCalorimeterHit The SimCalorimeterHit to update.
Definition at line 299 of file LcioHitsCollectionBuilder.cc.
{
     // Create empty hit contrib list.
     HitContributionList contribs;
     // Use aggregation of contribs by track ID if CHBIT_PDG is not set.
     if (!m_calCollFlag.bitSet(LCIO::CHBIT_PDG)) {
         // Pass a ref to contrib list, which will get filled.
         combineMcpHitContribs(g4CalHit->getHitContributions(), contribs);
     }
     // Otherwise, use the complete list from the CalHit.
     else {
         contribs = g4CalHit->getHitContributions();
     }
     // Add contribs to the LCIO MCParticle.
     size_t ncontrib = 0;
     for (HitContributionList::const_iterator iter = contribs.begin(); iter != contribs.end(); iter++) {
         // This contrib.
         const HitContribution& contrib = (*iter);
         // Get the MCParticle pointer from the track ID.
         MCParticle* contribMcp = MCParticleManager::instance()->findMCParticle(contrib.getTrackID());
         if (contribMcp != 0) {
             // Add the MCParticle contribution to the hit.
             simCalHit->addMCParticleContribution(contribMcp, (float) (contrib.getEdep() / GeV), (float) (contrib.getGlobalTime()), contrib.getPDGID(), const_cast<float*>(contrib.getPosition()));
             ++ncontrib;
         }
         // Problem!  Contributing particle is missing from MCParticle list.
 #ifdef SLIC_LOG
         else
         {
             log() << LOG::error << "No MCParticle from track ID <" << contrib.getTrackID() << "> when processing SimCalorimeterHit" << LOG::endl;
         }
 #endif
     }
 #ifdef SLIC_LOG
     if ( ncontrib == 0 ) {
         log().error("No hit contributions for CalorimeterHit.");
     }
 #endif
 }
References LcioHitsCollectionBuilder::combineMcpHitContribs(), LOG::endl, LOG::error, LogStream::error(), Singleton< MCParticleManager >::instance(), Module::log(), and LcioHitsCollectionBuilder::m_calCollFlag.
Referenced by LcioHitsCollectionBuilder::createHit().
combineMcpHitContribs()
void combineMcpHitContribs (const HitContributionList & allContributions, HitContributionList & combinedContributions) private
Combine hit contributions using track IDs.
Parameters
[in] allContributions The full hit contribution list.
[out] combinedContributions The hit contributions grouped by track ID.
Definition at line 343 of file LcioHitsCollectionBuilder.cc.
{
     combinedContrib.clear();
     // iterate over long list (one entry for every hit)
     for (HitContributionList::const_iterator iter = longContrib.begin(); iter != longContrib.end(); iter++) {
         int trkId = (*iter).getTrackID();
         //log().debug("Combining hits on trk_id: " + StringUtil::toString( trk_id ) );
         // old track id in new combined list?
         HitContribution* trk_contrib = 0;
         if ((trk_contrib = findHitContribution((*iter).getTrackID(), combinedContrib))) {
             // Add to the energy deposition.
             trk_contrib->incrEdep((*iter).getEdep());
             // Set the minimum time.
             trk_contrib->setMinTime((*iter).getGlobalTime());
         }
         // no existing contrib
         else {
             // Create a new contribution.
             combinedContrib.push_back(HitContribution(trkId, (*iter).getEdep(), (*iter).getPDGID(), (*iter).getGlobalTime()));
         }
     }
 }
References LcioHitsCollectionBuilder::findHitContribution().
Referenced by LcioHitsCollectionBuilder::addParticleContributions().
containsCollection()
bool containsCollection (EVENT::LCEvent * event, const std::string & name) static private
Check if an event contains a named collection.
Parameters
[in] event The LCEvent to search.
[in] name The name of the collection.
Returns
True if the LCEvent contains a collection with given name; false if not.
Definition at line 417 of file LcioHitsCollectionBuilder.cc.
{
     for (std::vector<string>::const_iterator iter = event->getCollectionNames()->begin(); iter != event->getCollectionNames()->end(); iter++) {
         const string thisName = *iter;
         if (thisName.compare(collectionName) == 0) {
             return true;
         }
     }
     return false;
 }
Referenced by LcioHitsCollectionBuilder::createHitCollections().
createCalorimeterCollectionVec()
LCCollectionVec * createCalorimeterCollectionVec (G4VHitsCollection * hitCollection) private
Create an output collection of LCIO caloriemter hits.
Parameters
[in] The input CalorimeterHit collection.
Definition at line 157 of file LcioHitsCollectionBuilder.cc.
{
     // create Lcio cal coll
     LCCollectionVec* collVec = new LCCollectionVec(LCIO::SIMCALORIMETERHIT);
     // cast to G4 cal HC
     CalorimeterHitsCollection* calHits = dynamic_cast<CalorimeterHitsCollection*>(g4HC);
     // call overloaded save function for cal hits
     saveHits(calHits, collVec);
     // set cal flags
     collVec->setFlag(m_calCollFlag.getFlag());
     return collVec;
 }
References LcioHitsCollectionBuilder::m_calCollFlag, and LcioHitsCollectionBuilder::saveHits().
Referenced by LcioHitsCollectionBuilder::createCollectionVec().
createCollectionVec()
IMPL::LCCollectionVec * createCollectionVec (G4VHitsCollection * hitCollection, SensitiveDetector::EType sensitiveDetectorType) private
Create the LCCollectionVec for a given hits collection.
Parameters
[in] hitCollection The hit collection.
[in] sensitiveDetectorType The type of the sensitive detector (e.g. tracker or calorimeter).
Definition at line 120 of file LcioHitsCollectionBuilder.cc.
{
     // vec to create
     LCCollectionVec* collVec = 0;
     // cal hits
     if (SDtype == SensitiveDetector::eCalorimeter) {
         collVec = createCalorimeterCollectionVec(g4HC);
     }
     // tracker hits
     else if (SDtype == SensitiveDetector::eTracker) {
         collVec = createTrackerCollectionVec(g4HC);
     }
     // unknown type of hit
     else {
         G4Exception("", "", FatalException, "Unknown HC type.");
     }
     return collVec;
 }
References LcioHitsCollectionBuilder::createCalorimeterCollectionVec(), and LcioHitsCollectionBuilder::createTrackerCollectionVec().
Referenced by LcioHitsCollectionBuilder::createHitCollections().
createHit() [1/2]
IMPL::SimCalorimeterHitImpl * createHit (CalorimeterHit * calorimeterHit) private
Create a SimCalorimeterHit from a CalorimeterHit.
Parameters
[in] calorimeterHit The source CalorimeterHit.
Returns
The output SimCalorimeterHit.
Definition at line 218 of file LcioHitsCollectionBuilder.cc.
{
     SimCalorimeterHitImpl* simCalHit = new SimCalorimeterHitImpl();
     // set cellid from cal hit's id64
     const Id64bit& id64 = calHit->getId64bit();
     simCalHit->setCellID0(id64.getId0());
     simCalHit->setCellID1(id64.getId1());
     // position
     const G4ThreeVector hitPos = calHit->getPosition();
     float pos[3] = { (float)hitPos.x(), (float)hitPos.y(), (float)hitPos.z() };
     simCalHit->setPosition(pos);
     //  copy Mcp contrib info; energy is also incremented by contrib addition
     addParticleContributions(calHit, simCalHit);
     // compare edep of calHit with simHit when debugging
 //#ifdef SLIC_DEBUG
     const HitContributionList& contribs = calHit->getHitContributions();
     double totE = 0;
     for (HitContributionList::const_iterator iter = contribs.begin(); iter != contribs.end(); iter++) {
         totE += (*iter).getEdep();
     }
     // Set energy from total of individual contributions.
     //simCalHit->setEnergy(totE/GeV);
     //std::cout << "set totE = " << totE/GeV << std::endl;
     // sanity check so that new and old edeps must match
     //if (abs( totE/GeV - simCalHit->getEnergy() ) > ( 0.001 * totE ) )
     //{
     //    log() << LOG::debug << "g4 hit E: " << totE << LOG::done;
     //    log() << LOG::debug << "sim hit E: " << simCalHit->getEnergy() << LOG::done;
     //    G4Exception("", "", JustWarning, "LCIO simCalHit E != G4 CalHit E, within tolerance");
     //}
 //#endif
     return simCalHit;
 }
References LcioHitsCollectionBuilder::addParticleContributions().
Referenced by LcioHitsCollectionBuilder::saveHits().
createHit() [2/2]
IMPL::SimTrackerHitImpl * createHit (TrackerHit * trackerHit) private
Create a SimTrackerHit from a TrackerHit.
Parameters
[in] trackerHit The input TrackerHit.
Returns
The output SimTrackerHit.
Definition at line 259 of file LcioHitsCollectionBuilder.cc.
{
     SimTrackerHitImpl* simTrackerHit = new SimTrackerHitImpl();
     // position in mm
     const G4ThreeVector hitPos = trackerHit->getPosition();
     double pos[3] = { hitPos.x(), hitPos.y(), hitPos.z() };
     simTrackerHit->setPosition(pos);
     // momentum in GeV
     const G4ThreeVector& momentum = trackerHit->getMomentum();
     simTrackerHit->setMomentum(momentum.x() / GeV, momentum.y() / GeV, momentum.z() / GeV);
     // pathLength = distance between exit and entry points in mm
     simTrackerHit->setPathLength(trackerHit->getLength());
     // dEdx in GeV (LCIO units)
     float edep = trackerHit->getEdep();
     simTrackerHit->setEDep(edep / GeV);
     // time in NS
     float tEdep = trackerHit->getTdep();
     simTrackerHit->setTime(tEdep);
     // Cell ID.
     simTrackerHit->setCellID0(trackerHit->getId());
     // MCP using McpManager
     MCParticle* mcp = MCParticleManager::instance()->findMCParticle(trackerHit->getTrackID());
     if (!mcp) {
         log().error("No MCParticle found for trackID <" + StringUtil::toString(trackerHit->getTrackID()) + "> when processing SimTrackerHit");
     } else {
         simTrackerHit->setMCParticle(mcp);
     }
     return simTrackerHit;
 }
References LogStream::error(), Singleton< MCParticleManager >::instance(), and Module::log().
createHitCollections()
void createHitCollections () private
Definition at line 50 of file LcioHitsCollectionBuilder.cc.
{
     // fetch HCIDs
     std::vector<int> hcids = HitsCollectionUtil::getHCIDs();
     // fetch hit collection of event
     G4HCofThisEvent* HCE = m_currentG4Event->GetHCofThisEvent();
     // HC table
     G4HCtable* HCtbl = G4SDManager::GetSDMpointer()->GetHCtable();
     // HCID
     G4int hcid;
     LCCollectionVec* collVec = 0;
     // Loop over HC IDs.
     for (std::vector<int>::const_iterator iter = hcids.begin(); iter != hcids.end(); iter++) {
         hcid = *iter;
         // retrieve Sensitive Detector ptr
         SensitiveDetector *SD = static_cast<SensitiveDetector*>(G4SDManager::GetSDMpointer()->FindSensitiveDetector(HCtbl->GetSDname(hcid)));
         // Get hits collections from SD.
         for (int i = 0; i < SD->getNumberOfHitsCollections(); i++) {
             if (SD->getHCID(i) == hcid) {
                 G4VHitsCollection* HC = HCE->GetHC(hcid);
                 // add a LCCollectionVec if got a HC
                 if (HC) {
                     // set LCIO endcap bit in the flag (i.e. CHBIT_BARREL ) according to SDs setting
                     setEndcapFlag(SD);
                     // create collection vector based on type of SD
                     collVec = createCollectionVec(HC, SD->getType());
                     // Store the cellID description into the LCIO::cellIDEncoding parameter in the collection.
                     if (SD->getIdSpec()) {
                         std::string id = SD->getIdSpec()->getFieldDescription();
                         collVec->parameters().setValue(LCIO::CellIDEncoding, id);
                     }
                     // Check for existing collection.
                     if (containsCollection(m_currentLCEvent, HC->GetName())) {
                         // Update existing collection.
                         // TODO: Check for matching id scheme and flags!
                         LCCollectionVec * collection = (LCCollectionVec*) m_currentLCEvent->getCollection(HC->GetName());
                         collection->insert(collection->begin(), collVec->begin(), collVec->end());
                     }
                     // No collection found.
                     else {
                         // Add new collection vector to LCEvent.
                         m_currentLCEvent->addCollection(collVec, HC->GetName());
 #ifdef SLIC_LOG
                         //log() << LOG::always << HC->GetName() << " has " << collVec->size() << " hits" << LOG::done;
 #endif
                     }
                 }
                 else {
                     G4Exception("LcioHitsCollectionBuilder::createHitCollections()", "", FatalException, "No collection found for Hits Collection ID");
                 }
             }
         }
     }
 }
References LcioHitsCollectionBuilder::containsCollection(), LcioHitsCollectionBuilder::createCollectionVec(), HitsCollectionUtil::getHCIDs(), LcioHitsCollectionBuilder::m_currentG4Event, LcioHitsCollectionBuilder::m_currentLCEvent, and LcioHitsCollectionBuilder::setEndcapFlag().
Referenced by LcioHitsCollectionBuilder::createHitCollectionsFromEvent().
createHitCollectionsFromEvent()
EVENT::LCEvent * createHitCollectionsFromEvent (const G4Event * event, EVENT::LCEvent * lcioEvent)
Setup instance variables and then create the LCIO output hits collections from the Geant4 sensitive detector data for the event.
Parameters
[in] event The Geant4 event.
[in] lcioEvent The LCIO target event.
Returns
The LCIO event with the hits collections.
Definition at line 381 of file LcioHitsCollectionBuilder.cc.
{
     // set instance vars
     m_currentG4Event = g4evt;
     m_currentLCEvent = lcevt;
     // call real HC creation function
     createHitCollections();
     // return evt pntr, which is same as input
     return m_currentLCEvent;
 }
References LcioHitsCollectionBuilder::createHitCollections(), LcioHitsCollectionBuilder::m_currentG4Event, and LcioHitsCollectionBuilder::m_currentLCEvent.
Referenced by LcioManager::createHitsCollections().
createTrackerCollectionVec()
LCCollectionVec * createTrackerCollectionVec (G4VHitsCollection * hitCollection) private
Create an output collection of LCIO tracker hits.
Parameters
[in] The input TrackerHit collection.
Definition at line 141 of file LcioHitsCollectionBuilder.cc.
{
     // create Lcio tracker coll
     LCCollectionVec* collVec = new LCCollectionVec(LCIO::SIMTRACKERHIT);
     // cast to G4 trk HC
     TrackerHitsCollection* trkHits = dynamic_cast<TrackerHitsCollection*>(g4HC);
     // call overloaded save function for trk hits
     saveHits(trkHits, collVec);
     // set trk flags
     collVec->setFlag(m_trkCollFlag.getFlag());
     return collVec;
 }
References LcioHitsCollectionBuilder::m_trkCollFlag, and LcioHitsCollectionBuilder::saveHits().
Referenced by LcioHitsCollectionBuilder::createCollectionVec().
findHitContribution()
HitContribution * findHitContribution (int trackID, HitContributionList & contributions) private
Find a single hit contribution by track ID within the combined list.
Parameters
[in] trackID The track ID.
[in] contributions The hit contribution list to search.
Returns
The matching HitContribution or null if there are none.
Definition at line 369 of file LcioHitsCollectionBuilder.cc.
{
     HitContribution* c = 0;
     for (HitContributionList::iterator iter = contribs.begin(); iter != contribs.end(); iter++) {
         if ((*iter).getTrackID() == trk_id) {
             c = &(*iter);
             break;
         }
     }
     return c;
 }
Referenced by LcioHitsCollectionBuilder::combineMcpHitContribs().
getStoreMomentum()
bool getStoreMomentum () inline
Get whether to store momentum in output step contributions.
Returns
True if momentum should be stored; false if not.
Definition at line 80 of file LcioHitsCollectionBuilder.hh.
{
             return m_storeMomentum;
         }
References LcioHitsCollectionBuilder::m_storeMomentum.
saveHits() [1/2]
void saveHits (CalorimeterHitsCollection * calorimeterHits, IMPL::LCCollectionVec * collection) private
Save the CalorimeterHits into the output LCIO collection.
Parameters
[in]
Definition at line 200 of file LcioHitsCollectionBuilder.cc.
{
     size_t s = calHits->GetSize();
     for (size_t i = 0; i < s; i++) {
         CalorimeterHit* calHit = static_cast<CalorimeterHit*>(calHits->GetHit(i));
         lcioColl->push_back(createHit(calHit));
     }
 }
References LcioHitsCollectionBuilder::createHit().
Referenced by LcioHitsCollectionBuilder::createCalorimeterCollectionVec(), and LcioHitsCollectionBuilder::createTrackerCollectionVec().
saveHits() [2/2]
void saveHits (TrackerHitsCollection * trackerHits, IMPL::LCCollectionVec * collection) private
Save TrackerHits to a collection.
Parameters
[in] trackerHits The TrackerHits to add.
[out] collection The target collection.
Definition at line 209 of file LcioHitsCollectionBuilder.cc.
{
     size_t s = trkHits->GetSize();
     for (size_t i = 0; i < s; i++) {
         TrackerHit* trkHit = static_cast<TrackerHit*>(trkHits->GetHit(i));
         lcioColl->push_back(createHit(trkHit));
     }
 }
References LcioHitsCollectionBuilder::createHit().
setEndcapFlag()
void setEndcapFlag (SensitiveDetector * sensitiveDetector) private
Set the endcap flag depending on the type of the sensitive detector.
Parameters
[in] sensitiveDetector The SensitiveDetector.
Definition at line 178 of file LcioHitsCollectionBuilder.cc.
{
     bool ec_flag = g4sd->getEndcapFlag();
     // set for cal
     if (g4sd->getType() == SensitiveDetector::eCalorimeter) {
         if (ec_flag) {
             m_calCollFlag.unsetBit(LCIO::CHBIT_BARREL);
         } else {
             m_calCollFlag.setBit(LCIO::CHBIT_BARREL);
         }
     }
     // set for trk
     else if (g4sd->getType() == SensitiveDetector::eTracker) {
         if (ec_flag) {
             m_trkCollFlag.unsetBit(LCIO::THBIT_BARREL);
         } else {
             m_trkCollFlag.setBit(LCIO::THBIT_BARREL);
         }
     }
 }
References LcioHitsCollectionBuilder::m_calCollFlag, and LcioHitsCollectionBuilder::m_trkCollFlag.
Referenced by LcioHitsCollectionBuilder::createHitCollections().
setFlagDefaults()
void setFlagDefaults () private
Set default CalorimeterHit flag settings. This is called from this classe's constructor.
Definition at line 173 of file LcioHitsCollectionBuilder.cc.
{
     m_calCollFlag.setBit(LCIO::CHBIT_LONG);
     m_calCollFlag.setBit(LCIO::CHBIT_ID1);
 }
References LcioHitsCollectionBuilder::m_calCollFlag.
Referenced by LcioHitsCollectionBuilder::LcioHitsCollectionBuilder().
setLongFlag()
void setLongFlag (bool longFlag = true)
Set to true in order to include positions in output hits.
Parameters
[in] longFlag The setting of the long flag.
Definition at line 393 of file LcioHitsCollectionBuilder.cc.
{
     if (setting) {
         m_calCollFlag.setBit(LCIO::CHBIT_LONG);
     } else {
         m_calCollFlag.unsetBit(LCIO::CHBIT_LONG);
     }
 #ifdef SLIC_LOG
     log().verbose("Set CHBIT_LONG: " + StringUtil::toString( setting ) );
 #endif
 }
References Module::log(), LcioHitsCollectionBuilder::m_calCollFlag, and LogStream::verbose().
Referenced by LcioMessenger::SetNewValue().
setPDGFlag()
void setPDGFlag (bool pdgFlag = true)
Set to true in order to include all step contributions in output hits rather than aggregating them together by PDG ID.
Parameters
[in] pdgFlag The setting of the PDG flag.
Definition at line 405 of file LcioHitsCollectionBuilder.cc.
{
     if (setting) {
         m_calCollFlag.setBit(LCIO::CHBIT_PDG);
     } else {
         m_calCollFlag.setBit(LCIO::CHBIT_PDG);
     }
 #ifdef SLIC_LOG
     log().verbose("Set CHBIT_PDG: " + StringUtil::toString( setting ) );
 #endif
 }
References Module::log(), LcioHitsCollectionBuilder::m_calCollFlag, and LogStream::verbose().
Referenced by LcioMessenger::SetNewValue().
setStoreMomentum()
void setStoreMomentum (bool storeMomentum = true) inline
Set to true in order to store momentum in output step contributions.
Parameters
[in] storeMomentum The store momentum setting.
Definition at line 72 of file LcioHitsCollectionBuilder.hh.
{
             m_storeMomentum = storeMomentum;
         }
References LcioHitsCollectionBuilder::m_storeMomentum.
Referenced by LcioManager::setStoreMomentum().
Member Data Documentation
m_calCollFlag
IMPL::LCFlagImpl m_calCollFlag private
Definition at line 190 of file LcioHitsCollectionBuilder.hh.
Referenced by LcioHitsCollectionBuilder::addParticleContributions(), LcioHitsCollectionBuilder::createCalorimeterCollectionVec(), LcioHitsCollectionBuilder::setEndcapFlag(), LcioHitsCollectionBuilder::setFlagDefaults(), LcioHitsCollectionBuilder::setLongFlag(), and LcioHitsCollectionBuilder::setPDGFlag().
m_currentG4Event
const G4Event* m_currentG4Event private
Definition at line 186 of file LcioHitsCollectionBuilder.hh.
Referenced by LcioHitsCollectionBuilder::createHitCollections(), and LcioHitsCollectionBuilder::createHitCollectionsFromEvent().
m_currentLCEvent
EVENT::LCEvent* m_currentLCEvent private
Definition at line 183 of file LcioHitsCollectionBuilder.hh.
Referenced by LcioHitsCollectionBuilder::createHitCollections(), and LcioHitsCollectionBuilder::createHitCollectionsFromEvent().
m_storeMomentum
bool m_storeMomentum private
Definition at line 193 of file LcioHitsCollectionBuilder.hh.
Referenced by LcioHitsCollectionBuilder::getStoreMomentum(), and LcioHitsCollectionBuilder::setStoreMomentum().
m_trkCollFlag
IMPL::LCFlagImpl m_trkCollFlag private
Definition at line 189 of file LcioHitsCollectionBuilder.hh.
Referenced by LcioHitsCollectionBuilder::createTrackerCollectionVec(), LcioHitsCollectionBuilder::LcioHitsCollectionBuilder(), and LcioHitsCollectionBuilder::setEndcapFlag().
The documentation for this class was generated from the following files:
LcioHitsCollectionBuilder.hh
LcioHitsCollectionBuilder.cc