SLIC: TrackSummary Class Reference
TrackSummary Class Reference
Container for all information from G4Track that may be persisted to MCParticle output collection.
#include <TrackSummary.hh>
Public Member Functions
TrackSummary (const G4Track *track, G4bool toBeSaved, G4bool backScattering=false)
virtual ~TrackSummary ()
void buildMCParticle ()
TrackSummary * findParent () const
G4bool getBackScattering () const
G4double getCharge () const
G4ThreeVector getEndPoint () const
G4double getEnergy () const
G4int getHepEvtStatus () const
G4double getMass () const
MCParticleImpl * getMCParticle ()
G4ThreeVector getMomentum () const
TrackSummary * getParent () const
G4int getParentID () const
G4int getPDG () const
G4int getSimulatorStatus () const
G4bool getToBeSaved () const
G4int getTrackID () const
G4double getTrackLength () const
const G4ThreeVector & getVertex () const
void operator delete (void *)
void * operator new (size_t)
void setBackScattering ()
void setHasTrackerHit ()
void setMCParticle (MCParticleImpl *mcp)
void setParentToBeSaved ()
void setToBeSaved ()
void update (const G4Track *track)
Private Attributes
G4bool _backScattering
G4double _charge
G4ThreeVector _endPoint
G4double _energy
G4double _globalTime
G4bool _hasTrackerHit
G4int _hepEvtStatus
G4double _mass
MCParticleImpl * _mcparticle
G4bool _mcParticleIsUpToDate
G4ThreeVector _momentum
G4ThreeVector _momentumAtEndpoint
TrackSummary * _parent
G4int _parentTrackID
G4int _PDG
std::bitset< 32 > _simstatus
G4bool _toBeSaved
G4int _trackID
G4double _trackLength
G4ThreeVector _vertex
Static Private Attributes
static TrackManager * m_trackManager = TrackManager::instance()
Detailed Description
Container for all information from G4Track that may be persisted to MCParticle output collection.
Definition at line 33 of file TrackSummary.hh.
Constructor & Destructor Documentation
TrackSummary()
TrackSummary (const G4Track * track, G4bool toBeSaved, G4bool backScattering = false)
Class constructor.
Definition at line 25 of file TrackSummary.cc.
                                                                                         :
         _parent(NULL), _toBeSaved(toBeSaved), _backScattering(backScattering), _mcparticle(NULL), _hasTrackerHit(false), _mcParticleIsUpToDate(false), _trackLength(0), _hepEvtStatus(0) {
     /* Set information of track that is immutable. */
     _charge = track->GetDefinition()->GetPDGCharge();
     _mass = track->GetDynamicParticle()->GetMass();
     _PDG = track->GetDefinition()->GetPDGEncoding();
     _trackID = track->GetTrackID();
     _parentTrackID = track->GetParentID();
     /* The momentum appears to be set correctly before tracking occurs so set here along with energy. */
     _momentum = track->GetMomentum();
     _energy = track->GetTotalEnergy();
     /* Assign track time. */
     // G4cout << "setting track time to " << track->GetGlobalTime() << G4endl;
     _globalTime = track->GetGlobalTime();
 }
References TrackSummary::_charge, TrackSummary::_energy, TrackSummary::_globalTime, TrackSummary::_mass, TrackSummary::_momentum, TrackSummary::_parentTrackID, TrackSummary::_PDG, and TrackSummary::_trackID.
~TrackSummary()
virtual ~TrackSummary () inline virtual
Class destructor.
Definition at line 45 of file TrackSummary.hh.
{
         }
Member Function Documentation
buildMCParticle()
void buildMCParticle ()
Build the MCParticle for this TrackSummary.
Definition at line 184 of file TrackSummary.cc.
{
     // if we have an MCParticle already we just need to update it
     // otherwise we need to create one ...
     if (_mcparticle == 0) {
         _mcparticle = new MCParticleImpl;
         _simstatus[MCParticle::BITCreatedInSimulation] = 1;    // created in simulation
         _mcparticle->setGeneratorStatus(getHepEvtStatus());
         _mcparticle->setPDG(getPDG());
     }
     /* Set charge. */
     _mcparticle->setCharge(getCharge());
     /* Set endpoint. */
     double endpoint[3];
     endpoint[0] = getEndPoint()(0);
     endpoint[1] = getEndPoint()(1);
     endpoint[2] = getEndPoint()(2);
     _mcparticle->setEndpoint(endpoint);
     /* Set mass. */
     _mcparticle->setMass(_mass / GeV);
     /* Set simulator status. */
     _mcparticle->setSimulatorStatus(getSimulatorStatus());
     /* Set momentum. */
     float p[3];
     G4ThreeVector momentum = getMomentum();
     p[0] = momentum(0) / GeV;
     p[1] = momentum(1) / GeV;
     p[2] = momentum(2) / GeV;
     _mcparticle->setMomentum(p);
     /* Set vertex. */
     double vertex[3];
     vertex[0] = getVertex()(0);
     vertex[1] = getVertex()(1);
     vertex[2] = getVertex()(2);
     _mcparticle->setVertex(vertex);
     /* Set global time. */
     _mcparticle->setTime(_globalTime);
     /* Set momentum at endpoint. */
     float momentumAtEndpoint[3];
     momentumAtEndpoint[0] = _momentumAtEndpoint(0) / GeV;
     momentumAtEndpoint[1] = _momentumAtEndpoint(1) / GeV;
     momentumAtEndpoint[2] = _momentumAtEndpoint(2) / GeV;
     _mcparticle->setMomentumAtEndpoint(momentumAtEndpoint);
     /* Set up to date. */
     _mcParticleIsUpToDate = true;
 }
References TrackSummary::_globalTime, TrackSummary::_mass, TrackSummary::_mcparticle, TrackSummary::_mcParticleIsUpToDate, TrackSummary::_momentumAtEndpoint, TrackSummary::_simstatus, TrackSummary::getCharge(), TrackSummary::getEndPoint(), TrackSummary::getHepEvtStatus(), TrackSummary::getMomentum(), TrackSummary::getPDG(), TrackSummary::getSimulatorStatus(), and TrackSummary::getVertex().
Referenced by TrackManager::saveTrackSummaries(), and TrackSummary::setParentToBeSaved().
findParent()
TrackSummary * findParent () const
Find the parent particle.
Returns
The parent particle or this if has no parent.
Definition at line 174 of file TrackSummary.cc.
{
     TrackSummary* trackSummary = 0;
     if (_parentTrackID == 0) {
         return trackSummary;
     }
     return m_trackManager->findTrackSummary(_parentTrackID);
 }
References TrackSummary::_parentTrackID, TrackManager::findTrackSummary(), and TrackSummary::m_trackManager.
Referenced by TrackManager::findFirstSavedAncestor(), TrackSummary::setParentToBeSaved(), and TrackSummary::update().
getBackScattering()
G4bool getBackScattering () const inline
Return the back scatter status of this particle.
Returns
True if particle is back scatter; false if not.
Definition at line 188 of file TrackSummary.hh.
{
             return _backScattering;
         }
References TrackSummary::_backScattering.
Referenced by TrackingAction::PreUserTrackingAction(), and TrackSummary::update().
getCharge()
G4double getCharge () const inline
Get the charge.
Returns
The charge.
Definition at line 68 of file TrackSummary.hh.
{
             return _charge;
         }
References TrackSummary::_charge.
Referenced by TrackSummary::buildMCParticle().
getEndPoint()
G4ThreeVector getEndPoint () const inline
Get the endpoint of the particle.
Returns
The end point of the particle in mm.
Definition at line 76 of file TrackSummary.hh.
{
             return _endPoint;
         }
References TrackSummary::_endPoint.
Referenced by TrackSummary::buildMCParticle(), and TrackSummary::update().
getEnergy()
G4double getEnergy () const inline
Get the total energy including momentum and mass.
Returns
The total energy in GeV.
Definition at line 84 of file TrackSummary.hh.
{
             return sqrt(_momentum[0] * _momentum[0] + _momentum[1] * _momentum[1] + _momentum[2] * _momentum[2] + _mass * _mass);
         }
References TrackSummary::_mass, and TrackSummary::_momentum.
getHepEvtStatus()
G4int getHepEvtStatus () const inline
Get the HEPEVT or "generator" status of this particle, which is zero if this particle was generated in the simulation as a secondary.
Returns
The HEPEVT status.
Definition at line 101 of file TrackSummary.hh.
{
             return _hepEvtStatus;
         }
References TrackSummary::_hepEvtStatus.
Referenced by TrackSummary::buildMCParticle().
getMass()
G4double getMass () const inline
Get the mass in GeV.
Returns
The mass.
Definition at line 92 of file TrackSummary.hh.
{
             return _mass;
         }
References TrackSummary::_mass.
getMCParticle()
MCParticleImpl* getMCParticle () inline
Get the MCParticle of this particle.
Returns
The MCParticle of this particle or NULL if not built yet.
Definition at line 208 of file TrackSummary.hh.
{
             return _mcparticle;
         }
References TrackSummary::_mcparticle.
Referenced by TrackManager::findFirstSavedAncestor(), TrackManager::saveTrackSummaries(), and TrackSummary::setParentToBeSaved().
getMomentum()
G4ThreeVector getMomentum () const inline
Get the momentum (px, py, pz).
Returns
The momentum.
Definition at line 117 of file TrackSummary.hh.
{
             return _momentum;
         }
References TrackSummary::_momentum.
Referenced by TrackSummary::buildMCParticle().
getParent()
TrackSummary* getParent () const inline
Get the parent particle.
Returns
The parent particle.
Definition at line 125 of file TrackSummary.hh.
{
             return _parent;
         }
References TrackSummary::_parent.
getParentID()
G4int getParentID () const inline
Get the parent particle's track ID.
Returns
The parent's track ID.
Definition at line 157 of file TrackSummary.hh.
{
             return _parentTrackID;
         }
References TrackSummary::_parentTrackID.
Referenced by TrackSummary::setParentToBeSaved().
getPDG()
G4int getPDG () const inline
Get the PDG ID.
Returns
The PDG ID.
Definition at line 133 of file TrackSummary.hh.
{
             return _PDG;
         }
References TrackSummary::_PDG.
Referenced by TrackSummary::buildMCParticle().
getSimulatorStatus()
G4int getSimulatorStatus () const inline
Get the simulator status, which is zero if this is a generator particle.
Returns
The simulator status.
Definition at line 109 of file TrackSummary.hh.
{
             return _simstatus.to_ulong();
         }
References TrackSummary::_simstatus.
Referenced by TrackSummary::buildMCParticle().
getToBeSaved()
G4bool getToBeSaved () const inline
Return true if this particle will be saved to the output collection.
Returns
True if particle will be saved; false if not.
Definition at line 173 of file TrackSummary.hh.
{
             return _toBeSaved;
         }
References TrackSummary::_toBeSaved.
Referenced by TrackManager::findFirstSavedAncestor(), and TrackManager::saveTrackSummaries().
getTrackID()
G4int getTrackID () const inline
Get the track ID.
Returns
The track ID.
Definition at line 149 of file TrackSummary.hh.
{
             return _trackID;
         }
References TrackSummary::_trackID.
Referenced by TrackManager::findFirstSavedAncestor(), TrackManager::registerTrackSummary(), TrackManager::saveTrackSummaries(), and TrackSummary::setParentToBeSaved().
getTrackLength()
G4double getTrackLength () const inline
Get the track length in mm.
Returns
The track length.
Definition at line 165 of file TrackSummary.hh.
{
             return _trackLength;
         }
References TrackSummary::_trackLength.
getVertex()
const G4ThreeVector& getVertex () const inline
Get the vertex (x, y, z) in mm.
Returns
The vertex.
Definition at line 141 of file TrackSummary.hh.
{
             return _vertex;
         }
References TrackSummary::_vertex.
Referenced by TrackSummary::buildMCParticle(), and TrackSummary::update().
operator delete()
void operator delete (void * aTrackSummary) inline
Delete operator.
Definition at line 278 of file TrackSummary.hh.
{
     TrackSummaryAllocator.FreeSingle((TrackSummary*) aTrackSummary);
 }
References slic::TrackSummaryAllocator.
operator new()
void * operator new (size_t) inline
New operator.
Definition at line 272 of file TrackSummary.hh.
{
     void *aTrackSummary;
     aTrackSummary = (void*) TrackSummaryAllocator.MallocSingle();
     return aTrackSummary;
 }
References slic::TrackSummaryAllocator.
setBackScattering()
void setBackScattering () inline
Set back scatter status to true.
Definition at line 195 of file TrackSummary.hh.
{
             _backScattering = true;
         }
References TrackSummary::_backScattering.
Referenced by SteppingAction::UserSteppingAction().
setHasTrackerHit()
void setHasTrackerHit () inline
Set hasTrackerHit status to true.
Definition at line 223 of file TrackSummary.hh.
{
             _hasTrackerHit = true;
         }
References TrackSummary::_hasTrackerHit.
Referenced by UserTrackInformation::setHasTrackerHit().
setMCParticle()
void setMCParticle (MCParticleImpl * mcp) inline
Set the MCParticle.
Parameters
[in] mcp The MCParticle.
Definition at line 216 of file TrackSummary.hh.
{
             _mcparticle = mcp;
         }
References TrackSummary::_mcparticle.
setParentToBeSaved()
void setParentToBeSaved ()
Set toBeSaved flag on this particle's parent.
Definition at line 132 of file TrackSummary.cc.
{
     if (!(_mcparticle && _mcParticleIsUpToDate))
         buildMCParticle();
     else
         // In LCIO mode, if the theMCParticle exists we have already
         // passed by here.
         return;
     TrackSummary* myParent = findParent();
     /*
      if (myParent == this) {
      G4cout << "summary for " << this->getTrackID() << " is its own parent (probably a primary)" << G4endl;
      }
      */
     if (myParent) {
         // std::cout << " **** TrackSummary::SetParentToBeSaved for trackID: " << myParent->GetTrackID() << " this trackid: " << GetTrackID() << std::endl ;
         myParent->_toBeSaved = true;
         myParent->setParentToBeSaved();
         MCParticle* theParentMCParticle = myParent->getMCParticle();
         // fg: need to check if particle already has this parent assigned ...
         // this will be fixed in a future (>1.6) LCIO version
         const MCParticleVec& parents = _mcparticle->getParents();
         // I think this check for existing parent can probably be removed. --JM
         if (std::find(parents.begin(), parents.end(), theParentMCParticle) == parents.end()) {
             // fix B.Vormwald:  only add parent if particle created in simulation
             if (_mcparticle->getGeneratorStatus() == 0) {
                 _mcparticle->addParent(theParentMCParticle);
             }
         }
         // DEBUG
     } else {
         if (this->getParentID() != 0)
             G4cout << "WARNING: no parent track ID " << this->getParentID() << " found for " << this->getTrackID() << G4endl;
         }
     }
References TrackSummary::_mcparticle, TrackSummary::_mcParticleIsUpToDate, TrackSummary::_toBeSaved, TrackSummary::buildMCParticle(), TrackSummary::findParent(), TrackSummary::getMCParticle(), TrackSummary::getParentID(), TrackSummary::getTrackID(), and TrackSummary::setParentToBeSaved().
Referenced by TrackSummary::setParentToBeSaved().
setToBeSaved()
void setToBeSaved () inline
Set that this particle will be saved.
Definition at line 180 of file TrackSummary.hh.
{
             _toBeSaved = true;
         }
References TrackSummary::_toBeSaved.
update()
void update (const G4Track * track)
Update this object from a G4Track.
Parameters
[in] track The G4Track with update information.
Definition at line 44 of file TrackSummary.cc.
{
     //G4cout << "updating track " << this->_trackID << " from track " << track->GetTrackID() << G4endl;
     // TODO: Status flags to check; x means verified
     // x BITCreatedInSimulation
     // x BITBackscatter
     // x BITEndpoint (seems to be always turned on for sim particles)
     // x BITDecayedInTracker
     // x BITLeftDetector
     // x BITStopped
     // BITDecayedInCalorimeter (this is the default!)
     // BITVertexIsNotEndpointOfParent
     // BITOverlay
     /* Set the vertex position. */
     _vertex = track->GetVertexPosition();
     /* Set the end point. */
     _endPoint = track->GetPosition();
     /* Set the track length. */
     _trackLength = track->GetTrackLength();
     /* Set the generator status. */
     _hepEvtStatus = 0;
     if (_parentTrackID == 0) {
         const G4DecayProducts* preAssignedDecayProducts = track->GetDynamicParticle()->GetPreAssignedDecayProducts();
         if (preAssignedDecayProducts && preAssignedDecayProducts->entries() > 0)
             _hepEvtStatus = 2;
         else
             _hepEvtStatus = 1;
     }
     /* Initialize sim status. */
     _simstatus = 0;
     /* This indicates the particle has an endpoint. */
     _simstatus[MCParticle::BITEndpoint] = 1;
     /*
      * Get the last step point.
      */
     const G4Step* lastStep = track->GetStep();
     G4StepPoint* lastPostStepPoint = NULL;
     if (lastStep)
         lastPostStepPoint = lastStep->GetPostStepPoint();
     /* Check for back scattering. */
     if (_hepEvtStatus == 0) {
         if (getBackScattering())
             _simstatus[MCParticle::BITBackscatter] = 1;
     }
     /* Check if left detector. */
     G4bool leftDetector = false;
     if (lastPostStepPoint) {
         /* Tracks with the last step on the world boundary are flagged as LeftDetector. */
         if ((leftDetector = (lastPostStepPoint->GetStepStatus() == fWorldBoundary))) {
             _simstatus[MCParticle::BITLeftDetector] = 1;
         }
     }
     // BITStopped
     if (track->GetKineticEnergy() <= 0.)
         _simstatus[MCParticle::BITStopped] = 1;
     G4bool insideTrackerRegion = TrackUtil::getRegionInformation(track)->getStoreSecondaries();
     if (insideTrackerRegion)
         _simstatus[MCParticle::BITDecayedInTracker] = 1;
     // BITDecayedInCalorimeter
     // FIXME: This should not be the default.
     if (!insideTrackerRegion && !leftDetector)
         _simstatus[MCParticle::BITDecayedInCalorimeter] = 1;
     // BITVertexIsNotEndpointOfParent
     TrackSummary* myParent = findParent();
     // TODO: Check if parent is EVER available here.
     if (myParent)
         if (myParent->getEndPoint().isNear(getVertex()))
             _simstatus[MCParticle::BITVertexIsNotEndpointOfParent] = 1;
     // set momentum at endpoint from the current momentum
     _momentumAtEndpoint = track->GetMomentum();
 }
References TrackSummary::_endPoint, TrackSummary::_hepEvtStatus, TrackSummary::_momentumAtEndpoint, TrackSummary::_parentTrackID, TrackSummary::_simstatus, TrackSummary::_trackLength, TrackSummary::_vertex, TrackSummary::findParent(), TrackSummary::getBackScattering(), TrackSummary::getEndPoint(), TrackUtil::getRegionInformation(), and TrackSummary::getVertex().
Referenced by TrackingAction::PostUserTrackingAction(), and SteppingAction::UserSteppingAction().
Member Data Documentation
_backScattering
G4bool _backScattering private
Definition at line 257 of file TrackSummary.hh.
Referenced by TrackSummary::getBackScattering(), and TrackSummary::setBackScattering().
_charge
G4double _charge private
Definition at line 242 of file TrackSummary.hh.
Referenced by TrackSummary::getCharge(), and TrackSummary::TrackSummary().
_endPoint
G4ThreeVector _endPoint private
Definition at line 243 of file TrackSummary.hh.
Referenced by TrackSummary::getEndPoint(), and TrackSummary::update().
_energy
G4double _energy private
Definition at line 244 of file TrackSummary.hh.
Referenced by TrackSummary::TrackSummary().
_globalTime
G4double _globalTime private
Definition at line 253 of file TrackSummary.hh.
Referenced by TrackSummary::buildMCParticle(), and TrackSummary::TrackSummary().
_hasTrackerHit
G4bool _hasTrackerHit private
Definition at line 265 of file TrackSummary.hh.
Referenced by TrackSummary::setHasTrackerHit().
_hepEvtStatus
G4int _hepEvtStatus private
Definition at line 246 of file TrackSummary.hh.
Referenced by TrackSummary::getHepEvtStatus(), and TrackSummary::update().
_mass
G4double _mass private
Definition at line 245 of file TrackSummary.hh.
Referenced by TrackSummary::buildMCParticle(), TrackSummary::getEnergy(), TrackSummary::getMass(), and TrackSummary::TrackSummary().
_mcparticle
MCParticleImpl* _mcparticle private
Definition at line 262 of file TrackSummary.hh.
Referenced by TrackSummary::buildMCParticle(), TrackSummary::getMCParticle(), TrackSummary::setMCParticle(), and TrackSummary::setParentToBeSaved().
_mcParticleIsUpToDate
G4bool _mcParticleIsUpToDate private
Definition at line 263 of file TrackSummary.hh.
Referenced by TrackSummary::buildMCParticle(), and TrackSummary::setParentToBeSaved().
_momentum
G4ThreeVector _momentum private
Definition at line 248 of file TrackSummary.hh.
Referenced by TrackSummary::getEnergy(), TrackSummary::getMomentum(), and TrackSummary::TrackSummary().
_momentumAtEndpoint
G4ThreeVector _momentumAtEndpoint private
Definition at line 249 of file TrackSummary.hh.
Referenced by TrackSummary::buildMCParticle(), and TrackSummary::update().
_parent
TrackSummary* _parent private
Definition at line 250 of file TrackSummary.hh.
Referenced by TrackSummary::getParent().
_parentTrackID
G4int _parentTrackID private
Definition at line 259 of file TrackSummary.hh.
Referenced by TrackSummary::findParent(), TrackSummary::getParentID(), TrackSummary::TrackSummary(), and TrackSummary::update().
_PDG
G4int _PDG private
Definition at line 251 of file TrackSummary.hh.
Referenced by TrackSummary::getPDG(), and TrackSummary::TrackSummary().
_simstatus
std::bitset<32> _simstatus private
Definition at line 247 of file TrackSummary.hh.
Referenced by TrackSummary::buildMCParticle(), TrackSummary::getSimulatorStatus(), and TrackSummary::update().
_toBeSaved
G4bool _toBeSaved private
Definition at line 255 of file TrackSummary.hh.
Referenced by TrackSummary::getToBeSaved(), TrackSummary::setParentToBeSaved(), and TrackSummary::setToBeSaved().
_trackID
G4int _trackID private
Definition at line 258 of file TrackSummary.hh.
Referenced by TrackSummary::getTrackID(), and TrackSummary::TrackSummary().
_trackLength
G4double _trackLength private
Definition at line 260 of file TrackSummary.hh.
Referenced by TrackSummary::getTrackLength(), and TrackSummary::update().
_vertex
G4ThreeVector _vertex private
Definition at line 252 of file TrackSummary.hh.
Referenced by TrackSummary::getVertex(), and TrackSummary::update().
m_trackManager
TrackManager * m_trackManager = TrackManager::instance() static private
Definition at line 267 of file TrackSummary.hh.
Referenced by TrackSummary::findParent().
The documentation for this class was generated from the following files:
TrackSummary.hh
TrackSummary.cc