SLIC: LogMessenger Class Reference
LogMessenger Class Reference
G4UImessenger assigned to a LogStream.
#include <LogMessenger.hh>
Public Member Functions
LogMessenger (LogStream *logstream)
virtual ~LogMessenger ()
void SetNewValue (G4UIcommand *command, G4String newValues)
Private Member Functions
void defineCommands ()
Private Attributes
G4UIcmdWithAString * m_fileCmd
G4UIdirectory * m_loggerDir
LogStream * m_logStream
G4UIcmdWithAnInteger * m_setLevelCmd
Detailed Description
G4UImessenger assigned to a LogStream.
Definition at line 19 of file LogMessenger.hh.
Constructor & Destructor Documentation
LogMessenger()
LogMessenger (LogStream * logstream)
Class constructor.
Parameters
[in] logstream The LogStream.
Definition at line 16 of file LogMessenger.cc.
                                             :
         m_logStream(logger) {
     defineCommands();
 }
References LogMessenger::defineCommands().
~LogMessenger()
~LogMessenger () virtual
Class destructor.
Definition at line 21 of file LogMessenger.cc.
{
     ;
 }
Member Function Documentation
defineCommands()
void defineCommands () private
Definition at line 33 of file LogMessenger.cc.
{
     m_loggerDir = new G4UIdirectory(std::string("/log/" + m_logStream->getName() + "/").c_str());
     m_loggerDir->SetGuidance(std::string("Commands for the logger " + m_logStream->getName()).c_str());
     m_setLevelCmd = new G4UIcmdWithAnInteger(std::string("/log/" + m_logStream->getName() + "/setLogLevel").c_str(), this);
     m_setLevelCmd->SetParameterName("logLevel", false);
     std::string range = "logLevel >= 0 && logLevel < " + StringUtil::toString(LOG::nlevels);
     m_setLevelCmd->SetRange(range.c_str());
     m_setLevelCmd->SetGuidance("Set the log level.");
     m_fileCmd = new G4UIcmdWithAString(std::string("/log/" + m_logStream->getName() + "/setLogFile").c_str(), this);
     m_fileCmd->SetParameterName("file", false);
     m_fileCmd->SetGuidance("Set the output file for this logger.");
 }
References LogStream::getName(), LogMessenger::m_fileCmd, LogMessenger::m_loggerDir, LogMessenger::m_logStream, LogMessenger::m_setLevelCmd, and LOG::nlevels.
Referenced by LogMessenger::LogMessenger().
SetNewValue()
void SetNewValue (G4UIcommand * command, G4String newValues)
Execute macro command.
Parameters
[in] command The macro command.
[in] newValues The argument values.
Definition at line 25 of file LogMessenger.cc.
{
     if (cmd == m_setLevelCmd) {
         m_logStream->setOutputLevel((LOG::ELevel) G4UIcmdWithAnInteger::GetNewIntValue(newVals));
     } else if (cmd == m_fileCmd) {
         m_logStream->setOutputFile(newVals);
     }
 }
References LogMessenger::m_fileCmd, LogMessenger::m_logStream, LogMessenger::m_setLevelCmd, LogStream::setOutputFile(), and LogStream::setOutputLevel().
Member Data Documentation
m_fileCmd
G4UIcmdWithAString* m_fileCmd private
Definition at line 53 of file LogMessenger.hh.
Referenced by LogMessenger::defineCommands(), and LogMessenger::SetNewValue().
m_loggerDir
G4UIdirectory* m_loggerDir private
Definition at line 54 of file LogMessenger.hh.
Referenced by LogMessenger::defineCommands().
m_logStream
LogStream* m_logStream private
Definition at line 50 of file LogMessenger.hh.
Referenced by LogMessenger::defineCommands(), and LogMessenger::SetNewValue().
m_setLevelCmd
G4UIcmdWithAnInteger* m_setLevelCmd private
Definition at line 52 of file LogMessenger.hh.
Referenced by LogMessenger::defineCommands(), and LogMessenger::SetNewValue().
The documentation for this class was generated from the following files:
LogMessenger.hh
LogMessenger.cc