SLIC: CommandLineProcessor Class Reference
CommandLineProcessor Class Reference
Command line processor for SLIC that uses getopt.
#include <CommandLineProcessor.hh>
Public Types
typedef std::vector< CommandLineProcessor::OptionsPair > CommandLineArguments
typedef std::vector< CommandLineOption * > OptionsList
typedef std::pair< std::string, std::string > OptionsPair
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Member Functions
CommandLineProcessor ()
virtual ~CommandLineProcessor ()
CommandQueue * getCommandQueue ()
void printOptions ()
void printUsage ()
void printVersion ()
void process (int argc, char **argv)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from Singleton< CommandLineProcessor >
Singleton ()
~Singleton ()
void release ()
Private Member Functions
void abort ()
void addOption (CommandLineOption *option)
void createOptionsString ()
CommandLineOption * getCommandLineOption (const std::string &option)
bool hasOption (const std::string &option)
void processOption (const std::string &option)
void processOptions ()
void registerOptions ()
Private Attributes
OptionsList m_cmds
CommandLineArguments m_commandline
CommandQueue m_g4q
std::string m_getoptOptions
int m_help_flag
int m_interactive_flag
int m_version_flag
Additional Inherited Members
Static Public Member Functions inherited from Singleton< CommandLineProcessor >
static CommandLineProcessor * instance ()
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
Command line processor for SLIC that uses getopt.
Author
Jeremy McCormick
Note
All options are mapped in a straightforward fashion to Geant4 macro commands that may be defined within LCDD, SLIC, or Geant4 itself. The result of processing the command line using this class is to fill the CommandQueue, which is then retrieved and executed by G4Application.
Definition at line 28 of file CommandLineProcessor.hh.
Member Typedef Documentation
CommandLineArguments
typedef std::vector<CommandLineProcessor::OptionsPair> CommandLineArguments
CommandLineArguments is the list of options and arguments from the command line.
Definition at line 40 of file CommandLineProcessor.hh.
OptionsList
typedef std::vector<CommandLineOption*> OptionsList
OptionsList is a list of CommandLineOption classes describing valid command line switches.
Definition at line 45 of file CommandLineProcessor.hh.
OptionsPair
typedef std::pair<std::string, std::string> OptionsPair
OptionsPair is a short option name and its associated arguments.
Definition at line 35 of file CommandLineProcessor.hh.
Constructor & Destructor Documentation
CommandLineProcessor()
CommandLineProcessor ()
Class constructor.
Definition at line 21 of file CommandLineProcessor.cc.
                                            :
         Module("CommandLineProcessor"), m_help_flag(0), m_interactive_flag(0), m_version_flag(0) {
     registerOptions();
     createOptionsString();
 }
References CommandLineProcessor::createOptionsString(), and CommandLineProcessor::registerOptions().
~CommandLineProcessor()
~CommandLineProcessor () virtual
Class destructor.
Definition at line 27 of file CommandLineProcessor.cc.
{
 }
Member Function Documentation
abort()
void abort () private
Abort the application before Geant4 starts, e.g. if usage or version are selected. This is not called if the command line arguments are invalid, as getopt will handle this and call exit() itself.
Definition at line 186 of file CommandLineProcessor.cc.
{
     exit(0);
 }
Referenced by CommandLineProcessor::process().
addOption()
void addOption (CommandLineOption * option) private
Add a command line option describing a command line switch, its full name, description, geant4 command, etc.
Parameters
[in] option The command line option to add.
Definition at line 292 of file CommandLineProcessor.cc.
{
     m_cmds.push_back(opt);
 }
References CommandLineProcessor::m_cmds.
Referenced by CommandLineProcessor::registerOptions().
createOptionsString()
void createOptionsString () private
Automatically create the getopt options string from OptionsList and set the m_getoptOptions variable to this value.
Definition at line 451 of file CommandLineProcessor.cc.
{
     m_getoptOptions = "";
     for (OptionsList::iterator it = m_cmds.begin(); it != m_cmds.end(); it++) {
         CommandLineOption* opt = *it;
         m_getoptOptions += opt->getShortName();
         if (opt->getMinArgs()) {
             m_getoptOptions += ":";
         } else if (opt->getMaxArgs()) {
             m_getoptOptions += "::";
         }
     }
 }
References CommandLineOption::getMaxArgs(), CommandLineOption::getMinArgs(), CommandLineOption::getShortName(), CommandLineProcessor::m_cmds, and CommandLineProcessor::m_getoptOptions.
Referenced by CommandLineProcessor::CommandLineProcessor().
getCommandLineOption()
CommandLineOption * getCommandLineOption (const std::string & option) private
Find an option specification by its single letter designation (with no '-').
Parameters
[in] option The option to find.
Returns
The command line option object or null if does not exist.
Definition at line 429 of file CommandLineProcessor.cc.
{
     CommandLineOption* clo = 0;
     for (OptionsList::const_iterator iter = m_cmds.begin(); iter != m_cmds.end(); iter++) {
         if ((*iter)->getShortName() == opt) {
             clo = (*iter);
             break;
         }
     }
     return clo;
 }
References CommandLineProcessor::m_cmds.
Referenced by CommandLineProcessor::processOption().
getCommandQueue()
CommandQueue* getCommandQueue () inline
Get the queue of Geant4 macro commands created from the command line arguments.
Returns
The queue of Geant4 macro commands to execute.
Definition at line 97 of file CommandLineProcessor.hh.
{
             return &m_g4q;
         }
References CommandLineProcessor::m_g4q.
hasOption()
bool hasOption (const std::string & option) private
Returns true if the option was found in the command line arguments.
Parameters
[in] option The command line option.
Returns
True if option exist; false if not.
Definition at line 440 of file CommandLineProcessor.cc.
{
     bool hasoption = false;
     for (CommandLineArguments::iterator it = m_commandline.begin(); it != m_commandline.end(); it++) {
         if ((*it).first == opt) {
             hasoption = true;
             break;
         }
     }
     return hasoption;
 }
References CommandLineProcessor::m_commandline.
Referenced by CommandLineProcessor::processOptions().
printOptions()
void printOptions ()
Print out the options table.
Definition at line 366 of file CommandLineProcessor.cc.
{
     log() << LOG::okay << "************************" << LOG::done;
     log() << LOG::okay << "* Command Line Options *" << LOG::done;
     log() << LOG::okay << "************************" << LOG::done;
     log() << LOG::okay << LOG::done;
     static const int opt_width = 8;
     static const int descr_width = 15;
     static const int name_width = 16;
     static const int cmd_width = 24;
     static const int sep_width = 60;
     log().getOutputStream().width(opt_width);
     log().getOutputStream() << left;
     log().getOutputStream() << left;
     log() << LOG::okay << "Option";
     log().getOutputStream().width(name_width);
     log().getOutputStream() << left;
     log() << LOG::okay << "Full Name";
     log().getOutputStream().width(cmd_width);
     log().getOutputStream() << left;
     log() << LOG::okay << "Macro Command";
     log().getOutputStream().width(descr_width);
     log().getOutputStream() << left;
     log() << LOG::okay << "Description";
     log().getOutputStream().fill('-');
     log().getOutputStream().width(sep_width);
     log() << LOG::okay << LOG::done;
     log() << LOG::okay << '-' << LOG::done;
     log().getOutputStream().fill(' ');
     for (OptionsList::const_iterator iter = m_cmds.begin(); iter != m_cmds.end(); iter++) {
         CommandLineOption* cl_opt = (*iter);
         std::string opt_str = "-" + cl_opt->getShortName();
         log().getOutputStream().width(opt_width);
         log().getOutputStream() << left;
         log() << LOG::okay << opt_str;
         std::string name_str = "--" + cl_opt->getLongName();
         log().getOutputStream().width(name_width);
         log().getOutputStream() << left;
         log() << LOG::okay << name_str;
         log().getOutputStream().width(cmd_width);
         log().getOutputStream() << left;
         log() << LOG::okay << cl_opt->getG4CommandString();
         log().getOutputStream().width(descr_width);
         log().getOutputStream() << left;
         log() << LOG::okay << cl_opt->getDescription();
         log() << LOG::okay << LOG::done;
     }
 }
References LOG::done, CommandLineOption::getDescription(), CommandLineOption::getG4CommandString(), CommandLineOption::getLongName(), LogStream::getOutputStream(), CommandLineOption::getShortName(), Module::log(), CommandLineProcessor::m_cmds, and LOG::okay.
Referenced by CommandLineProcessor::printUsage().
printUsage()
void printUsage ()
Print the usage statement.
Definition at line 159 of file CommandLineProcessor.cc.
{
     printVersion();
     log() << LOG::okay << LOG::done;
     log() << LOG::okay << "**************" << LOG::done;
     log() << LOG::okay << "* SLIC Usage *" << LOG::done;
     log() << LOG::okay << "**************" << LOG::done;
     log() << LOG::okay << LOG::done;
     log() << LOG::okay << "Command line usage: " << LOG::done;
     log() << LOG::okay << LOG::done;
     log() << LOG::okay << "slic [single_macro_path]" << LOG::done;
     log() << LOG::okay << "slic [options]" << LOG::done;
     log() << LOG::okay << LOG::done;
     log() << LOG::okay << "Interactive usage: " << LOG::done;
     log() << LOG::okay << LOG::done;
     log() << LOG::okay << "slic -n" << LOG::done;
     log() << LOG::okay << LOG::done;
     printOptions();
     log() << LOG::okay << LOG::done;
 }
References LOG::done, Module::log(), LOG::okay, CommandLineProcessor::printOptions(), and CommandLineProcessor::printVersion().
Referenced by CommandLineProcessor::process().
printVersion()
void printVersion () inline
Print the version information.
Definition at line 88 of file CommandLineProcessor.hh.
{
             log() << LOG::okay << PackageInfo::getShortName() << " " << PackageInfo::getVersion() << LOG::done;
         }
References LOG::done, Module::log(), and LOG::okay.
Referenced by CommandLineProcessor::printUsage(), and CommandLineProcessor::process().
process()
void process (int argc, char ** argv)
This is the primary function to process the raw arguments. Options that will cause an abort, e.g. '-h', '-v', and '-n', are handled explicitly so that the correct flag is set. Other arguments are handled generically and put into the CommandLineArguments vector, which associates a short option name with its arguments (if any). Options that can occur more than once, such as the '-m' command, get one entry per occurrence in the CommandLineArguments. getopt will check that the option is valid and that enough arguments were received, before the command is put into CommandLineArguments. After calling process(), the getCommandQueue() function can be used to retrieve the list of Geant4 macro commands that resulted from processing the raw command line arguments.
Parameters
[in] argc The argument count.
[in] argv The argument values.
Definition at line 30 of file CommandLineProcessor.cc.
{
     // Description of SLIC's options in getopt's format.
     static struct option long_options[] = {
             { "help", no_argument, 0, 'h' },
             { "help", no_argument, 0, '?' },
             { "version", no_argument, 0, 'v' },
             { "interactive", no_argument, 0, 'n' },
             { "macro", required_argument, 0, 'm' },
             { "event-file", required_argument, 0, 'i' },
             { "lcdd-url", required_argument, 0, 'g' },
             { "lcio-file", required_argument, 0, 'o' },
             { "lcio-path", required_argument, 0, 'p' },
             { "autoname", optional_argument, 0, 'O' },
             { "lcio-delete", no_argument, 0, 'x' },
             { "run-events", required_argument, 0, 'r' },
             { "skip-events", required_argument, 0, 's' },
             { "physics-list", required_argument, 0, 'l' },
             { "log-file", required_argument, 0, 'L' },
             { "seed", required_argument, 0, 'd' },
             { "dump-gdml", required_argument, 0, 'G' },
             { "optical", no_argument, 0, 'c' },
             { "pdg-file", required_argument, 0, 'P' },
             { "lcdd-version", required_argument, 0, 'V' },
             { "lcdd-setup", required_argument, 0, 'S' },
             { "quiet", no_argument, 0, 'q' },
             { 0, 0, 0, 0 }
     };
     const char* optstr = m_getoptOptions.c_str();
     while (1) {
         int option_index = 0;
         int c;
         // Call getopt for next option.
         c = getopt_long(argc, argv, optstr, long_options, &option_index);
 #ifdef SLIC_LOG
         log() << LOG::verbose << "Handling option <" << c << ">." << LOG::done;
 #endif
         // Done.
         if (c == -1)
             break;
         // Handle options.
         switch (c) {
         case 'h':
             m_help_flag = 1;
             break;
         case '?':
             m_help_flag = 1;
             break;
         case 'n':
             m_interactive_flag = 1;
             break;
         case 'v':
             m_version_flag = 1;
             break;
         default:
             stringstream ostr;
             char cc = (char) c;
             ostr << cc;
             string theopt = ostr.str();
             if (optarg) {
                 m_commandline.push_back(OptionsPair(theopt, optarg));
             } else {
                 m_commandline.push_back(OptionsPair(theopt, ""));
             }
             break;
         }
     }
     //
     // The processing flow...
     //
     // 1) If version flag is set, print version and exit.
     //
     // 2) If usage flag is set or no arguments were received,
     //    print the usage and exit.
     //
     // 3) If a single non-option command was received, treat
     //    it as a macro to execute.
     //
     // 4) If no options were received or the number of options
     //    is less than the number of arguments, print usage
     //    and exit (syntax incorrect).
     //
     // 5) Finally, process the options in order if the syntax
     //    appears to be okay.
     //
     // Print the version information and abort.
     if (m_version_flag) {
         printVersion();
         abort();
     }
     // Print the usage and abort if the help flag is set
     // or no arguments were received.
     else if (m_help_flag || argc == 1) {
         printUsage();
         abort();
     }
     // Single macro to execute, if got 1 argument that is a non-option.
     else if (argc == 2 && optind < argc) {
         stringstream str;
         str << "/control/execute ";
         str << argv[1];
         m_g4q.add(str.str());
     }
     // Probably extra arguments or no options.
     else if (optind == 1 || optind < argc) {
         printUsage();
         abort();
     }
     // Default is process all the options and build the CommandQueue.
     else {
         processOptions();
     }
 }
References CommandLineProcessor::abort(), CommandQueue::add(), LOG::done, Module::log(), CommandLineProcessor::m_commandline, CommandLineProcessor::m_g4q, CommandLineProcessor::m_getoptOptions, CommandLineProcessor::m_help_flag, CommandLineProcessor::m_interactive_flag, CommandLineProcessor::m_version_flag, CommandLineProcessor::printUsage(), CommandLineProcessor::printVersion(), CommandLineProcessor::processOptions(), and LOG::verbose.
Referenced by SlicApplication::initialize().
processOption()
void processOption (const std::string & option) private
Process a command line switch by adding the corresponding Geant4 macro command to the CommandQueue.
Parameters
[in] option The option to process.
Definition at line 262 of file CommandLineProcessor.cc.
{
     // Loop over all input arguments to look for this option.
     for (CommandLineArguments::iterator it = m_commandline.begin(); it != m_commandline.end(); it++) {
         // Look for a matching switch in the arguments.
         if (it->first == opt) {
             // Get the associated specification for this option.
             CommandLineOption* cmdlineopt = getCommandLineOption(opt);
             // We must have a valid option!
             assert(cmdlineopt != 0);
             // Get the associated Geant4 command string.
             string cmdstr = cmdlineopt->getG4CommandString();
             // Add arguments to the command string, if some were passed.
             if (it->second != "") {
                 cmdstr += " ";
                 cmdstr += it->second;
             }
             // Add the command string to the CommandQueue.
             m_g4q.add(cmdstr);
         }
     }
 }
References CommandQueue::add(), CommandLineProcessor::getCommandLineOption(), CommandLineOption::getG4CommandString(), CommandLineProcessor::m_commandline, and CommandLineProcessor::m_g4q.
Referenced by CommandLineProcessor::processOptions().
processOptions()
void processOptions () private
Process all the command line arguments in correct order to create the queue of Geant4 commands.
Definition at line 296 of file CommandLineProcessor.cc.
{
     // Quiet mode
     processOption("q");
     // Logger.
     processOption("L");
     // GDML file version in setup tag.
     processOption("V");
     // GDML name in setup tag.
     processOption("S");
     // Geometry file.
     processOption("g");
     // Optical processes.
     processOption("c");
     // SUSY data.
     processOption("P");
     // Physics list.
     processOption("l");
     // Add initialization after geometry and physics,
     // but only if there was a geometry file argument.
     // Otherwise, initialize is not called, and the
     // user is given the PreInit prompt.
     if (hasOption("g")) {
         m_g4q.add("/run/initialize");
     }
     // Dump gdml.
     processOption("G");
     // Random seed.
     processOption("d");
     // Event file.
     processOption("i");
     // Output path.
     processOption("p");
     // Delete existing LCIO file.
     processOption("x");
     // Set LCIO file name.
     processOption("o");
     // Autoname the LCIO file.
     processOption("O");
     // Events to skip.
     processOption("s");
     // Geant4 macro to run.
     processOption("m");
     // Events to run.
     processOption("r");
     // Interactive mode, if selected.
     if (m_interactive_flag) {
         m_g4q.add("/control/interactive");
     }
 }
References CommandQueue::add(), CommandLineProcessor::hasOption(), CommandLineProcessor::m_g4q, CommandLineProcessor::m_interactive_flag, and CommandLineProcessor::processOption().
Referenced by CommandLineProcessor::process().
registerOptions()
void registerOptions () private
Register the list of valid command line options.
Definition at line 190 of file CommandLineProcessor.cc.
{
     // Print application usage.
     addOption(new CommandLineOption("h", "help", "Print SLIC usage.", 0, 0, "/slic/usage"));
     // Usage is also activated with the '?' switch.
     addOption(new CommandLineOption("?", "help", "Print SLIC usage.", 0, 0, "/slic/usage"));
     // Run in interactive mode.
     addOption(new CommandLineOption("n", "interactive", "Start a Geant4 interactive session.", 0, 0, "/control/interactive"));
     // Print SLIC version info.
     addOption(new CommandLineOption("v", "version", "Print SLIC version.", 0, 0, "/slic/version"));
     // Execute the commands from a macro file.
     addOption(new CommandLineOption("m", "macro", "Execute Geant4 commands from a file.", 1, 1, "/control/execute"));
     // Set the URL of the input LCDD file.
     addOption(new CommandLineOption("g", "lcdd-url", "Set LCDD geometry file URL.", 1, 1, "/lcdd/url"));
     // Set the path to a generator file, e.g. StdHep or LCIO.
     addOption(new CommandLineOption("i", "event-file", "Set event input file full path.", 1, 1, "/generator/filename"));
     // Set the name of the LCIO output file.
     addOption(new CommandLineOption("o", "lcio-file", "Set name of LCIO output file.", 1, 1, "/lcio/filename"));
     // Set the path of output files.
     addOption(new CommandLineOption("p", "lcio-path", "Set directory for LCIO output.", 1, 1, "/lcio/path"));
     // Automatically name the LCIO output file.
     addOption(new CommandLineOption("O", "autoname", "Automatically name the LCIO output file.", 0, 1, "/lcio/autoname"));
     // Overwrite an existing LCIO output file.
     addOption(
             new CommandLineOption("x", "lcio-delete", "Delete an existing LCIO file.", 0, 0,
                     "/lcio/fileExists delete"));
     // Number of events to run.
     addOption(new CommandLineOption("r", "run-events", "Run # of events.", 1, 1, "/run/beamOn"));
     // Set number of events to skip from a file-based event source (e.g. StdHep).
     addOption(new CommandLineOption("s", "skip-events", "Set number of events to skip.", 1, 1, "/generator/skipEvents"));
     // Set the physics list.
     addOption(new CommandLineOption("l", "physics-list", "Set Geant4 physics list.", 1, 1, "/physics/select"));
     // Set the name of the log file.
     addOption(new CommandLineOption("L", "log-file", "Set logfile name.", 0, 0, "/log/filename"));
     // Set the random seed.
     addOption(new CommandLineOption("d", "seed", "Set the random seed. (No argument seeds with time.)", 0, 1, "/random/seed"));
     // Dump the loaded Geant4 geometry to a GDML file.
     addOption(new CommandLineOption("G", "dump-gdml", "Dump geometry to GDML file.", 1, 1, "/lcdd/dumpGDML"));
     // Enable optical physics processes.
     addOption(new CommandLineOption("c", "optical", "Enable optical physics processes.", 0, 0, "/physics/enableOptical"));
     // Set location of particle.tbl.
     addOption(new CommandLineOption("P", "pdg-file", "Set location of particle.tbl file.", 1, 1, "/physics/setPDGFile"));
     // Set the version of the GDML setup.
     addOption(new CommandLineOption("V", "lcdd-version", "Set the version of the GDML setup tag.", 1, 1, "/lcdd/version"));
     // Set the name of the GMDL setup.
     addOption(new CommandLineOption("S", "lcdd-setup", "Set the name of the GDML setup tag.", 1, 1, "/lcdd/setupName"));
     // Activate quiet mode which suppresses stdout in the job.
     addOption(new CommandLineOption("q", "quiet", "Quiet mode.", 0, 0, "/slic/quiet"));
 }
References CommandLineProcessor::addOption().
Referenced by CommandLineProcessor::CommandLineProcessor().
Member Data Documentation
m_cmds
OptionsList m_cmds private
Definition at line 173 of file CommandLineProcessor.hh.
Referenced by CommandLineProcessor::addOption(), CommandLineProcessor::createOptionsString(), CommandLineProcessor::getCommandLineOption(), and CommandLineProcessor::printOptions().
m_commandline
CommandLineArguments m_commandline private
Definition at line 167 of file CommandLineProcessor.hh.
Referenced by CommandLineProcessor::hasOption(), CommandLineProcessor::process(), and CommandLineProcessor::processOption().
m_g4q
CommandQueue m_g4q private
Definition at line 170 of file CommandLineProcessor.hh.
Referenced by CommandLineProcessor::getCommandQueue(), CommandLineProcessor::process(), CommandLineProcessor::processOption(), and CommandLineProcessor::processOptions().
m_getoptOptions
std::string m_getoptOptions private
Definition at line 181 of file CommandLineProcessor.hh.
Referenced by CommandLineProcessor::createOptionsString(), and CommandLineProcessor::process().
m_help_flag
int m_help_flag private
Definition at line 176 of file CommandLineProcessor.hh.
Referenced by CommandLineProcessor::process().
m_interactive_flag
int m_interactive_flag private
Definition at line 177 of file CommandLineProcessor.hh.
Referenced by CommandLineProcessor::process(), and CommandLineProcessor::processOptions().
m_version_flag
int m_version_flag private
Definition at line 178 of file CommandLineProcessor.hh.
Referenced by CommandLineProcessor::process().
The documentation for this class was generated from the following files:
CommandLineProcessor.hh
CommandLineProcessor.cc