SLIC: PhysicsMessenger Class Reference
PhysicsMessenger Class Reference
G4UImessenger for selection of physics list at runtime.
#include <PhysicsMessenger.hh>
Public Member Functions
PhysicsMessenger ()
virtual ~PhysicsMessenger ()
virtual void SetNewValue (G4UIcommand *cmd, G4String newVals)
Private Member Functions
void defineCommands ()
Private Attributes
G4UIcmdWithABool * m_enableOpticalCmd
G4UIcommand * m_pdgCmd
G4UIdirectory * m_physicsListDir
G4UIcmdWithoutParameter * m_printCurrentCmd
G4UIcmdWithoutParameter * m_printListsCmd
G4UIcommand * m_selectCmd
Detailed Description
G4UImessenger for selection of physics list at runtime.
Note
Also handles data for the HepPDT interface.
Definition at line 18 of file PhysicsMessenger.hh.
Constructor & Destructor Documentation
PhysicsMessenger()
PhysicsMessenger ()
Class constructor.
Definition at line 16 of file PhysicsMessenger.cc.
                                    :
         m_physicsListDir(0), m_selectCmd(0) {
     defineCommands();
 }
References PhysicsMessenger::defineCommands().
~PhysicsMessenger()
~PhysicsMessenger () virtual
Class destructor.
Definition at line 21 of file PhysicsMessenger.cc.
{
 }
Member Function Documentation
defineCommands()
void defineCommands () private
Define commands handled by this messenger.
Definition at line 60 of file PhysicsMessenger.cc.
{
     G4UIparameter* p;
     m_physicsListDir = new G4UIdirectory("/physics/");
     m_physicsListDir->SetGuidance("Physics list commands. [SLIC]");
     // select physics list
     m_selectCmd = new G4UIcommand("/physics/select", this);
     m_selectCmd->SetGuidance("Select the Geant4 physics list.  This command is only available in the PreInit state.");
     p = new G4UIparameter("list", 's', false);
     m_selectCmd->SetParameter(p);
     m_selectCmd->AvailableForStates(G4State_PreInit);
     // print available lists
     m_printListsCmd = new G4UIcmdWithoutParameter("/physics/printLists", this);
     m_printListsCmd->SetGuidance("Print available physics lists.");
     // print current list
     m_printCurrentCmd = new G4UIcmdWithoutParameter("/physics/printCurrent", this);
     m_printCurrentCmd->SetGuidance("Print name of currently selected physics list.");
     // Enable optical physics processes for the current list when it is initialized.
     m_enableOpticalCmd = new G4UIcmdWithABool("/physics/enableOptical", this);
     m_enableOpticalCmd->SetGuidance("Enable optical physics processes.");
     m_enableOpticalCmd->SetParameterName("enable", 'b', true);
     m_enableOpticalCmd->SetDefaultValue(true);
     // Set location of particle.tbl for supplementary particle data.
     m_pdgCmd = new G4UIcommand("/physics/setPDGFile", this);
     m_pdgCmd->SetGuidance("Set location of particle data for HepPDT, probably called particle.tbl.");
     p = new G4UIparameter("file", 's', false);
     m_pdgCmd->SetParameter(p);
     m_pdgCmd->AvailableForStates(G4State_PreInit);
 }
References PhysicsMessenger::m_enableOpticalCmd, PhysicsMessenger::m_pdgCmd, PhysicsMessenger::m_physicsListDir, PhysicsMessenger::m_printCurrentCmd, PhysicsMessenger::m_printListsCmd, and PhysicsMessenger::m_selectCmd.
Referenced by PhysicsMessenger::PhysicsMessenger().
SetNewValue()
void SetNewValue (G4UIcommand * cmd, G4String newVals) virtual
Execute macro command.
Parameters
[in] cmd The command to execute.
[in] newVals The command arguments.
Definition at line 24 of file PhysicsMessenger.cc.
{
     std::istringstream is((const char*) newVals);
     std::string s;
     is >> s;
     PhysicsListManager* mgr = PhysicsListManager::instance();
     // set physics list
     if (cmd == m_selectCmd) {
         mgr->setCurrentListName(s);
     }
     // print available lists
     else if (cmd == m_printListsCmd) {
         PhysicsListManager::instance()->printAvailablePhysicsLists();
     }
     // Print current list and whether initialized.
     else if (cmd == m_printCurrentCmd) {
         mgr->log() << LOG::okay << "Current physics list <" << mgr->getCurrentListName() << ">." << LOG::done;
         mgr->log() << LOG::okay << "Physics has been initialized <" << mgr->isInitialized() << ">." << LOG::done;
     }
     // Enable optical physics processes.
     else if (cmd == m_enableOpticalCmd) {
         bool enableOptical = true;
         if (newVals != G4String(""))
             enableOptical = G4UIcmdWithABool::GetNewBoolValue(newVals);
         PhysicsListManager::instance()->enableOptical(enableOptical);
     }
     // Set location of particle.tbl for HepPDT.
     else if (cmd == m_pdgCmd) {
         HepPDTManager::instance()->setParticleDataFile(s);
     } else {
         mgr->log() << LOG::error << "Unknown command for PhysicsMessenger." << LOG::done;
     }
 }
References LOG::done, LOG::error, PhysicsListManager::getCurrentListName(), Singleton< PhysicsListManager >::instance(), Singleton< HepPDTManager >::instance(), PhysicsListManager::isInitialized(), Module::log(), PhysicsMessenger::m_enableOpticalCmd, PhysicsMessenger::m_pdgCmd, PhysicsMessenger::m_printCurrentCmd, PhysicsMessenger::m_printListsCmd, PhysicsMessenger::m_selectCmd, LOG::okay, and PhysicsListManager::setCurrentListName().
Member Data Documentation
m_enableOpticalCmd
G4UIcmdWithABool* m_enableOpticalCmd private
Definition at line 55 of file PhysicsMessenger.hh.
Referenced by PhysicsMessenger::defineCommands(), and PhysicsMessenger::SetNewValue().
m_pdgCmd
G4UIcommand* m_pdgCmd private
Definition at line 56 of file PhysicsMessenger.hh.
Referenced by PhysicsMessenger::defineCommands(), and PhysicsMessenger::SetNewValue().
m_physicsListDir
G4UIdirectory* m_physicsListDir private
Definition at line 50 of file PhysicsMessenger.hh.
Referenced by PhysicsMessenger::defineCommands().
m_printCurrentCmd
G4UIcmdWithoutParameter* m_printCurrentCmd private
Definition at line 54 of file PhysicsMessenger.hh.
Referenced by PhysicsMessenger::defineCommands(), and PhysicsMessenger::SetNewValue().
m_printListsCmd
G4UIcmdWithoutParameter* m_printListsCmd private
Definition at line 53 of file PhysicsMessenger.hh.
Referenced by PhysicsMessenger::defineCommands(), and PhysicsMessenger::SetNewValue().
m_selectCmd
G4UIcommand* m_selectCmd private
Definition at line 52 of file PhysicsMessenger.hh.
Referenced by PhysicsMessenger::defineCommands(), and PhysicsMessenger::SetNewValue().
The documentation for this class was generated from the following files:
PhysicsMessenger.hh
PhysicsMessenger.cc