SLIC: LcioManager Class Reference
LcioManager Class Reference
Singleton manager class of LCIO configuration and output file operations.
#include <LcioManager.hh>
Public Types
enum EFileExistsAction { eInvalid = -1, eFail = 0, eDelete = 1, eAppend = 2 }
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Member Functions
LcioManager ()
virtual ~LcioManager ()
void addCollection (EVENT::LCCollection *collection, const std::string &name)
void addCollection (EVENT::LCEvent *lcevent, EVENT::LCCollection *collection, const std::string &name)
void beginRun (const G4Run *run)
IMPL::LCEventImpl * createLCEvent ()
IMPL::LCEventImpl * createLCEvent (const G4Event *anEvent)
void enableDumpEvent (bool p=true)
void endEvent (const G4Event *anEvent)
void endRun (const G4Run *run)
IMPL::LCEventImpl * getCurrentLCEvent ()
EFileExistsAction getFileExistsAction ()
LcioFileNamer * getFileNamer ()
std::string getFullOutputPath (bool withExtension=false)
LcioHitsCollectionBuilder * getHitsCollectionBuilder ()
G4bool getWriteCompleteEvent ()
void openLcioFile ()
void setAutonameFields (const std::vector< std::string > &fields)
void setCurrentLCEvent (IMPL::LCEventImpl *anLCEvent)
void setFileExistsAction (EFileExistsAction fea)
void setFilename (const std::string &filename)
void setPath (const std::string &path)
void setRunNumber (int runNumber)
void setStoreMomentum (bool s=true)
void setWriteCompleteEvent (G4bool writeCompleteEvent)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void cleanup ()
bool deleteOnExit ()
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from Singleton< LcioManager >
Singleton ()
~Singleton ()
void release ()
Static Public Member Functions
static EFileExistsAction getFileExistsActionFromString (const std::string &fileExists)
Static Public Member Functions inherited from Singleton< LcioManager >
static LcioManager * instance ()
Private Member Functions
void addActiveSubdetectors ()
void createHitsCollections ()
void createRunHeader (const G4Run *run)
void createWriter ()
void deleteRunHeader ()
void deleteWriter ()
void makeAutoname ()
void setDetectorName ()
void setEventTimeStamp ()
Private Attributes
bool _writeCompleteEvent
std::vector< std::string > m_currentAutonameFields
IMPL::LCEventImpl * m_currentLCEvent
bool m_enableDumpEvent
EFileExistsAction m_fileExistsAction
std::string m_filename
LcioHitsCollectionBuilder * m_HCBuilder
LcioMessenger * m_messenger
LcioFileNamer * m_namer
std::string m_path
IMPL::LCRunHeaderImpl * m_runHdr
int m_runNumber
bool m_usingAutoname
IO::LCWriter * m_writer
bool m_writerIsOpen
Static Private Attributes
static std::string m_defaultFileName = "slicEvents"
Additional Inherited Members
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
Singleton manager class of LCIO configuration and output file operations.
Note
This class is the top-level instantiator of most other LCIO-related managers and helper classes.
Definition at line 45 of file LcioManager.hh.
Member Enumeration Documentation
EFileExistsAction
enum EFileExistsAction
Enum for setting what action to take when an output LCIO file already exists.
Enumerator
eInvalid
eFail
eDelete
eAppend
Definition at line 52 of file LcioManager.hh.
{
             eInvalid = -1, eFail = 0, eDelete = 1, eAppend = 2
         };
Constructor & Destructor Documentation
LcioManager()
LcioManager ()
Class constructor.
Definition at line 53 of file LcioManager.cc.
                          :
         Module("LcioManager"), m_writer(NULL), m_runHdr(NULL), m_fileExistsAction(LcioManager::eFail), m_runNumber(0), m_enableDumpEvent(false), m_writerIsOpen(false), m_usingAutoname(false) {
     // Initialize the Geant4 UI messenger for the LCIO.
     m_messenger = new LcioMessenger(this);
     // Initialize the LCIO HitsCollectionBuilder.
     m_HCBuilder = new LcioHitsCollectionBuilder();
     // Create the LCIO writer.
     createWriter();
     // Create the LCIO file namer.
     m_namer = new LcioFileNamer();
     // Set the default output file name.
     m_filename = m_defaultFileName;
 }
References LcioManager::createWriter(), LcioManager::m_defaultFileName, LcioManager::m_filename, LcioManager::m_HCBuilder, LcioManager::m_messenger, and LcioManager::m_namer.
~LcioManager()
~LcioManager () virtual
Class destructor.
Definition at line 72 of file LcioManager.cc.
{
     deleteWriter();
     if (m_messenger != 0) {
         delete m_messenger;
     }
 }
References LcioManager::deleteWriter(), and LcioManager::m_messenger.
Member Function Documentation
addActiveSubdetectors()
void addActiveSubdetectors () private
Add the list of active subdetectors into the event header.
Definition at line 270 of file LcioManager.cc.
{
     LCDDProcessor::SensitiveDetectors::const_iterator iter;
     LCDDProcessor* lcddProc = LCDDProcessor::instance();
     for (iter = lcddProc->getSensitiveDetectorsBegin(); iter != lcddProc->getSensitiveDetectorsEnd(); iter++) {
         m_runHdr->addActiveSubdetector((iter->second)->GetName());
     }
 }
References LcioManager::m_runHdr.
Referenced by LcioManager::createRunHeader().
addCollection() [1/2]
void addCollection (EVENT::LCCollection * collection, const std::string & name)
Add a collection the current LCEvent.
Parameters
[in] The collection.
Definition at line 393 of file LcioManager.cc.
{
     getCurrentLCEvent()->addCollection(collection, collectionName);
 }
References LcioManager::getCurrentLCEvent().
addCollection() [2/2]
void addCollection (EVENT::LCEvent * lcevent, EVENT::LCCollection * collection, const std::string & name)
Add a collection to the LCEvent.
Parameters
[in] lcsevent The LCEvent.
[in] collection The collection.
[in] name The name of the collection.
Definition at line 389 of file LcioManager.cc.
{
     event->addCollection(collection, collectionName);
 }
beginRun()
void beginRun (const G4Run * run) virtual
Begin of run hook.
Parameters
[in] run The run.
Reimplemented from Module.
Definition at line 189 of file LcioManager.cc.
{
     // Set the G4Run counter.
 #if ( G4VERSION_NUMBER >= 1000 )
     G4RunManager::GetRunManager()->GetNonConstCurrentRun()->SetRunID(m_runNumber);
 #else
     // Alternate code for backward compatibility.
     const_cast<G4Run *>(G4RunManager::GetRunManager()->GetCurrentRun())->SetRunID(m_runNumber);
 #endif
     // Automatically create LCIO output file name if option was selected.
     if (m_usingAutoname) {
         makeAutoname();
     }
     // Open the LCIO output file for writing.
     openLcioFile();
     // Run aborted, because LCIO output file already exists.
     if (!RunManager::instance()->isRunAborted()) {
         // create new LCRunHeader
         createRunHeader(aRun);
         // write the run header
         m_writer->writeRunHeader(m_runHdr);
         // Incr run number.
         ++m_runNumber;
     }
 }
References LcioManager::createRunHeader(), RunManager::instance(), LcioManager::m_runHdr, LcioManager::m_runNumber, LcioManager::m_usingAutoname, LcioManager::m_writer, LcioManager::makeAutoname(), and LcioManager::openLcioFile().
createHitsCollections()
void createHitsCollections () private
Create the hits collections using the current set of objects.
Definition at line 385 of file LcioManager.cc.
{
     m_HCBuilder->createHitCollectionsFromEvent(G4EventManager::GetEventManager()->GetNonconstCurrentEvent(), m_currentLCEvent);
 }
References LcioHitsCollectionBuilder::createHitCollectionsFromEvent(), LcioManager::m_currentLCEvent, and LcioManager::m_HCBuilder.
Referenced by LcioManager::endEvent().
createLCEvent() [1/2]
LCEventImpl * createLCEvent ()
Create the LCEvent from the current G4Event.
Returns
The LCEvent.
Definition at line 353 of file LcioManager.cc.
{
     return createLCEvent(G4EventManager::GetEventManager()->GetNonconstCurrentEvent());
 }
createLCEvent() [2/2]
LCEventImpl * createLCEvent (const G4Event * anEvent)
Create the LCEvent from the G4Event.
Parameters
[in] anEvent The input G4Event.
Returns
The output LCEvent.
Definition at line 317 of file LcioManager.cc.
{
     /* Create the LCEvent and set basic parameters. */
     LCEventImpl* lcevt = new LCEventImpl();
     lcevt->setEventNumber(anEvent->GetEventID());
     lcevt->setRunNumber(m_runHdr->getRunNumber());
     lcevt->setDetectorName(m_runHdr->getDetectorName());
     /* Get the current MCParticle collection. */
     LCCollection* mcpColl = MCParticleManager::instance()->getMCParticleCollection();
     if (mcpColl != 0) {
         /* Set the event weight. */
         float eventWeight = mcpColl->getParameters().getFloatVal("_weight");
         if (eventWeight != 0.0) {
             lcevt->setWeight(eventWeight);
         }
         /* Set the idrup. */
         int idrup = mcpColl->getParameters().getIntVal("_idrup");
         //G4cout << "idrup = " << idrup << G4endl;
         if (idrup != 0) {
             lcevt->parameters().setValue("_idrup", idrup);
         }
     }
     // Write SLIC version into event header.
     lcevt->parameters().setValue("SLIC_VERSION", PackageInfo::getVersion());
     /* Set the current LCEvent. */
     setCurrentLCEvent(lcevt);
     return lcevt;
 }
References Singleton< MCParticleManager >::instance(), LcioManager::m_runHdr, and LcioManager::setCurrentLCEvent().
createRunHeader()
void createRunHeader (const G4Run * run) private
Create the run header from the Geant4 run.
Parameters
[in] run The Geant4 run.
Definition at line 240 of file LcioManager.cc.
{
     // create new run header
     m_runHdr = new LCRunHeaderImpl();
     // Write SLIC version into run header.
     m_runHdr->parameters().setValue("SLIC_VERSION", PackageInfo::getVersion());
     // set run number
     m_runHdr->setRunNumber(m_runNumber);
     // set detector name in LCIO header
     setDetectorName();
     // add active subdet to header
     addActiveSubdetectors();
 }
References LcioManager::addActiveSubdetectors(), LcioManager::m_runHdr, LcioManager::m_runNumber, and LcioManager::setDetectorName().
Referenced by LcioManager::beginRun().
createWriter()
void createWriter () private
Create the output LCWriter.
Definition at line 149 of file LcioManager.cc.
{
     m_writer = IOIMPL::LCFactory::getInstance()->createLCWriter();
 }
References LcioManager::m_writer.
Referenced by LcioManager::LcioManager().
deleteRunHeader()
void deleteRunHeader () private
Delete the current run header.
Definition at line 263 of file LcioManager.cc.
{
     if (m_runHdr) {
         delete m_runHdr;
         m_runHdr = 0;
     }
 }
References LcioManager::m_runHdr.
Referenced by LcioManager::endRun().
deleteWriter()
void deleteWriter () private
Delete the current LCWriter.
Definition at line 153 of file LcioManager.cc.
{
     if (m_writer != 0) {
         if (m_writerIsOpen) {
             try {
                 m_writer->close();
                 m_writerIsOpen = false;
             } catch (...) {
             }
         }
         delete m_writer;
         m_writer = 0;
     }
 }
References LcioManager::m_writer, and LcioManager::m_writerIsOpen.
Referenced by LcioManager::~LcioManager().
enableDumpEvent()
void enableDumpEvent (bool p = true) inline
Enable dump event output for debugging.
Parameters
[in] The dump event setting.
Definition at line 222 of file LcioManager.hh.
{
             m_enableDumpEvent = p;
         }
References LcioManager::m_enableDumpEvent.
Referenced by LcioMessenger::SetNewValue().
endEvent()
void endEvent (const G4Event * anEvent) virtual
End of event hook to write out an LCIO file.
Parameters
[in] The physics event.
Reimplemented from Module.
Definition at line 357 of file LcioManager.cc.
{
     // create HC in current LCEvent from current G4Event using builder
     createHitsCollections();
     // Dump event stats.
     if (m_enableDumpEvent) {
         LCTOOLS::dumpEventDetailed(m_currentLCEvent);
     }
     // set timestamp
     setEventTimeStamp();
     // write event
     m_writer->writeEvent(m_currentLCEvent);
     // flush writer
     m_writer->flush();
     // delete event's transient objects, including current LCEvent
     delete m_currentLCEvent;
     m_currentLCEvent = 0;
 }
References LcioManager::createHitsCollections(), LcioManager::m_currentLCEvent, LcioManager::m_enableDumpEvent, LcioManager::m_writer, and LcioManager::setEventTimeStamp().
endRun()
void endRun (const G4Run * run) virtual
End of run hook.
Parameters
[in] run The run.
Reimplemented from Module.
Definition at line 221 of file LcioManager.cc.
{
     // Delete the LCIO run header object.
     deleteRunHeader();
     // Set append mode for subsequent writes if interactive mode and the run was not aborted.
     if (!RunManager::instance()->isRunAborted()) {
         // If run was aborted, writer was never opened.
         if (m_writer != 0) {
             m_writer->close();
             m_writerIsOpen = false;
         }
         // Close the writer to flush it (could be reopened).
         if (SlicApplication::instance()->getMode() == SlicApplication::eInteractive) {
             m_fileExistsAction = eAppend;
         }
     }
 }
References LcioManager::deleteRunHeader(), LcioManager::eAppend, SlicApplication::eInteractive, Singleton< SlicApplication >::instance(), RunManager::instance(), LcioManager::m_fileExistsAction, LcioManager::m_writer, and LcioManager::m_writerIsOpen.
getCurrentLCEvent()
IMPL::LCEventImpl* getCurrentLCEvent () inline
Get the current LCEvent.
Returns
The current LCEvent.
Definition at line 167 of file LcioManager.hh.
{
             return m_currentLCEvent;
         }
References LcioManager::m_currentLCEvent.
Referenced by LcioManager::addCollection(), and LcioManager::setEventTimeStamp().
getFileExistsAction()
EFileExistsAction getFileExistsAction () inline
Get the file exists action.
Returns
The file exists action.
Definition at line 198 of file LcioManager.hh.
{
             return m_fileExistsAction;
         }
References LcioManager::m_fileExistsAction.
getFileExistsActionFromString()
LcioManager::EFileExistsAction getFileExistsActionFromString (const std::string & fileExists) static
Get the FileExists enum value from a string.
Parameters
[in] fileExists The file exists string.
Returns
The file exists action from the string.
Definition at line 130 of file LcioManager.cc.
{
     string s = StringUtil::toLower(feaStr);
     EFileExistsAction fea = eInvalid;
     if (s == "fail") {
         fea = eFail;
     } else if (s == "overwrite" || s == "delete") {
         fea = eDelete;
     } else if (s == "append") {
         fea = eAppend;
     }
     return fea;
 }
References LcioManager::eAppend, LcioManager::eDelete, LcioManager::eFail, and LcioManager::eInvalid.
Referenced by LcioMessenger::SetNewValue().
getFileNamer()
LcioFileNamer* getFileNamer () inline
Get the LcioFileNamer for automatically naming output files.
Returns
The LcioFileNamer for naming output files.
Definition at line 214 of file LcioManager.hh.
{
             return m_namer;
         }
References LcioManager::m_namer.
getFullOutputPath()
string getFullOutputPath (bool withExtension = false)
Get the path plus the filename and optionally include the extension.
Parameters
[in] withExtension Whether or not to include the file extension.
Returns
The full output file path.
Definition at line 167 of file LcioManager.cc.
{
     string fullPath;
     if (m_path.length() > 0) {
         // Append the output directory if one exists.
         fullPath = m_path;
     } else {
         // Default to the current directory if none specified.
         fullPath = ".";
     }
     // Append file name.
     fullPath += "/" + m_filename;
     // Append extension.
     if (withExtension) {
         fullPath += ".slcio";
     }
     return fullPath;
 }
References LcioManager::m_filename, and LcioManager::m_path.
Referenced by LcioManager::openLcioFile().
getHitsCollectionBuilder()
LcioHitsCollectionBuilder* getHitsCollectionBuilder () inline
Get the LcioHitsCollectionBuilder for creating output hit collections.
Returns
The LcioHitsCollectionBuilder.
Definition at line 206 of file LcioManager.hh.
{
             return m_HCBuilder;
         }
References LcioManager::m_HCBuilder.
Referenced by LcioMessenger::SetNewValue().
getWriteCompleteEvent()
G4bool getWriteCompleteEvent () inline
Definition at line 234 of file LcioManager.hh.
{
             return _writeCompleteEvent;
         }
References LcioManager::_writeCompleteEvent.
makeAutoname()
void makeAutoname () private
Make the LCIO output file name using the LcioFileNamer.
Definition at line 306 of file LcioManager.cc.
{
     std::string autoname = m_namer->makeFileName(m_currentAutonameFields);
     if (autoname.size() == 0 || autoname == "") {
         log().warning("Autonaming returned an empty string.  Using default file name <" + m_defaultFileName + ">");
         setFilename(m_defaultFileName);
     } else {
         setFilename(autoname);
         log().okay("Autoname set file name to <" + autoname + ">.");
     }
 }
References Module::log(), LcioManager::m_currentAutonameFields, LcioManager::m_defaultFileName, LcioManager::m_namer, LcioFileNamer::makeFileName(), LogStream::okay(), LcioManager::setFilename(), and LogStream::warning().
Referenced by LcioManager::beginRun().
openLcioFile()
void openLcioFile ()
Open the output LCIO file.
Definition at line 81 of file LcioManager.cc.
{
     // Get full output path with extension to check its existence.
     string fullFilename = getFullOutputPath(true);
     // Default to writing a new file.
     int writeMode = LCIO::WRITE_NEW;
     // File exists?
     if (FileUtil::fileExists(fullFilename)) {
         // Failure mode is on, so kill the current run.
         if (m_fileExistsAction == eFail) {
             log() << LOG::fatal << LOG::name << LOG::sep << "LCIO file already exists: " << fullFilename << LOG::done;
             RunManager::instance()->abortRun(SlicApplication::OUTPUT_FILE_EXISTS);
             // Deletion mode is on, so try to remove the current file.
         } else if (m_fileExistsAction == eDelete) {
             if (FileUtil::removeFile(fullFilename) != 0) {
                 // Fatal error.  File could not be removed.
                 log() << LOG::fatal << LOG::head << "Unable to delete old LCIO file: " << fullFilename << LOG::done;
                 RunManager::instance()->abortRun(SlicApplication::FAILED_DELETE_LCIO_FILE);
             } else {
                 log().okay("Deleted old LCIO file: " + fullFilename);
             }
         }
         // Append mode is on.
         else if (m_fileExistsAction == eAppend) {
             log().okay("Appending to existing LCIO file: " + fullFilename);
             writeMode = LCIO::WRITE_APPEND;
         }
     }
     // Create a new file if doesn't exist.
     else {
         log().okay("Creating new LCIO file: " + fullFilename);
     }
     // Open the file using the writer with the full path.
     if (m_writer) {
         if (!RunManager::instance()->isRunAborted()) {
             m_writer->open(getFullOutputPath(false), writeMode);
             m_writerIsOpen = true;
         }
     } else {
         //G4Exception("", "", FatalException, "LCWriter is null.");
         log() << LOG::fatal << LOG::head << "LCWriter is null." << LOG::done;
         RunManager::instance()->abortRun();
     }
 }
References RunManager::abortRun(), LOG::done, LcioManager::eAppend, LcioManager::eDelete, LcioManager::eFail, SlicApplication::FAILED_DELETE_LCIO_FILE, LOG::fatal, FileUtil::fileExists(), LcioManager::getFullOutputPath(), LOG::head, RunManager::instance(), Module::log(), LcioManager::m_fileExistsAction, LcioManager::m_writer, LcioManager::m_writerIsOpen, LOG::name, LogStream::okay(), SlicApplication::OUTPUT_FILE_EXISTS, FileUtil::removeFile(), and LOG::sep.
Referenced by LcioManager::beginRun().
setAutonameFields()
void setAutonameFields (const std::vector< std::string > & fields)
Set the list of fields to use for output file autonaming.
Definition at line 298 of file LcioManager.cc.
{
     m_usingAutoname = true;
     m_currentAutonameFields.clear();
     for (std::vector<std::string>::const_iterator it = fields.begin(); it != fields.end(); it++) {
         m_currentAutonameFields.push_back(*it);
     }
 }
References LcioManager::m_currentAutonameFields, and LcioManager::m_usingAutoname.
Referenced by LcioMessenger::SetNewValue().
setCurrentLCEvent()
void setCurrentLCEvent (IMPL::LCEventImpl * anLCEvent) inline
Set the current output LCIO event.
Parameters
[in] anLCEvent The LCIO event.
Definition at line 159 of file LcioManager.hh.
{
             m_currentLCEvent = anLCEvent;
         }
References LcioManager::m_currentLCEvent.
Referenced by LcioManager::createLCEvent().
setDetectorName()
void setDetectorName () private
Set the detector name in the current run header.
Definition at line 257 of file LcioManager.cc.
{
     string det_tag = LCDDProcessor::instance()->getDetectorName();
     m_runHdr->setDetectorName(det_tag);
     log().okay("Detector name set to <" + det_tag + "> in run header.");
 }
References Module::log(), LcioManager::m_runHdr, and LogStream::okay().
Referenced by LcioManager::createRunHeader().
setEventTimeStamp()
void setEventTimeStamp () private
Set the time stamp in the current event header.
Definition at line 381 of file LcioManager.cc.
{
     getCurrentLCEvent()->setTimeStamp(TimeUtil::getTimeNS());
 }
References LcioManager::getCurrentLCEvent(), and TimeUtil::getTimeNS().
Referenced by LcioManager::endEvent().
setFileExistsAction()
void setFileExistsAction (EFileExistsAction fea) inline
Set the file exists action.
Parameters
[in] fea The file exists action.
Definition at line 183 of file LcioManager.hh.
{
             if (fea == eInvalid) {
 #ifdef SLIC_LOG
                 log() << LOG::error << "Invalid setting for FileExistsAction." << LOG::done;
 #endif
                 return;
             }
             m_fileExistsAction = fea;
         }
References LOG::done, LcioManager::eInvalid, LOG::error, Module::log(), and LcioManager::m_fileExistsAction.
Referenced by LcioMessenger::SetNewValue().
setFilename()
void setFilename (const std::string & filename)
Set the output file name, which will be appended to the path.
Definition at line 285 of file LcioManager.cc.
{
     m_filename = filename;
     /* If the given filename has an extension, then remove it.
      The LCIO library will add it automatically. */
     size_t hasExt = filename.find(".slcio");
     if (hasExt != string::npos) {
         m_filename.replace(filename.size() - 6, 6, "");
     }
     log().okay("Set output file name to <" + m_filename + ">.");
 }
References Module::log(), LcioManager::m_filename, and LogStream::okay().
Referenced by LcioManager::makeAutoname(), and LcioMessenger::SetNewValue().
setPath()
void setPath (const std::string & path)
Set the output path.
Definition at line 279 of file LcioManager.cc.
{
     log().okay("Set output directory to <" + path + ">.");
     m_path = path;
 }
References Module::log(), LcioManager::m_path, and LogStream::okay().
Referenced by LcioMessenger::SetNewValue().
setRunNumber()
void setRunNumber (int runNumber)
Set the current run number.
Parameters
[in] runNumber The run number.
Definition at line 144 of file LcioManager.cc.
{
     m_runNumber = runNumber;
     log().verbose("Set starting run number <" + StringUtil::toString((int)runNumber) + ">");
 }
References Module::log(), LcioManager::m_runNumber, and LogStream::verbose().
Referenced by LcioMessenger::SetNewValue().
setStoreMomentum()
void setStoreMomentum (bool s = true) inline
Set whether to store momentum in output hits.
Parameters
[in] s Setting for storing momentum in output hits.
Definition at line 175 of file LcioManager.hh.
{
             m_HCBuilder->setStoreMomentum(s);
         }
References LcioManager::m_HCBuilder, and LcioHitsCollectionBuilder::setStoreMomentum().
setWriteCompleteEvent()
void setWriteCompleteEvent (G4bool writeCompleteEvent) inline
Enable writing complete event to MCParticle collection.
Parameters
[in] writeCompleteEvent Set to true to write complete event.
Definition at line 230 of file LcioManager.hh.
{
             _writeCompleteEvent = writeCompleteEvent;
         }
References LcioManager::_writeCompleteEvent.
Member Data Documentation
_writeCompleteEvent
bool _writeCompleteEvent private
Definition at line 324 of file LcioManager.hh.
Referenced by LcioManager::getWriteCompleteEvent(), and LcioManager::setWriteCompleteEvent().
m_currentAutonameFields
std::vector<std::string> m_currentAutonameFields private
Definition at line 319 of file LcioManager.hh.
Referenced by LcioManager::makeAutoname(), and LcioManager::setAutonameFields().
m_currentLCEvent
IMPL::LCEventImpl* m_currentLCEvent private
Definition at line 305 of file LcioManager.hh.
Referenced by LcioManager::createHitsCollections(), LcioManager::endEvent(), LcioManager::getCurrentLCEvent(), and LcioManager::setCurrentLCEvent().
m_defaultFileName
string m_defaultFileName = "slicEvents" static private
Definition at line 318 of file LcioManager.hh.
Referenced by LcioManager::LcioManager(), and LcioManager::makeAutoname().
m_enableDumpEvent
bool m_enableDumpEvent private
Definition at line 321 of file LcioManager.hh.
Referenced by LcioManager::enableDumpEvent(), and LcioManager::endEvent().
m_fileExistsAction
EFileExistsAction m_fileExistsAction private
Definition at line 311 of file LcioManager.hh.
Referenced by LcioManager::endRun(), LcioManager::getFileExistsAction(), LcioManager::openLcioFile(), and LcioManager::setFileExistsAction().
m_filename
std::string m_filename private
Definition at line 295 of file LcioManager.hh.
Referenced by LcioManager::getFullOutputPath(), LcioManager::LcioManager(), and LcioManager::setFilename().
m_HCBuilder
LcioHitsCollectionBuilder* m_HCBuilder private
Definition at line 302 of file LcioManager.hh.
Referenced by LcioManager::createHitsCollections(), LcioManager::getHitsCollectionBuilder(), LcioManager::LcioManager(), and LcioManager::setStoreMomentum().
m_messenger
LcioMessenger* m_messenger private
Definition at line 308 of file LcioManager.hh.
Referenced by LcioManager::LcioManager(), and LcioManager::~LcioManager().
m_namer
LcioFileNamer* m_namer private
Definition at line 316 of file LcioManager.hh.
Referenced by LcioManager::getFileNamer(), LcioManager::LcioManager(), and LcioManager::makeAutoname().
m_path
std::string m_path private
Definition at line 296 of file LcioManager.hh.
Referenced by LcioManager::getFullOutputPath(), and LcioManager::setPath().
m_runHdr
IMPL::LCRunHeaderImpl* m_runHdr private
Definition at line 292 of file LcioManager.hh.
Referenced by LcioManager::addActiveSubdetectors(), LcioManager::beginRun(), LcioManager::createLCEvent(), LcioManager::createRunHeader(), LcioManager::deleteRunHeader(), and LcioManager::setDetectorName().
m_runNumber
int m_runNumber private
Definition at line 314 of file LcioManager.hh.
Referenced by LcioManager::beginRun(), LcioManager::createRunHeader(), and LcioManager::setRunNumber().
m_usingAutoname
bool m_usingAutoname private
Definition at line 323 of file LcioManager.hh.
Referenced by LcioManager::beginRun(), and LcioManager::setAutonameFields().
m_writer
IO::LCWriter* m_writer private
Definition at line 289 of file LcioManager.hh.
Referenced by LcioManager::beginRun(), LcioManager::createWriter(), LcioManager::deleteWriter(), LcioManager::endEvent(), LcioManager::endRun(), and LcioManager::openLcioFile().
m_writerIsOpen
bool m_writerIsOpen private
Definition at line 322 of file LcioManager.hh.
Referenced by LcioManager::deleteWriter(), LcioManager::endRun(), and LcioManager::openLcioFile().
The documentation for this class was generated from the following files:
LcioManager.hh
LcioManager.cc