SLIC: PhysicsListManager Class Reference
PhysicsListManager Class Reference
Provides management of user physics lists.
#include <PhysicsListManager.hh>
Public Member Functions
PhysicsListManager ()
virtual ~PhysicsListManager ()
G4VUserPhysicsList * createPhysicsList ()
bool enableLimits ()
void enableLimits (bool enableLimits)
bool enableOptical ()
void enableOptical (bool enableOptical)
const std::string & getCurrentListName ()
bool isInitialized ()
void printAvailablePhysicsLists ()
void setCurrentListName (const std::string &name)
void setupUserLimitsProcesses ()
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Public Member Functions inherited from Singleton< PhysicsListManager >
Singleton ()
~Singleton ()
void release ()
Private Member Functions
void setupSUSY ()
Private Attributes
G4VUserPhysicsList * m_currentList
std::string m_currentListName
bool m_enableLimits
bool m_enableOptical
G4PhysListFactory * m_factory
bool m_isFromDefault
bool m_isInitialized
PhysicsMessenger * m_messenger
bool m_setupLimits
Static Private Attributes
static const std::string m_defaultListName = std::string("QGSP_BERT")
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Static Public Member Functions inherited from Singleton< PhysicsListManager >
static PhysicsListManager * instance ()
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
Provides management of user physics lists.
Note
Current, primary function is selection of a list and . setting the default, which is LCPhys.
Definition at line 29 of file PhysicsListManager.hh.
Constructor & Destructor Documentation
PhysicsListManager()
PhysicsListManager ()
The class constructor.
Definition at line 20 of file PhysicsListManager.cc.
                                        :
         Module("PhysicsListManager"), m_currentList(0), m_isInitialized(false), m_isFromDefault(false), m_enableLimits(false), m_setupLimits(false), m_enableOptical(false) {
     // Set the current list to the default.
     m_currentListName = m_defaultListName;
     // Create the messenger class for the manager.
     m_messenger = new PhysicsMessenger();
     // Create the list factory.
     m_factory = new G4PhysListFactory();
 }
References PhysicsListManager::m_currentListName, PhysicsListManager::m_defaultListName, PhysicsListManager::m_factory, and PhysicsListManager::m_messenger.
~PhysicsListManager()
~PhysicsListManager () virtual
The class destructor.
Definition at line 32 of file PhysicsListManager.cc.
{
 }
Member Function Documentation
createPhysicsList()
G4VUserPhysicsList * createPhysicsList ()
Initialize the currently selected physics list. This will also register option physics such as optical and extended particle set.
Definition at line 40 of file PhysicsListManager.cc.
{
 #ifdef SLIC_LOG
     if ( m_isFromDefault ) {
         log() << LOG::okay << "Using default physics list <" << m_defaultListName << ">." << LOG::done;
     }
 #endif
     // Create the physics list from the name argument.
     m_currentList = m_factory->GetReferencePhysList(m_currentListName);
     // Enable optical processes.
     if (enableOptical()) {
         dynamic_cast<G4VModularPhysicsList*>(m_currentList)->RegisterPhysics(new LCOpticalPhysics("optical"));
     }
     if (HepPDTManager::instance()->getParticleDataTable()) {
         dynamic_cast<G4VModularPhysicsList*>(m_currentList)->RegisterPhysics(new LCExtendedParticles());
     }
     return m_currentList;
 }
References LOG::done, PhysicsListManager::enableOptical(), Singleton< HepPDTManager >::instance(), Module::log(), PhysicsListManager::m_currentList, PhysicsListManager::m_currentListName, PhysicsListManager::m_defaultListName, PhysicsListManager::m_factory, PhysicsListManager::m_isFromDefault, and LOG::okay.
enableLimits() [1/2]
bool enableLimits () inline
Return true if physics limits are enabled.
Returns
True if physics limits are enabled; false if not.
Definition at line 87 of file PhysicsListManager.hh.
{
             return m_enableLimits;
         }
References PhysicsListManager::m_enableLimits.
Referenced by PhysicsListManager::enableLimits().
enableLimits() [2/2]
void enableLimits (bool enableLimits) inline
Enable physics limits.
Parameters
[in] enableLimits True to enable limits; false to disable.
Definition at line 79 of file PhysicsListManager.hh.
{
             m_enableLimits = enableLimits;
         }
References PhysicsListManager::enableLimits(), and PhysicsListManager::m_enableLimits.
Referenced by RunManager::InitializePhysics().
enableOptical() [1/2]
bool enableOptical () inline
Return true if optical physics are enabled.
Returns
True if optical physics are enabled; false if not.
Definition at line 95 of file PhysicsListManager.hh.
{
             return m_enableOptical;
         }
References PhysicsListManager::m_enableOptical.
Referenced by PhysicsListManager::createPhysicsList(), and PhysicsListManager::enableOptical().
enableOptical() [2/2]
void enableOptical (bool enableOptical) inline
Enable optical physics.
Parameters
[in] enableOptical Set to true to enable optical physics; false to disable.
Definition at line 103 of file PhysicsListManager.hh.
{
             m_enableOptical = enableOptical;
         }
References PhysicsListManager::enableOptical(), and PhysicsListManager::m_enableOptical.
getCurrentListName()
const std::string& getCurrentListName () inline
Get the name of the current physics list.
Returns
The name of the current physics list.
Definition at line 63 of file PhysicsListManager.hh.
{
             return m_currentListName;
         }
References PhysicsListManager::m_currentListName.
Referenced by PhysicsMessenger::SetNewValue().
isInitialized()
bool isInitialized () inline
Return true if the physics list has been initialized.
Returns
True if list has been initialized; false if not.
Definition at line 71 of file PhysicsListManager.hh.
{
             return m_isInitialized;
         }
References PhysicsListManager::m_isInitialized.
Referenced by PhysicsMessenger::SetNewValue().
printAvailablePhysicsLists()
void printAvailablePhysicsLists ()
Print a list of available physics lists.
Definition at line 86 of file PhysicsListManager.cc.
{
     const std::vector<G4String>& lists = m_factory->AvailablePhysLists();
     for (std::vector<G4String>::const_iterator it = lists.begin(); it != lists.end(); it++) {
         log().always(*it);
     }
 }
References LogStream::always(), Module::log(), and PhysicsListManager::m_factory.
setCurrentListName()
void setCurrentListName (const std::string & name)
Set the name of the current physics list. Only available in pre-init state.
Parameters
[in] name The name of the physics list.
Definition at line 35 of file PhysicsListManager.cc.
{
     m_currentListName = n;
     m_isFromDefault = false;
 }
References PhysicsListManager::m_currentListName, and PhysicsListManager::m_isFromDefault.
Referenced by PhysicsMessenger::SetNewValue().
setupSUSY()
void setupSUSY () private
Setup SUSY physics.
setupUserLimitsProcesses()
void setupUserLimitsProcesses ()
Set up the user limits process.
Definition at line 63 of file PhysicsListManager.cc.
{
     G4ParticleTable* ptbl = G4ParticleTable::GetParticleTable();
     G4ParticleTable::G4PTblDicIterator* piter = ptbl->GetIterator();
     G4UserSpecialCuts* cuts = new G4UserSpecialCuts("UserSpecialCuts");
     G4StepLimiter* slim = new G4StepLimiter("StepLimiter");
     piter->reset();
     while ((*piter)()) {
         G4ParticleDefinition* pdef = piter->value();
         G4ProcessManager* pmgr = pdef->GetProcessManager();
         // Add user limit processes for steps and special cuts.
         if (pmgr) {
             pmgr->AddProcess(slim, -1, -1, 3);
             pmgr->AddProcess(cuts, -1, -1, 4);
         } else {
             G4Exception("", "", FatalException, "G4ProcessManager is null.");
         }
     }
 }
Referenced by RunManager::InitializePhysics().
Member Data Documentation
m_currentList
G4VUserPhysicsList* m_currentList private
Definition at line 126 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::createPhysicsList().
m_currentListName
std::string m_currentListName private
Definition at line 136 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::createPhysicsList(), PhysicsListManager::getCurrentListName(), PhysicsListManager::PhysicsListManager(), and PhysicsListManager::setCurrentListName().
m_defaultListName
const std::string m_defaultListName = std::string("QGSP_BERT") static private
Definition at line 137 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::createPhysicsList(), and PhysicsListManager::PhysicsListManager().
m_enableLimits
bool m_enableLimits private
Definition at line 130 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::enableLimits().
m_enableOptical
bool m_enableOptical private
Definition at line 132 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::enableOptical().
m_factory
G4PhysListFactory* m_factory private
Definition at line 139 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::createPhysicsList(), PhysicsListManager::PhysicsListManager(), and PhysicsListManager::printAvailablePhysicsLists().
m_isFromDefault
bool m_isFromDefault private
Definition at line 129 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::createPhysicsList(), and PhysicsListManager::setCurrentListName().
m_isInitialized
bool m_isInitialized private
Definition at line 128 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::isInitialized().
m_messenger
PhysicsMessenger* m_messenger private
Definition at line 134 of file PhysicsListManager.hh.
Referenced by PhysicsListManager::PhysicsListManager().
m_setupLimits
bool m_setupLimits private
Definition at line 131 of file PhysicsListManager.hh.
The documentation for this class was generated from the following files:
PhysicsListManager.hh
PhysicsListManager.cc