SLIC: SlicMain Class Reference
SlicMain Class Reference
A wrapper for the main method of SLIC.
#include <SlicMain.hh>
Public Member Functions
SlicMain ()
virtual ~SlicMain ()
int main (int argc, char **argv)
Public Member Functions inherited from Module
virtual ~Module ()
virtual void beginEvent (const G4Event *)
virtual void beginRun (const G4Run *)
virtual void cleanup ()
bool deleteOnExit ()
virtual void endEvent (const G4Event *)
virtual void endRun (const G4Run *)
const std::string & getName () const
ModuleStatus getStatus () const
virtual void initialize ()
LogStream & log ()
virtual void postTracking (const G4Track *)
virtual void preTracking (const G4Track *)
virtual void reset ()
virtual void stepping (const G4Step *)
Additional Inherited Members
Public Types inherited from Module
enum ModuleStatus { eOkay = 0, eNotInitialized = 1, eBadState = 2, eFatalError = 3 }
Public Attributes inherited from Module
bool m_deleteOnExit
LogStream * m_log
std::string m_name
ModuleStatus m_status
Protected Member Functions inherited from Module
Module (const std::string &name, bool deleteOnExit=true, bool autoRegister=true)
Detailed Description
A wrapper for the main method of SLIC.
Definition at line 12 of file SlicMain.hh.
Constructor & Destructor Documentation
SlicMain()
SlicMain ()
Class constructor.
Definition at line 11 of file SlicMain.cc.
~SlicMain()
~SlicMain () virtual
Class destructor.
Definition at line 16 of file SlicMain.cc.
Member Function Documentation
main()
int main (int argc, char ** argv)
Execute the main method by instantiating the SlicApplication and passing control to it.
Parameters
[in] argc The argument count.
[in] argc The argument values.
Definition at line 20 of file SlicMain.cc.
References LOG::done, LOG::endl, LOG::error, SlicApplication::getReturnCode(), LOG::head, SlicApplication::initialize(), Singleton< SlicApplication >::instance(), Module::log(), SlicApplication::run(), SlicApplication::STD_EXCEPTION, and SlicApplication::UNKNOWN_EXCEPTION.
The documentation for this class was generated from the following files:
SlicMain.hh
SlicMain.cc