/control/verbose 2

/lcdd/url examples/cal/ecap.lcdd

/lcio/path .
/lcio/filename lcioOutputFile

/run/initialize

/gps/particle mu-
/gps/energy 10 GeV
/gps/position 0 600 300 mm
/gps/direction 0 0 -1

/control/execute macros/heprep2.mac

/vis/drawTree
/vis/scene/add/hits
/vis/scene/add/trajectories

/vis/open OGLIX
/vis/viewer/panTo ! .7
/vis/viewer/zoom 2
/vis/viewer/set/viewpointThetaPhi 90 0

#/run/beamOn
