IF( NOT LCDD_VERSION )
    SET( LCDD_VERSION "master" )
ENDIF()

EXTERNALPROJECT_ADD(
    LCDD

    GIT_REPOSITORY "https://github.com/slaclab/lcdd"
    GIT_TAG "${LCDD_VERSION}"
    
    UPDATE_COMMAND ""
    PATCH_COMMAND ""

    SOURCE_DIR "${CMAKE_BINARY_DIR}/extdep/lcdd"
    CMAKE_ARGS -DINSTALL_DOC=OFF -DCMAKE_INSTALL_PREFIX=${GLOBAL_INSTALL_DIR}/lcdd -DGDML_DIR=${GDML_DIR} -DXERCES_DIR=${XERCES_DIR} -DGeant4_DIR=${Geant4_DIR}
    
    BUILD_COMMAND make -j4
)

SET( LCDD_DIR ${GLOBAL_INSTALL_DIR}/lcdd )

# TODO: move to UseLCDD macro
SET( LCDD_INCLUDE_DIR ${LCDD_DIR}/include )
SET( LCDD_LIBRARY_DIR ${LCDD_DIR}/lib )
SET( LCDD_LIBRARY lcdd )
