IF( NOT GDML_VERSION )
    SET( GDML_VERSION "master" )
ENDIF()

EXTERNALPROJECT_ADD(

    GDML

    DEPENDS XERCES Geant4 

    GIT_REPOSITORY "https://github.com/slaclab/gdml"
    GIT_TAG ${GDML_VERSION}
    
    UPDATE_COMMAND ""
    PATCH_COMMAND ""

    SOURCE_DIR "${CMAKE_BINARY_DIR}/gdml"
    CMAKE_ARGS -DDEPENDENCY_INSTALL_DIR=${DEPENDENCY_INSTALL_DIR}/gdml -DXERCES_DIR=${XERCES_DIR} -DGeant4_DIR=${Geant4_DIR}
    
    BUILD_COMMAND make -j4
)

SET( GDML_DIR ${DEPENDENCY_INSTALL_DIR}/gdml CACHE PATH "GDML install dir" FORCE )
