IF( NOT LCIO_VERSION )
    SET( LCIO_VERSION "master" )
ENDIF()

EXTERNALPROJECT_ADD(
    LCIO

    GIT_REPOSITORY "https://github.com/iLCSoft/LCIO"
    GIT_TAG "${LCIO_VERSION}"
    
    UPDATE_COMMAND ""
    PATCH_COMMAND ""

    SOURCE_DIR "${CMAKE_BINARY_DIR}/extdep/lcio"
    CMAKE_ARGS -DINSTALL_DOC=OFF -DCMAKE_INSTALL_PREFIX=${GLOBAL_INSTALL_DIR}/lcio
    
    BUILD_COMMAND make -j4
)

SET( LCIO_DIR ${GLOBAL_INSTALL_DIR}/lcio CACHE PATH "LCIO install dir" FORCE )
