IF( NOT LCIO_TAG )
    SET( LCIO_TAG "master" )
ENDIF()

EXTERNALPROJECT_ADD(
    LCIO

    GIT_REPOSITORY "https://github.com/iLCSoft/LCIO"
    GIT_TAG ${LCIO_TAG}
    
    UPDATE_COMMAND ""
    PATCH_COMMAND ""

    SOURCE_DIR "${CMAKE_BINARY_DIR}/lcio"
    CMAKE_ARGS -DINSTALL_DOC=OFF -DCMAKE_INSTALL_PREFIX=${DEPENDENCY_INSTALL_DIR}/lcio
    
    BUILD_COMMAND make -j4
    INSTALL_COMMAND make install COMMAND mkdir ${DEPENDENCY_INSTALL_DIR}/lcio/cmake COMMAND cp ${CMAKE_BINARY_DIR}/lcio/cmake/MacroCheckPackageVersion.cmake ${DEPENDENCY_INSTALL_DIR}/lcio/cmake COMMAND cp ${CMAKE_BINARY_DIR}/lcio/cmake/MacroCheckPackageLibs.cmake ${DEPENDENCY_INSTALL_DIR}/lcio/cmake
)

SET( LCIO_DIR ${DEPENDENCY_INSTALL_DIR}/lcio CACHE PATH "LCIO install dir" FORCE )
